// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace InteriorCamera {

// マネキン[B](室内のみ) (GROUP_00021)
void マネキン_B_室内のみ_024ee72f1954(CTRPluginFramework::MenuEntry *entry);

// 願う(室内) (GROUP_00075)
void 願う_室内_0714d4b0fcd6(CTRPluginFramework::MenuEntry *entry);

// コケる室内 (GROUP_00095)
void コケる室内_091c58154e71(CTRPluginFramework::MenuEntry *entry);

// ポムポムプリン (GROUP_00111)
void ポムポムプリン_0b1a87f6495e(CTRPluginFramework::MenuEntry *entry);

// マイメロディ (GROUP_00176)
void マイメロディ_13da6bf90382(CTRPluginFramework::MenuEntry *entry);

// カメラズーム (GROUP_00262)
void カメラズーム_1e19624d2bcc(CTRPluginFramework::MenuEntry *entry);

// 煙(消えない) (GROUP_00278)
void 煙_消えない_1f89ad7ee244(CTRPluginFramework::MenuEntry *entry);

// 空を見上げない (GROUP_00299)
void 空を見上げない_219a39d9e503(CTRPluginFramework::MenuEntry *entry);

// スプラ家具セット (GROUP_00340)
void スプラ家具セット_25e8b50d4918(CTRPluginFramework::MenuEntry *entry);

// 歩いた所を消す(室内非対応) (GROUP_00350)
void 歩いた所を消す_室内非対応_26d46a192df7(CTRPluginFramework::MenuEntry *entry);

// 下画面=上画面 (GROUP_00430)
void 下画面_上画面_2eeec1be92ea(CTRPluginFramework::MenuEntry *entry);

// 外と室内対応動作 (GROUP_00495)
void 外と室内対応動作_366c6c9563a7(CTRPluginFramework::MenuEntry *entry);

// 岩をたたく(室内) (GROUP_00551)
void 岩をたたく_室内_3bd2515c616c(CTRPluginFramework::MenuEntry *entry);

// 飛行ドローン[Cスティックで操作] (GROUP_00563)
void 飛行ドローン_Cスティックで操作_3d0009904f4d(CTRPluginFramework::MenuEntry *entry);

// アクション実験用 (GROUP_00605)
void アクション実験用_421db48d1f60(CTRPluginFramework::MenuEntry *entry);

// カメラ座標移動 (GROUP_00674)
void カメラ座標移動_488edc26cf94(CTRPluginFramework::MenuEntry *entry);

// 黄金家具セット (GROUP_00721)
void 黄金家具セット_4c98075903d3(CTRPluginFramework::MenuEntry *entry);

// 頭が坊主になる (GROUP_00737)
void 頭が坊主になる_4e1bed20d472(CTRPluginFramework::MenuEntry *entry);

// けろけろけろっぴ (GROUP_00776)
void けろけろけろっぴ_51cc790be0f6(CTRPluginFramework::MenuEntry *entry);

// 点滅1 (GROUP_00799)
void 点滅1_548ad95cd617(CTRPluginFramework::MenuEntry *entry);

// カメラ固定 (GROUP_00802)
void カメラ固定_54d120856f90(CTRPluginFramework::MenuEntry *entry);

// 空を見上げない OFF (GROUP_00895)
void 空を見上げない_OFF_5eac58c03597(CTRPluginFramework::MenuEntry *entry);

// カメラを回す 操作タイプB (GROUP_01047)
void カメラを回す_操作タイプB_6ff698be4d04(CTRPluginFramework::MenuEntry *entry);

// 島にある引き取りボックス機能変更 (GROUP_01066)
void 島にある引き取りボックス機能変更_71bd8776a44c(CTRPluginFramework::MenuEntry *entry);

// カメラを回す 操作タイプA (GROUP_01102)
void カメラを回す_操作タイプA_7562183c368e(CTRPluginFramework::MenuEntry *entry);

// 家具回る (GROUP_01221)
void 家具回る_82b9cf242325(CTRPluginFramework::MenuEntry *entry);

// 点滅2 (GROUP_01245)
void 点滅2_8570ee724340(CTRPluginFramework::MenuEntry *entry);

// キキ&ララ (GROUP_01256)
void キキ_ララ_866a18f0d539(CTRPluginFramework::MenuEntry *entry);

// 室内で拾える(on) (GROUP_01262)
void 室内で拾える_on_87106944e4b9(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート3P(室内) (GROUP_01392)
void プレイヤーテレポート3P_室内_950c48be3890(CTRPluginFramework::MenuEntry *entry);

// 歩いた所を消す室内 (オン未対応) (GROUP_01415)
void 歩いた所を消す室内_オン未対応_97f9445f40b5(CTRPluginFramework::MenuEntry *entry);

// 画面横向き (GROUP_01454)
void 画面横向き_9bc2c17d02dd(CTRPluginFramework::MenuEntry *entry);

// 誰かがいても家具動かせる (GROUP_01477)
void 誰かがいても家具動かせる_9e88e9d6c865(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート2P(室内) (GROUP_01501)
void プレイヤーテレポート2P_室内_a1645ec008f8(CTRPluginFramework::MenuEntry *entry);

// 広角カメラ (GROUP_01503)
void 広角カメラ_a1836951f283(CTRPluginFramework::MenuEntry *entry);

// ストーカー室内版 (GROUP_01620)
void ストーカー室内版_acc8aae5b967(CTRPluginFramework::MenuEntry *entry);

// ハローキティ (GROUP_01663)
void ハローキティ_b3447e9d48a8(CTRPluginFramework::MenuEntry *entry);

// 岩たたく 室内 (GROUP_01734)
void 岩たたく_室内_ba77c505c238(CTRPluginFramework::MenuEntry *entry);

// 歩いた所を消す室内 (GROUP_01753)
void 歩いた所を消す室内_bc5ca505dcf0(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート1P(室内) (GROUP_01848)
void プレイヤーテレポート1P_室内_c7164ebdd525(CTRPluginFramework::MenuEntry *entry);

// 煙(消える) (GROUP_01867)
void 煙_消える_c8aa67cb3a09(CTRPluginFramework::MenuEntry *entry);

// 視点動かす (GROUP_02076)
void 視点動かす_df1d94ca82b6(CTRPluginFramework::MenuEntry *entry);

// 服装変更(室内のみ) (GROUP_02078)
void 服装変更_室内のみ_df3f73ac1f88(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート4P(室内) (GROUP_02288)
void プレイヤーテレポート4P_室内_f4f4f7c6a40b(CTRPluginFramework::MenuEntry *entry);

// どこかにワープ (GROUP_02396)
void どこかにワープ_ff92d5e885c6(CTRPluginFramework::MenuEntry *entry);

} }
