// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#include "InterfaceCommunication.hpp"
#include <3ds.h>
#include <functional>

namespace ReferenceCheats { namespace InterfaceCommunication {
using namespace CTRPluginFramework;

// 名称: 字数制限解除(54文字)
// Group: GROUP_00034 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L13 (AR_3de7cf64879c473a)
// 出典: reference/old_project/REFERENCES/CHEATS/by_mame.txt:L4962 (AR_7a4a3fef2901ad3f)
void 字数制限解除_54文字_039ad0557401(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L14
    offset[0] = 0x32000000u;
}
step1: { // Source L15
    (void)Process::Write32(0x00E15624u + offset[activeOffset], static_cast<u32>(0x00000036u));
}
step2: { // Source L16
    (void)Process::Write32(0x00E15740u + offset[activeOffset], static_cast<u32>(0x45800000u));
}
step3: { // Source L17
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step4:
    return;
}

// 名称: Disable Bottom Screen
// Group: GROUP_00260 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ui.txt:L6 (AR_5ac5422f958f7a8e)
void Disable_Bottom_Screen_1da9ab376182(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L7
    if (!(Controller::IsKeysDown(0x00000100u))) goto step2;
}
step1: { // Source L8
    (void)Process::Write32(0x00ACF6E0u + offset[activeOffset], static_cast<u32>(0x00630000u));
}
step2:
    return;
}

// 名称: チャットの赤線のサイズ
// Group: GROUP_00483 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L42 (AR_0a0e98cb9b57d422)
// 原注: 00000000 X
// 原注: 00000004 X
void チャットの赤線のサイズ_353fa77ced47(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L43
    offset[0] = 0x32E3DF60u;
}
step1: { // Source L46
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step2:
    return;
}

// 名称: チャットの点滅する赤い線がレインボーになる
// Group: GROUP_00711 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L35 (AR_b0c0d992284338b4)
void チャットの点滅する赤い線がレインボーになる_4c450edfe1ee(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
    const auto read32 = [](u32 address, u32 &destination) {
        (void)Process::Read32(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
step0: { // Source L36
    offset[0] = 0x32E3E4A0u;
}
step1: { // Source L37
    (void)Process::Write32(0x00000000u + offset[activeOffset], static_cast<u32>(0x3F800000u));
}
step2: { // Source L38
    // True-path D0 is a no-op; false-path exits were emitted at the condition.
}
step3: { // Source L39
    offset[0] = 0x32E3E0D0u;
}
step4: { // Source L40
    read32(0x00000000u + offset[activeOffset], value.bits);
    (void)Process::Write32(0x00000000u + offset[activeOffset], value.bits + 0xFF777777u);
}
step5:
    return;
}

// 名称: @制限解除
// Group: GROUP_00857 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L5 (AR_04a6acbee470294a)
// 出典: reference/old_project/REFERENCES/CHEATS/by_mame.txt:L4973 (AR_cf7857b4f1afb853)
void 制限解除_5a9fba2e0312(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L6
    (void)Process::Write32(0x00AD05C0u + offset[activeOffset], static_cast<u32>(0x00000000u));
}
step1:
    return;
}

// 名称: タイマーチート
// Group: GROUP_00912 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L29 (AR_9b2ff30921234006)
// 原注: {1行目@虫　2行目@魚　3行目@海の幸}
void タイマーチート_60c02a293405(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L30
    (void)Process::Write32(0x0094A724u + offset[activeOffset], static_cast<u32>(0x99999999u));
}
step1: { // Source L31
    (void)Process::Write32(0x0094A72Cu + offset[activeOffset], static_cast<u32>(0x99999999u));
}
step2: { // Source L32
    (void)Process::Write32(0x0094A728u + offset[activeOffset], static_cast<u32>(0x99999999u));
}
step3:
    return;
}

// 名称: 字数制限解除(32文字)
// Group: GROUP_00937 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L8 (AR_af2358f3dd435a11)
// 出典: reference/old_project/REFERENCES/CHEATS/by_mame.txt:L4957 (AR_cde83de557747980)
void 字数制限解除_32文字_636b9009cc87(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L9
    offset[0] = 0x32000000u;
}
step1: { // Source L10
    (void)Process::Write32(0x00E15740u + offset[activeOffset], static_cast<u32>(0x45800000u));
}
step2: { // Source L11
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step3:
    return;
}

// 名称: 送ったメッセージがすぐに消える
// Group: GROUP_00980 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/by_yuuma.txt:L14933 (AR_1da1067328aad448)
void 送ったメッセージがすぐに消える_682cc90e6471(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L14934
    offset[0] = 0x33000000u;
}
step1: { // Source L14935
    (void)Process::Write32(0x0009D4E0u + offset[activeOffset], static_cast<u32>(0x01000100u));
}
step2: { // Source L14936
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step3:
    return;
}

// 名称: メッセージテキスト音を変える
// Group: GROUP_01063 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/by_mame.txt:L4976 (AR_fdc794951c1a5243)
void メッセージテキスト音を変える_71734129748e(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L4977
    (void)Process::Write32(0x0071FF1Cu + offset[activeOffset], static_cast<u32>(0x01000648u));
}
step1:
    return;
}

// 名称: chat akasen
// Group: GROUP_01127 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/テクスチャ・バッジ系/ボタンアイコン.txt:L207 (AR_576057e04792acbf)
void chat_akasen_78e95a4e0110(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L208
    offset[0] = 0x32000000u;
}
step1: { // Source L209
    (void)Process::Write32(0x00E3E4A0u + offset[activeOffset], static_cast<u32>(0x3F800000u));
}
step2: { // Source L210
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step3:
    return;
}

// 名称: Menu??
// Group: GROUP_01172 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ui.txt:L10 (AR_9bc125eed512235d)
void Menu_7dde79f8559f(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L11
    (void)Process::Write32(0x005FAF68u + offset[activeOffset], static_cast<u32>(0xEBFFF4B2u));
}
step1:
    return;
}

// 名称: ウィンドウ解除
// Group: GROUP_01441 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/by_yuuma.txt:L2641 (AR_b875f3595c1047f5)
// 原注: {Prese :}
void ウィンドウ解除_9a9302c70c75(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L2642
    offset[0] = 0x33000000u;
}
step1: { // Source L2643
    if (!(Controller::IsKeysDown(0x00000240u))) goto step3;
}
step2: { // Source L2644
    (void)Process::Write32(0x00099FE4u + offset[activeOffset], static_cast<u32>(0x060D0600u));
}
step3: { // Source L2645
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step4:
    return;
}

// 名称: メニューアニメーションをカット
// Group: GROUP_01489 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ui.txt:L1 (AR_9e8527bfbd02d8a9)
void メニューアニメーションをカット_9fc235c46688(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L2
    (void)Process::Write32(0x005FAF68u + offset[activeOffset], static_cast<u32>(0xE1A00000u));
}
step1: { // Source L3
    (void)Process::Write32(0x005FB298u + offset[activeOffset], static_cast<u32>(0x43B00000u));
}
step2: { // Source L4
    (void)Process::Write32(0x00568BF8u + offset[activeOffset], static_cast<u32>(0x43B00000u));
}
step3:
    return;
}

// 名称: カスタムキーボード
// Group: GROUP_01967 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/チャット.txt:L51 (AR_b8bc431c9febcd5d)
void カスタムキーボード_d44486b682f7(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    const auto read32 = [](u32 address, u32 &destination) {
        (void)Process::Read32(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
    const auto read16 = [](u32 address, u16 &destination) {
        (void)Process::Read16(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
    bool exitAll = false;
    std::function<bool(u32, u32)> run;
    run = [&](u32 begin, u32 end) -> bool {
        // Original _Execute gives every recursive call its own read scratch.
        union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
        u16 value16 = 0;
        for (u32 pc = begin; pc < end && !exitAll; ++pc) {
            switch (pc) {
            case 0u: { // Source L52
                offset[1] = 0x32DDCC76u;
                break;
            }
            case 1u: { // Source L53
                read16(0x00AAE990u + offset[activeOffset], value16);
                value16 &= static_cast<u16>(~(0xFFF00003u >> 16));
                // Comparison order is immediate < memory, as in the original AR handler.
                if (!((0xFFF00003u & 0xFFFFu) < value16)) { pc = (4u < end ? 4u : end) - 1u; }
                break;
            }
            case 2u: { // Source L54
                offset[1] = 0x32DE91F6u;
                break;
            }
            case 3u: { // Source L55
                // True-path D0 is a no-op; false-path exits were emitted at the condition.
                break;
            }
            case 4u: { // Source L56
                offset[0] = offset[1];
                break;
            }
            case 5u: { // Source L57
                read32(0x00000000u + offset[activeOffset], value.bits);
                // Comparison order is immediate == memory, as in the original AR handler.
                if (!(0x002C002Eu == value.bits)) { pc = (62u < end ? 62u : end) - 1u; }
                break;
            }
            case 6u: { // Source L58
                if (62u >= end) { pc = end; break; }
                const u32 iterations = 0x00000001u;
                const u32 dataBeforeLoop = activeData;
                for (u32 remaining = iterations; remaining && !exitAll; --remaining) {
                    if (run(7u, 62u)) break;
                }
                pc = 62u;
                // D2 binds currentData before executing the pending loop.
                offset[activeOffset] = 0;
                data[dataBeforeLoop] = 0;
                break;
            }
            case 7u: { // Source L59
                (void)Process::Write32(0x00000000u + offset[activeOffset], static_cast<u32>(0xE001E000u));
                break;
            }
            case 8u: { // Source L60
                (void)Process::Write32(0x00000004u + offset[activeOffset], static_cast<u32>(0xE003E002u));
                break;
            }
            case 9u: { // Source L61
                (void)Process::Write32(0x00000008u + offset[activeOffset], static_cast<u32>(0xE005E004u));
                break;
            }
            case 10u: { // Source L62
                (void)Process::Write32(0x0000000Cu + offset[activeOffset], static_cast<u32>(0xE008E006u));
                break;
            }
            case 11u: { // Source L63
                (void)Process::Write32(0x00000010u + offset[activeOffset], static_cast<u32>(0xE070E009u));
                break;
            }
            case 12u: { // Source L64
                (void)Process::Write32(0x00000014u + offset[activeOffset], static_cast<u32>(0xE06CE06Fu));
                break;
            }
            case 13u: { // Source L65
                (void)Process::Write32(0x00000018u + offset[activeOffset], static_cast<u32>(0xE00DE00Cu));
                break;
            }
            case 14u: { // Source L66
                (void)Process::Write32(0x0000001Cu + offset[activeOffset], static_cast<u32>(0xE00FE00Eu));
                break;
            }
            case 15u: { // Source L67
                (void)Process::Write32(0x00000020u + offset[activeOffset], static_cast<u32>(0xE011E010u));
                break;
            }
            case 16u: { // Source L68
                (void)Process::Write32(0x00000024u + offset[activeOffset], static_cast<u32>(0xE013E012u));
                break;
            }
            case 17u: { // Source L69
                (void)Process::Write32(0x00000028u + offset[activeOffset], static_cast<u32>(0xE03CE014u));
                break;
            }
            case 18u: { // Source L70
                (void)Process::Write32(0x0000002Cu + offset[activeOffset], static_cast<u32>(0xE03DE03Cu));
                break;
            }
            case 19u: { // Source L71
                (void)Process::Write32(0x00000030u + offset[activeOffset], static_cast<u32>(0xE019E072u));
                break;
            }
            case 20u: { // Source L72
                (void)Process::Write32(0x00000034u + offset[activeOffset], static_cast<u32>(0xE01BE01Au));
                break;
            }
            case 21u: { // Source L73
                (void)Process::Write32(0x00000038u + offset[activeOffset], static_cast<u32>(0xE01DE01Cu));
                break;
            }
            case 22u: { // Source L74
                (void)Process::Write32(0x0000003Cu + offset[activeOffset], static_cast<u32>(0xE01FE01Eu));
                break;
            }
            case 23u: { // Source L75
                (void)Process::Write32(0x00000040u + offset[activeOffset], static_cast<u32>(0xE021E020u));
                break;
            }
            case 24u: { // Source L76
                (void)Process::Write32(0x00000044u + offset[activeOffset], static_cast<u32>(0xE023E022u));
                break;
            }
            case 25u: { // Source L77
                (void)Process::Write32(0x00000048u + offset[activeOffset], static_cast<u32>(0xE025E024u));
                break;
            }
            case 26u: { // Source L78
                (void)Process::Write32(0x0000004Cu + offset[activeOffset], static_cast<u32>(0xE027E026u));
                break;
            }
            case 27u: { // Source L79
                (void)Process::Write32(0x00000050u + offset[activeOffset], static_cast<u32>(0xE029E028u));
                break;
            }
            case 28u: { // Source L80
                (void)Process::Write32(0x00000054u + offset[activeOffset], static_cast<u32>(0xE02BE02Au));
                break;
            }
            case 29u: { // Source L81
                (void)Process::Write32(0x00000058u + offset[activeOffset], static_cast<u32>(0xE02DE02Cu));
                break;
            }
            case 30u: { // Source L82
                (void)Process::Write32(0x0000005Cu + offset[activeOffset], static_cast<u32>(0xE02FE02Eu));
                break;
            }
            case 31u: { // Source L83
                (void)Process::Write32(0x00000060u + offset[activeOffset], static_cast<u32>(0xE031E030u));
                break;
            }
            case 32u: { // Source L84
                (void)Process::Write32(0x00000064u + offset[activeOffset], static_cast<u32>(0xE033E032u));
                break;
            }
            case 33u: { // Source L85
                (void)Process::Write32(0x00000068u + offset[activeOffset], static_cast<u32>(0xE035E034u));
                break;
            }
            case 34u: { // Source L86
                (void)Process::Write32(0x0000006Cu + offset[activeOffset], static_cast<u32>(0xE037E036u));
                break;
            }
            case 35u: { // Source L87
                (void)Process::Write32(0x00000070u + offset[activeOffset], static_cast<u32>(0xE039E038u));
                break;
            }
            case 36u: { // Source L88
                (void)Process::Write32(0x00000074u + offset[activeOffset], static_cast<u32>(0xE07AE079u));
                break;
            }
            case 37u: { // Source L89
                (void)Process::Write32(0x00000078u + offset[activeOffset], static_cast<u32>(0xE07CE07Bu));
                break;
            }
            case 38u: { // Source L90
                (void)Process::Write32(0x0000007Cu + offset[activeOffset], static_cast<u32>(0xE03FE03Eu));
                break;
            }
            case 39u: { // Source L91
                (void)Process::Write32(0x00000080u + offset[activeOffset], static_cast<u32>(0xE041E040u));
                break;
            }
            case 40u: { // Source L92
                (void)Process::Write32(0x00000084u + offset[activeOffset], static_cast<u32>(0xE043E042u));
                break;
            }
            case 41u: { // Source L93
                (void)Process::Write32(0x00000088u + offset[activeOffset], static_cast<u32>(0xE045E044u));
                break;
            }
            case 42u: { // Source L94
                (void)Process::Write32(0x0000008Cu + offset[activeOffset], static_cast<u32>(0xE047E046u));
                break;
            }
            case 43u: { // Source L95
                (void)Process::Write32(0x00000090u + offset[activeOffset], static_cast<u32>(0xE049E048u));
                break;
            }
            case 44u: { // Source L96
                (void)Process::Write32(0x00000094u + offset[activeOffset], static_cast<u32>(0xE04BE04Au));
                break;
            }
            case 45u: { // Source L97
                (void)Process::Write32(0x00000098u + offset[activeOffset], static_cast<u32>(0xE04DE04Cu));
                break;
            }
            case 46u: { // Source L98
                (void)Process::Write32(0x0000009Cu + offset[activeOffset], static_cast<u32>(0xE04FE04Eu));
                break;
            }
            case 47u: { // Source L99
                (void)Process::Write32(0x000000A0u + offset[activeOffset], static_cast<u32>(0xE051E050u));
                break;
            }
            case 48u: { // Source L100
                (void)Process::Write32(0x000000A4u + offset[activeOffset], static_cast<u32>(0xE053E052u));
                break;
            }
            case 49u: { // Source L101
                (void)Process::Write32(0x000000A8u + offset[activeOffset], static_cast<u32>(0xE055E054u));
                break;
            }
            case 50u: { // Source L102
                (void)Process::Write32(0x000000ACu + offset[activeOffset], static_cast<u32>(0xE057E056u));
                break;
            }
            case 51u: { // Source L103
                (void)Process::Write32(0x000000B0u + offset[activeOffset], static_cast<u32>(0xE059E058u));
                break;
            }
            case 52u: { // Source L104
                (void)Process::Write32(0x000000B4u + offset[activeOffset], static_cast<u32>(0xE05BE05Au));
                break;
            }
            case 53u: { // Source L105
                (void)Process::Write32(0x000000B8u + offset[activeOffset], static_cast<u32>(0xE05DE05Cu));
                break;
            }
            case 54u: { // Source L106
                (void)Process::Write32(0x000000BCu + offset[activeOffset], static_cast<u32>(0xE05FE05Eu));
                break;
            }
            case 55u: { // Source L107
                (void)Process::Write32(0x000000C0u + offset[activeOffset], static_cast<u32>(0xE061E060u));
                break;
            }
            case 56u: { // Source L108
                (void)Process::Write32(0x000000C4u + offset[activeOffset], static_cast<u32>(0xE063E062u));
                break;
            }
            case 57u: { // Source L109
                (void)Process::Write32(0x000000C8u + offset[activeOffset], static_cast<u32>(0xE065E064u));
                break;
            }
            case 58u: { // Source L110
                (void)Process::Write32(0x000000CCu + offset[activeOffset], static_cast<u32>(0xE067E069u));
                break;
            }
            case 59u: { // Source L111
                (void)Process::Write32(0x000000D0u + offset[activeOffset], static_cast<u32>(0xE074E073u));
                break;
            }
            case 60u: { // Source L112
                (void)Process::Write32(0x000000D4u + offset[activeOffset], static_cast<u32>(0xE076E075u));
                break;
            }
            case 61u: { // Source L113
                (void)Process::Write32(0x000000D8u + offset[activeOffset], static_cast<u32>(0xE078E077u));
                break;
            }
            case 62u: { // Source L114
                offset[activeOffset] = 0;
                data[activeData] = 0;
                break;
            }
            default: return false;
            }
        }
        return exitAll;
    };
    (void)run(0, 63u);
}

// 名称: Yで村名をキーボードに入力されている文字に変更
// Group: GROUP_02019 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/by_yuuma.txt:L1226 (AR_a9544a800e35727a)
void Yで村名をキーボードに入力されている文字に変更_da80491e270d(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
    const auto read32 = [](u32 address, u32 &destination) {
        (void)Process::Read32(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
    const auto read16 = [](u32 address, u16 &destination) {
        (void)Process::Read16(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
step0: { // Source L1227
    if (!(Controller::IsKeysDown(0x00000800u))) goto step41;
}
step1: { // Source L1228
    offset[0] = 0x00000000u;
}
step2: { // Source L1229
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step3: { // Source L1230
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step4: { // Source L1231
    read16(0x00000044u + offset[activeOffset], value16);
    data[activeData] = value16;
}
step5: { // Source L1232
    offset[0] = 0x00000000u;
}
step6: { // Source L1233
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step7: { // Source L1234
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step8: { // Source L1235
    (void)Process::Write16(0x000055BEu + offset[activeOffset], static_cast<u16>(data[activeData]));
    offset[activeOffset] += 2u;
}
step9: { // Source L1236
    offset[0] = 0x00000000u;
}
step10: { // Source L1237
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step11: { // Source L1238
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step12: { // Source L1239
    read32(0x00000046u + offset[activeOffset], data[activeData]);
}
step13: { // Source L1240
    offset[0] = 0x00000000u;
}
step14: { // Source L1241
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step15: { // Source L1242
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step16: { // Source L1243
    (void)Process::Write32(0x000055C0u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step17: { // Source L1244
    offset[0] = 0x00000000u;
}
step18: { // Source L1245
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step19: { // Source L1246
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step20: { // Source L1247
    read32(0x0000004Au + offset[activeOffset], data[activeData]);
}
step21: { // Source L1248
    offset[0] = 0x00000000u;
}
step22: { // Source L1249
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step23: { // Source L1250
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step24: { // Source L1251
    (void)Process::Write32(0x000055C4u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step25: { // Source L1252
    offset[0] = 0x00000000u;
}
step26: { // Source L1253
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step27: { // Source L1254
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step28: { // Source L1255
    read32(0x0000004Eu + offset[activeOffset], data[activeData]);
}
step29: { // Source L1256
    offset[0] = 0x00000000u;
}
step30: { // Source L1257
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step31: { // Source L1258
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step32: { // Source L1259
    (void)Process::Write32(0x000055C8u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step33: { // Source L1260
    offset[0] = 0x00000000u;
}
step34: { // Source L1261
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step35: { // Source L1262
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step36: { // Source L1263
    read16(0x00000052u + offset[activeOffset], value16);
    data[activeData] = value16;
}
step37: { // Source L1264
    offset[0] = 0x00000000u;
}
step38: { // Source L1265
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step41;
}
step39: { // Source L1266
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step40: { // Source L1267
    (void)Process::Write16(0x000055CCu + offset[activeOffset], static_cast<u16>(data[activeData]));
    offset[activeOffset] += 2u;
}
step41:
    return;
}

// 名称: Xで名前をキーボードに入力されている文字に変更
// Group: GROUP_02187 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/by_yuuma.txt:L1189 (AR_2cf388b9ad5e2bc7)
void Xで名前をキーボードに入力されている文字に変更_ea1e62055923(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
    const auto read32 = [](u32 address, u32 &destination) {
        (void)Process::Read32(address, destination);
        // AR leaves the previous value on an inaccessible read and continues.
    };
step0: { // Source L1190
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step1: { // Source L1191
    if (!(Controller::IsKeysDown(0x00000400u))) goto step34;
}
step2: { // Source L1192
    offset[0] = 0x00000000u;
}
step3: { // Source L1193
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step4: { // Source L1194
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step5: { // Source L1195
    read32(0x00000044u + offset[activeOffset], data[activeData]);
}
step6: { // Source L1196
    offset[0] = 0x00000000u;
}
step7: { // Source L1197
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step8: { // Source L1198
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step9: { // Source L1199
    (void)Process::Write32(0x000055A8u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step10: { // Source L1200
    offset[0] = 0x00000000u;
}
step11: { // Source L1201
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step12: { // Source L1202
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step13: { // Source L1203
    read32(0x00000048u + offset[activeOffset], data[activeData]);
}
step14: { // Source L1204
    offset[0] = 0x00000000u;
}
step15: { // Source L1205
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step16: { // Source L1206
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step17: { // Source L1207
    (void)Process::Write32(0x000055ACu + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step18: { // Source L1208
    offset[0] = 0x00000000u;
}
step19: { // Source L1209
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step20: { // Source L1210
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step21: { // Source L1211
    read32(0x0000004Cu + offset[activeOffset], data[activeData]);
}
step22: { // Source L1212
    offset[0] = 0x00000000u;
}
step23: { // Source L1213
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step24: { // Source L1214
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step25: { // Source L1215
    (void)Process::Write32(0x000055B0u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step26: { // Source L1216
    offset[0] = 0x00000000u;
}
step27: { // Source L1217
    read32(0x00986500u + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step28: { // Source L1218
    read32(0x00986500u + offset[activeOffset], offset[activeOffset]);
}
step29: { // Source L1219
    read32(0x00000050u + offset[activeOffset], data[activeData]);
}
step30: { // Source L1220
    offset[0] = 0x00000000u;
}
step31: { // Source L1221
    read32(0x00AA914Cu + offset[activeOffset], value.bits);
    // Comparison order is immediate != memory, as in the original AR handler.
    if (!(0x00000000u != value.bits)) goto step34;
}
step32: { // Source L1222
    read32(0x00AA914Cu + offset[activeOffset], offset[activeOffset]);
}
step33: { // Source L1223
    (void)Process::Write32(0x000055B4u + offset[activeOffset], static_cast<u32>(data[activeData]));
    offset[activeOffset] += 4u;
}
step34: { // Source L1224
    offset[activeOffset] = 0;
    data[activeData] = 0;
}
step35:
    return;
}

// 名称: 誰か来ました のウィンドウ出現
// Group: GROUP_02350 / IDA-gpt-6.1-sol-F018 / gpt-6.1-sol
// 確度LOW・実機未確認。ARの命令/条件/レジスタ/データ順を保持した変換。
// 元のアドレスを保持。現在の日本語更新版との完全な版一致は未確定。
// 元AR同様、OFFは実行停止のみ。明示された復元命令以外の書込みは自動復元しない。
// 出典: reference/old_project/REFERENCES/CHEATS/ACNL_ALPC/その他/システム系.txt:L2 (AR_220aaa130d7c9c2d)
void 誰か来ました_のウィンドウ出現_fb53f1854c54(MenuEntry *entry)
{
    if (!entry || !entry->IsActivated()) return;
    // Registers restart each invocation; no state is shared with another cheat.
    u32 offset[2] = {0, 0}, data[2] = {0, 0};
    u32 activeOffset = 0, activeData = 0;
    union Temporary { u32 bits; float real; Temporary() : bits(0) {} } value;
    u16 value16 = 0;
step0: { // Source L3
    (void)Process::Write32(0x00568960u + offset[activeOffset], static_cast<u32>(0x41800000u));
}
step1:
    return;
}

} }
