// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace InterfaceCommunication {

// 字数制限解除(54文字) (GROUP_00034)
void 字数制限解除_54文字_039ad0557401(CTRPluginFramework::MenuEntry *entry);

// Disable Bottom Screen (GROUP_00260)
void Disable_Bottom_Screen_1da9ab376182(CTRPluginFramework::MenuEntry *entry);

// チャットの赤線のサイズ (GROUP_00483)
void チャットの赤線のサイズ_353fa77ced47(CTRPluginFramework::MenuEntry *entry);

// チャットの点滅する赤い線がレインボーになる (GROUP_00711)
void チャットの点滅する赤い線がレインボーになる_4c450edfe1ee(CTRPluginFramework::MenuEntry *entry);

// @制限解除 (GROUP_00857)
void 制限解除_5a9fba2e0312(CTRPluginFramework::MenuEntry *entry);

// タイマーチート (GROUP_00912)
void タイマーチート_60c02a293405(CTRPluginFramework::MenuEntry *entry);

// 字数制限解除(32文字) (GROUP_00937)
void 字数制限解除_32文字_636b9009cc87(CTRPluginFramework::MenuEntry *entry);

// 送ったメッセージがすぐに消える (GROUP_00980)
void 送ったメッセージがすぐに消える_682cc90e6471(CTRPluginFramework::MenuEntry *entry);

// メッセージテキスト音を変える (GROUP_01063)
void メッセージテキスト音を変える_71734129748e(CTRPluginFramework::MenuEntry *entry);

// chat akasen (GROUP_01127)
void chat_akasen_78e95a4e0110(CTRPluginFramework::MenuEntry *entry);

// Menu?? (GROUP_01172)
void Menu_7dde79f8559f(CTRPluginFramework::MenuEntry *entry);

// ウィンドウ解除 (GROUP_01441)
void ウィンドウ解除_9a9302c70c75(CTRPluginFramework::MenuEntry *entry);

// メニューアニメーションをカット (GROUP_01489)
void メニューアニメーションをカット_9fc235c46688(CTRPluginFramework::MenuEntry *entry);

// カスタムキーボード (GROUP_01967)
void カスタムキーボード_d44486b682f7(CTRPluginFramework::MenuEntry *entry);

// Yで村名をキーボードに入力されている文字に変更 (GROUP_02019)
void Yで村名をキーボードに入力されている文字に変更_da80491e270d(CTRPluginFramework::MenuEntry *entry);

// Xで名前をキーボードに入力されている文字に変更 (GROUP_02187)
void Xで名前をキーボードに入力されている文字に変更_ea1e62055923(CTRPluginFramework::MenuEntry *entry);

// 誰か来ました のウィンドウ出現 (GROUP_02350)
void 誰か来ました_のウィンドウ出現_fb53f1854c54(CTRPluginFramework::MenuEntry *entry);

} }
