// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace ItemsInventory {

// 花無限が持ち物から消えない (GROUP_00007)
void 花無限が持ち物から消えない_00a21075cc52(CTRPluginFramework::MenuEntry *entry);

// 木セット (GROUP_00010)
void 木セット_00f8ea8aa8ab(CTRPluginFramework::MenuEntry *entry);

// 取る動作: 鉱石 (GROUP_00028)
void 取る動作_鉱石_02afecc75d8b(CTRPluginFramework::MenuEntry *entry);

// あける2 (GROUP_00037)
void あける2_03d8d6d4c041(CTRPluginFramework::MenuEntry *entry);

// 針葉樹 (GROUP_00052)
void 針葉樹_0531e01cd148(CTRPluginFramework::MenuEntry *entry);

// 木/岩 掘り起こす オフ (GROUP_00057)
void 木_岩_掘り起こす_オフ_0588ccd79a72(CTRPluginFramework::MenuEntry *entry);

// 花火1 (GROUP_00066)
void 花火1_065b157472e3(CTRPluginFramework::MenuEntry *entry);

// 沢山ばらまく [++] (GROUP_00078)
void 沢山ばらまく_07672f0651b8(CTRPluginFramework::MenuEntry *entry);

// ポケットにしまう (GROUP_00113)
void ポケットにしまう_0b844d2d2fe9(CTRPluginFramework::MenuEntry *entry);

// 落とし穴無効化 (GROUP_00116)
void 落とし穴無効化_0bee829fced1(CTRPluginFramework::MenuEntry *entry);

// 銀の道具 (GROUP_00158)
void 銀の道具_11cf0c45ed7c(CTRPluginFramework::MenuEntry *entry);

// 道具持つ (GROUP_00162)
void 道具持つ_12847a735f10(CTRPluginFramework::MenuEntry *entry);

// Cut (GROUP_00168)
void Cut_135267aa1113(CTRPluginFramework::MenuEntry *entry);

// Plank (GROUP_00177)
void Plank_13dac1d2e595(CTRPluginFramework::MenuEntry *entry);

// アイテム COPY OFF (GROUP_00182)
void アイテム_COPY_OFF_148be2fba484(CTRPluginFramework::MenuEntry *entry);

// 卵 アイテム全て戻す (GROUP_00184)
void 卵_アイテム全て戻す_149cf9de4b5c(CTRPluginFramework::MenuEntry *entry);

// お薬 (GROUP_00185)
void お薬_14aa028ae151(CTRPluginFramework::MenuEntry *entry);

// アイテム置ける範囲を広くする(1×1) (GROUP_00186)
void アイテム置ける範囲を広くする_1_1_14b2f42da0f2(CTRPluginFramework::MenuEntry *entry);

// アイテム複製 (持ち物参照 1番目) (GROUP_00200)
void アイテム複製_持ち物参照_1番目_15ea74c10bcb(CTRPluginFramework::MenuEntry *entry);

// アイス (GROUP_00205)
void アイス_16a52d9a8551(CTRPluginFramework::MenuEntry *entry);

// Tour Shovel Enable (GROUP_00212)
void Tour_Shovel_Enable_17784f28b302(CTRPluginFramework::MenuEntry *entry);

// 何でも拾って見せびらかす (GROUP_00217)
void 何でも拾って見せびらかす_17e49e9bc02e(CTRPluginFramework::MenuEntry *entry);

// 道具切り替え (GROUP_00220)
void 道具切り替え_1832ace405f3(CTRPluginFramework::MenuEntry *entry);

// アイテム無料 (GROUP_00239)
void アイテム無料_1a8e02153616(CTRPluginFramework::MenuEntry *entry);

// レンタル道具セット (GROUP_00245)
void レンタル道具セット_1b2de82946ee(CTRPluginFramework::MenuEntry *entry);

// 掘ったり埋めたり (GROUP_00246)
void 掘ったり埋めたり_1b41b6a159d3(CTRPluginFramework::MenuEntry *entry);

// 穴(デフォルト) (GROUP_00270)
void 穴_デフォルト_1ead3b281568(CTRPluginFramework::MenuEntry *entry);

// 何でも捨てる (GROUP_00272)
void 何でも捨てる_1f1bf952c162(CTRPluginFramework::MenuEntry *entry);

// ドロップ縦軸変更コード (GROUP_00274)
void ドロップ縦軸変更コード_1f416ff27602(CTRPluginFramework::MenuEntry *entry);

// 傘2 (GROUP_00283)
void 傘2_2019212bc0c1(CTRPluginFramework::MenuEntry *entry);

// 置いた場所に高速ドロップ [] (GROUP_00293)
void 置いた場所に高速ドロップ_20e4c04fa021(CTRPluginFramework::MenuEntry *entry);

// アイテムを拾う (GROUP_00298)
void アイテムを拾う_21819cd913bc(CTRPluginFramework::MenuEntry *entry);

// ドロップモーション [+] (GROUP_00353)
void ドロップモーション_27380698a00a(CTRPluginFramework::MenuEntry *entry);

// 拾って見せる (GROUP_00426)
void 拾って見せる_2e8e1a240abc(CTRPluginFramework::MenuEntry *entry);

// ポケットでアイテムを動かして置く (GROUP_00434)
void ポケットでアイテムを動かして置く_2f4bd13f1415(CTRPluginFramework::MenuEntry *entry);

// 財布リサイクルショップ化 (GROUP_00435)
void 財布リサイクルショップ化_2f4cf77a7d7a(CTRPluginFramework::MenuEntry *entry);

// 交番アイテム変更 (GROUP_00446)
void 交番アイテム変更_314c5e78cac9(CTRPluginFramework::MenuEntry *entry);

// 布切れ (GROUP_00447)
void 布切れ_31559a4a2732(CTRPluginFramework::MenuEntry *entry);

// アイテムセット (GROUP_00449)
void アイテムセット_3164206742b7(CTRPluginFramework::MenuEntry *entry);

// 卵 アイテム変更 (GROUP_00452)
void 卵_アイテム変更_31ae8fb6a40d(CTRPluginFramework::MenuEntry *entry);

// 高さ関係なくアイテム置ける (GROUP_00457)
void 高さ関係なくアイテム置ける_3217523edc49(CTRPluginFramework::MenuEntry *entry);

// アイテム指定 Inventory (GROUP_00470)
void アイテム指定_Inventory_33bb2d6b14ca(CTRPluginFramework::MenuEntry *entry);

// みる (GROUP_00482)
void みる_3521d3752b3c(CTRPluginFramework::MenuEntry *entry);

// can drop anywhere (GROUP_00497)
void can_drop_anywhere_36d276c9145a(CTRPluginFramework::MenuEntry *entry);

// ふきもどし (GROUP_00507)
void ふきもどし_37c6839e7cb3(CTRPluginFramework::MenuEntry *entry);

// アイテム置ける範囲を広くする(3×3) (GROUP_00513)
void アイテム置ける範囲を広くする_3_3_383e36fbe068(CTRPluginFramework::MenuEntry *entry);

// 釣り竿 (GROUP_00522)
void 釣り竿_38b4c89cfaaa(CTRPluginFramework::MenuEntry *entry);

// みにつける (GROUP_00590)
void みにつける_402141ac30a1(CTRPluginFramework::MenuEntry *entry);

// えほうまき (GROUP_00610)
void えほうまき_42732b816dea(CTRPluginFramework::MenuEntry *entry);

// 1p歩数無限 (GROUP_00611)
void Cheat_1p歩数無限_4276142b1e0f(CTRPluginFramework::MenuEntry *entry);

// カタログ注文ポケットに入れる (GROUP_00618)
void カタログ注文ポケットに入れる_43156044f3f9(CTRPluginFramework::MenuEntry *entry);

// ポケットいっぱい (GROUP_00628)
void ポケットいっぱい_43ca4bac0322(CTRPluginFramework::MenuEntry *entry);

// 何でも拾う (GROUP_00661)
void 何でも拾う_473b7a456efc(CTRPluginFramework::MenuEntry *entry);

// ランダムドロップオフ (GROUP_00664)
void ランダムドロップオフ_475d77c8f7c4(CTRPluginFramework::MenuEntry *entry);

// 置いても見えない OFF (GROUP_00678)
void 置いても見えない_OFF_490ef111fc87(CTRPluginFramework::MenuEntry *entry);

// drag drop spam (GROUP_00685)
void drag_drop_spam_49b195ce9e34(CTRPluginFramework::MenuEntry *entry);

// 丸太 (GROUP_00688)
void 丸太_49ee83c3171e(CTRPluginFramework::MenuEntry *entry);

// 竹 (GROUP_00708)
void 竹_4c0005505fea(CTRPluginFramework::MenuEntry *entry);

// 食べて見せる (GROUP_00717)
void 食べて見せる_4c79e2a9dd5d(CTRPluginFramework::MenuEntry *entry);

// 卵 出てきたアイテム持ち物に入らない OFF (GROUP_00729)
void 卵_出てきたアイテム持ち物に入らない_OFF_4d079dce0fc6(CTRPluginFramework::MenuEntry *entry);

// 所持金固定 (GROUP_00733)
void 所持金固定_4ddfad3c6170(CTRPluginFramework::MenuEntry *entry);

// 全アイテムに水やり (GROUP_00734)
void 全アイテムに水やり_4de02aecea08(CTRPluginFramework::MenuEntry *entry);

// Rock Smash (GROUP_00807)
void Rock_Smash_5520fe9859c5(CTRPluginFramework::MenuEntry *entry);

// Auto Pickup (GROUP_00821)
void Auto_Pickup_56386a77d1e0(CTRPluginFramework::MenuEntry *entry);

// 連続で置く(無限アイテムと併用) (GROUP_00828)
void 連続で置く_無限アイテムと併用_57fe5c904d7c(CTRPluginFramework::MenuEntry *entry);

// アイテム全て卵判定 OFF (GROUP_00843)
void アイテム全て卵判定_OFF_596b705e2c2e(CTRPluginFramework::MenuEntry *entry);

// 食べてアイテム変換 (GROUP_00853)
void 食べてアイテム変換_5a406db73e41(CTRPluginFramework::MenuEntry *entry);

// フルーツの木の実アイテムを変更 (GROUP_00874)
void フルーツの木の実アイテムを変更_5d1fa9f18b6a(CTRPluginFramework::MenuEntry *entry);

// アイテム指定 (GROUP_00879)
void アイテム指定_5d42424ce99a(CTRPluginFramework::MenuEntry *entry);

// 卵 普通に食べる (GROUP_00883)
void 卵_普通に食べる_5dc1d1fb8a2d(CTRPluginFramework::MenuEntry *entry);

// 傘1 (GROUP_00915)
void 傘1_60e9a22beb6a(CTRPluginFramework::MenuEntry *entry);

// 取る動作 解除 (GROUP_00946)
void 取る動作_解除_649d5d5a1045(CTRPluginFramework::MenuEntry *entry);

// 消えない穴 (GROUP_00998)
void 消えない穴_69ef6cf5d6dc(CTRPluginFramework::MenuEntry *entry);

// Hole Fill (GROUP_01001)
void Hole_Fill_6a3a4aba9514(CTRPluginFramework::MenuEntry *entry);

// どこでも穴掘れるようになる (GROUP_01012)
void どこでも穴掘れるようになる_6be4750ab6b1(CTRPluginFramework::MenuEntry *entry);

// 低木 (GROUP_01026)
void 低木_6dad4dd59415(CTRPluginFramework::MenuEntry *entry);

// 普通の∞フルーツ (GROUP_01040)
void 普通の_フルーツ_6f1acd628b6f(CTRPluginFramework::MenuEntry *entry);

// 高速ドロップ(A+R) (GROUP_01043)
void 高速ドロップ_A_R_6f775b98f3e2(CTRPluginFramework::MenuEntry *entry);

// 経過日数 (GROUP_01052)
void 経過日数_7033c5712fcb(CTRPluginFramework::MenuEntry *entry);

// 木/岩 掘り起こす (GROUP_01058)
void 木_岩_掘り起こす_70e7e5bb25b6(CTRPluginFramework::MenuEntry *entry);

// ドロップ横軸変更コード (GROUP_01087)
void ドロップ横軸変更コード_7399249a5960(CTRPluginFramework::MenuEntry *entry);

// 通常動作 (GROUP_01101)
void 通常動作_7546c9ae96f2(CTRPluginFramework::MenuEntry *entry);

// 花が持ち物から消えない(解除) (GROUP_01105)
void 花が持ち物から消えない_解除_75a0ae9671c8(CTRPluginFramework::MenuEntry *entry);

// 歩いた場所の物を消す (GROUP_01107)
void 歩いた場所の物を消す_75e2d4c19f33(CTRPluginFramework::MenuEntry *entry);

// ポケット表示中 (GROUP_01109)
void ポケット表示中_7629e5458d65(CTRPluginFramework::MenuEntry *entry);

// 石ころ (GROUP_01147)
void 石ころ_7b4e1355cc49(CTRPluginFramework::MenuEntry *entry);

// てがみをかく (GROUP_01155)
void てがみをかく_7c5354a8d044(CTRPluginFramework::MenuEntry *entry);

// アイテムを捨てる (GROUP_01156)
void アイテムを捨てる_7c5d17bbe9a1(CTRPluginFramework::MenuEntry *entry);

// 地面に埋める (GROUP_01166)
void 地面に埋める_7d6a168dd351(CTRPluginFramework::MenuEntry *entry);

// どこにでもアイテム置ける (GROUP_01178)
void どこにでもアイテム置ける_7e4193d25216(CTRPluginFramework::MenuEntry *entry);

// かざぐるま (GROUP_01189)
void かざぐるま_7f179d48f20c(CTRPluginFramework::MenuEntry *entry);

// 食べてアイテム変換 OFF (GROUP_01201)
void 食べてアイテム変換_OFF_808930fcee47(CTRPluginFramework::MenuEntry *entry);

// アイテムが持ち物から消えない(解除) (GROUP_01202)
void アイテムが持ち物から消えない_解除_80c00980b7ac(CTRPluginFramework::MenuEntry *entry);

// 歩いた時のスコア999999 (GROUP_01207)
void 歩いた時のスコア999999_812e2c5ddbc6(CTRPluginFramework::MenuEntry *entry);

// アイテム拾い方変更キー式 (GROUP_01220)
void アイテム拾い方変更キー式_8280dedadfcd(CTRPluginFramework::MenuEntry *entry);

// 拾う時変Off (GROUP_01222)
void 拾う時変Off_83014cdecc85(CTRPluginFramework::MenuEntry *entry);

// その他のアイテム (GROUP_01227)
void その他のアイテム_83567ab4b30c(CTRPluginFramework::MenuEntry *entry);

// 卵 出てきたアイテム持ち物に入らない (GROUP_01228)
void 卵_出てきたアイテム持ち物に入らない_836345a7730b(CTRPluginFramework::MenuEntry *entry);

// 竹歩き置き (GROUP_01231)
void 竹歩き置き_83ccc5d8fed8(CTRPluginFramework::MenuEntry *entry);

// 吹き出し花火 (GROUP_01239)
void 吹き出し花火_84e3b884b121(CTRPluginFramework::MenuEntry *entry);

// 回転消しOff (GROUP_01287)
void 回転消しOff_89ca3d35a3b2(CTRPluginFramework::MenuEntry *entry);

// ランダムドロップオン (GROUP_01288)
void ランダムドロップオン_89d7809f9850(CTRPluginFramework::MenuEntry *entry);

// 没メニュー (GROUP_01293)
void 没メニュー_8a451306d524(CTRPluginFramework::MenuEntry *entry);

// すてる3 (GROUP_01312)
void すてる3_8c30ac30c360(CTRPluginFramework::MenuEntry *entry);

// 食料落下数 (GROUP_01316)
void 食料落下数_8c66ff7d66b6(CTRPluginFramework::MenuEntry *entry);

// ピコピコハンマー (GROUP_01321)
void ピコピコハンマー_8cf4c301c541(CTRPluginFramework::MenuEntry *entry);

// 卵 普通に食べる OFF (GROUP_01324)
void 卵_普通に食べる_OFF_8d47e7e6b532(CTRPluginFramework::MenuEntry *entry);

// 拾う時On (GROUP_01345)
void 拾う時On_8f92ea5db46c(CTRPluginFramework::MenuEntry *entry);

// 図鑑で表示した虫をポケットに入れる (GROUP_01386)
void 図鑑で表示した虫をポケットに入れる_94563bf49525(CTRPluginFramework::MenuEntry *entry);

// 回転消し (GROUP_01400)
void 回転消し_96075ae9dd9e(CTRPluginFramework::MenuEntry *entry);

// 図鑑の生き物をポケットに入れる (GROUP_01411)
void 図鑑の生き物をポケットに入れる_97d54209b704(CTRPluginFramework::MenuEntry *entry);

// 何でもクローバーで拾う (GROUP_01444)
void 何でもクローバーで拾う_9af3cbb23f4a(CTRPluginFramework::MenuEntry *entry);

// クローバーで拾った時 (GROUP_01469)
void クローバーで拾った時_9dc1fb778261(CTRPluginFramework::MenuEntry *entry);

// へやにかざる (GROUP_01471)
void へやにかざる_9de53e81633d(CTRPluginFramework::MenuEntry *entry);

// マイデザセット2 (GROUP_01546)
void マイデザセット2_a5edbdbc262d(CTRPluginFramework::MenuEntry *entry);

// 機能変更 (GROUP_01549)
void 機能変更_a632b4427712(CTRPluginFramework::MenuEntry *entry);

// お金の木 (GROUP_01554)
void お金の木_a686702aef11(CTRPluginFramework::MenuEntry *entry);

// 全アイテム削除[ZR+↑] (GROUP_01556)
void 全アイテム削除_ZR_a6ba3603e8e5(CTRPluginFramework::MenuEntry *entry);

// マイデザセット4 (GROUP_01563)
void マイデザセット4_a6ff62dd6abc(CTRPluginFramework::MenuEntry *entry);

// 恵方巻き・アイス (GROUP_01570)
void 恵方巻き_アイス_a7e074ad4166(CTRPluginFramework::MenuEntry *entry);

// 相手のアイテム (GROUP_01575)
void 相手のアイテム_a875adf5d4a6(CTRPluginFramework::MenuEntry *entry);

// drag dorp spam off (GROUP_01593)
void drag_dorp_spam_off_aa6019531731(CTRPluginFramework::MenuEntry *entry);

// Tour Shovel Disable (GROUP_01609)
void Tour_Shovel_Disable_ab692caa4a2e(CTRPluginFramework::MenuEntry *entry);

// Rotate (GROUP_01610)
void Rotate_ab74b6c2ec53(CTRPluginFramework::MenuEntry *entry);

// ベル歩き置き (GROUP_01612)
void ベル歩き置き_abe5818f3ca5(CTRPluginFramework::MenuEntry *entry);

// Aを押してる間自動で拾いまくる (GROUP_01627)
void Aを押してる間自動で拾いまくる_ad397194a76c(CTRPluginFramework::MenuEntry *entry);

// 雑草 (GROUP_01661)
void 雑草_b30f82c304f7(CTRPluginFramework::MenuEntry *entry);

// 棒 (GROUP_01673)
void 棒_b44b8767dc4f(CTRPluginFramework::MenuEntry *entry);

// たべる (GROUP_01679)
void たべる_b4bd03ced6e3(CTRPluginFramework::MenuEntry *entry);

// 拾う (GROUP_01708)
void 拾う_b7d6c882cf2e(CTRPluginFramework::MenuEntry *entry);

// ドロップMOD (GROUP_01716)
void ドロップMOD_b8dbf8b27944(CTRPluginFramework::MenuEntry *entry);

// 没アイテムをポケットに表示する (GROUP_01732)
void 没アイテムをポケットに表示する_ba56482bd842(CTRPluginFramework::MenuEntry *entry);

// 金鉱石 (GROUP_01745)
void 金鉱石_bbbeb39009fa(CTRPluginFramework::MenuEntry *entry);

// スパークリングソーダー (GROUP_01756)
void スパークリングソーダー_bc8f6a0a5d1a(CTRPluginFramework::MenuEntry *entry);

// 2p歩数無限 (GROUP_01778)
void Cheat_2p歩数無限_bf904b43331a(CTRPluginFramework::MenuEntry *entry);

// 銀鉱石 (GROUP_01785)
void 銀鉱石_c0331bf3a1a4(CTRPluginFramework::MenuEntry *entry);

// お金 (GROUP_01793)
void お金_c10107609fd6(CTRPluginFramework::MenuEntry *entry);

// 掘り出す (GROUP_01796)
void 掘り出す_c158b3617d46(CTRPluginFramework::MenuEntry *entry);

// マリンスーツセット (GROUP_01799)
void マリンスーツセット_c18002adff3e(CTRPluginFramework::MenuEntry *entry);

// 置いたもの変更 (GROUP_01827)
void 置いたもの変更_c4830a08d4a4(CTRPluginFramework::MenuEntry *entry);

// 食料所持数 (GROUP_01832)
void 食料所持数_c5591cf110c7(CTRPluginFramework::MenuEntry *entry);

// 金の道具 (GROUP_01859)
void 金の道具_c803110b753e(CTRPluginFramework::MenuEntry *entry);

// host drop (GROUP_01869)
void host_drop_c8f5cea3fd57(CTRPluginFramework::MenuEntry *entry);

// コーヒー・サイダー (GROUP_01874)
void コーヒー_サイダー_c9b30c08935d(CTRPluginFramework::MenuEntry *entry);

// マイデザセット3 (GROUP_01877)
void マイデザセット3_c9dd46ee27bf(CTRPluginFramework::MenuEntry *entry);

// マイデザセット1 (GROUP_01881)
void マイデザセット1_caac2edddc90(CTRPluginFramework::MenuEntry *entry);

// へやにかざる、カベにかける (GROUP_01889)
void へやにかざる_カベにかける_cb4e30230d1d(CTRPluginFramework::MenuEntry *entry);

// 船の旗 (GROUP_01900)
void 船の旗_cc7f9607bbcf(CTRPluginFramework::MenuEntry *entry);

// 手紙のプレゼント変更 (GROUP_01904)
void 手紙のプレゼント変更_ce165e2017b0(CTRPluginFramework::MenuEntry *entry);

// Nop (GROUP_01909)
void Nop_ceb2f26d34f3(CTRPluginFramework::MenuEntry *entry);

// 糸 (GROUP_01982)
void 糸_d5f1569c394f(CTRPluginFramework::MenuEntry *entry);

// アイテムをスライドで置ける (GROUP_01992)
void アイテムをスライドで置ける_d72e9e86f9f2(CTRPluginFramework::MenuEntry *entry);

// キャンピングカーの注文ポケットに入れる (GROUP_02012)
void キャンピングカーの注文ポケットに入れる_d96203b8e30b(CTRPluginFramework::MenuEntry *entry);

// TreeShake (GROUP_02032)
void TreeShake_db7651c4ca9f(CTRPluginFramework::MenuEntry *entry);

// 鉱石セット (GROUP_02036)
void 鉱石セット_dbc884fef21e(CTRPluginFramework::MenuEntry *entry);

// アイテム置ける範囲を広くする(5×5) (GROUP_02066)
void アイテム置ける範囲を広くする_5_5_ddfaea3d6219(CTRPluginFramework::MenuEntry *entry);

// スズラン (GROUP_02093)
void スズラン_e0c381f9eca3(CTRPluginFramework::MenuEntry *entry);

// 落とし穴無効化オフ (GROUP_02100)
void 落とし穴無効化オフ_e200dcc4220b(CTRPluginFramework::MenuEntry *entry);

// 見せびらかす1 (GROUP_02107)
void 見せびらかす1_e3371d743740(CTRPluginFramework::MenuEntry *entry);

// 青バラ (GROUP_02108)
void 青バラ_e3490d82f240(CTRPluginFramework::MenuEntry *entry);

// 拾った没アイテムが持ち物欄に入る (GROUP_02124)
void 拾った没アイテムが持ち物欄に入る_e4e40fccd838(CTRPluginFramework::MenuEntry *entry);

// 拾う途中 (GROUP_02125)
void 拾う途中_e4ebbe8dab90(CTRPluginFramework::MenuEntry *entry);

// すてる (GROUP_02128)
void すてる_e52774df81a9(CTRPluginFramework::MenuEntry *entry);

// 残り日数 (GROUP_02131)
void 残り日数_e549599c191a(CTRPluginFramework::MenuEntry *entry);

// 道具しまえない (GROUP_02133)
void 道具しまえない_e583da61976b(CTRPluginFramework::MenuEntry *entry);

// 見せびらかす2 (GROUP_02137)
void 見せびらかす2_e5a41cf7ff3e(CTRPluginFramework::MenuEntry *entry);

// 斧 (GROUP_02164)
void 斧_e78a31748af9(CTRPluginFramework::MenuEntry *entry);

// おいしい∞フルーツ (GROUP_02180)
void おいしい_フルーツ_e942b7ae470d(CTRPluginFramework::MenuEntry *entry);

// アイテムが持ち物から消えない (GROUP_02186)
void アイテムが持ち物から消えない_e9fe6aeb5b69(CTRPluginFramework::MenuEntry *entry);

// オンライン drag drop spam off (GROUP_02190)
void オンライン_drag_drop_spam_off_ea5295a9552f(CTRPluginFramework::MenuEntry *entry);

// 食べる時くちゃくちゃしない (GROUP_02194)
void 食べる時くちゃくちゃしない_eac67b7e3a83(CTRPluginFramework::MenuEntry *entry);

// ステージ開放率 (GROUP_02211)
void ステージ開放率_ecaecdb6f671(CTRPluginFramework::MenuEntry *entry);

// すてる2 (GROUP_02213)
void すてる2_ed15d7a702bc(CTRPluginFramework::MenuEntry *entry);

// リサイクルショップアイテム変更 (GROUP_02218)
void リサイクルショップアイテム変更_ee1bbda28217(CTRPluginFramework::MenuEntry *entry);

// オンライン drag drop spam (GROUP_02219)
void オンライン_drag_drop_spam_ee2db8d7f994(CTRPluginFramework::MenuEntry *entry);

// 歩いた所のアイテム変更 (GROUP_02225)
void 歩いた所のアイテム変更_eebd2566fefd(CTRPluginFramework::MenuEntry *entry);

// おいしい (GROUP_02233)
void おいしい_efc3982973a7(CTRPluginFramework::MenuEntry *entry);

// Dig (GROUP_02237)
void Dig_f0255402384a(CTRPluginFramework::MenuEntry *entry);

// 道具変更動作 (GROUP_02252)
void 道具変更動作_f165c0f085c3(CTRPluginFramework::MenuEntry *entry);

// 卵 大当たりの券 変更 (GROUP_02256)
void 卵_大当たりの券_変更_f2028839b2a3(CTRPluginFramework::MenuEntry *entry);

// まめ (GROUP_02296)
void まめ_f5b1f1656d58(CTRPluginFramework::MenuEntry *entry);

// おき花火の燃えカスからお金 (GROUP_02304)
void おき花火の燃えカスからお金_f68f471c9535(CTRPluginFramework::MenuEntry *entry);

// 花火2 (GROUP_02308)
void 花火2_f6e6d7644298(CTRPluginFramework::MenuEntry *entry);

// Paste (GROUP_02310)
void Paste_f724c05d8105(CTRPluginFramework::MenuEntry *entry);

// 食べておいしい (GROUP_02318)
void 食べておいしい_f7a7ca83f1f5(CTRPluginFramework::MenuEntry *entry);

// リンゴゲージ (GROUP_02331)
void リンゴゲージ_f8e5c1d18bdc(CTRPluginFramework::MenuEntry *entry);

// 卵 当たりの券 変更 (GROUP_02336)
void 卵_当たりの券_変更_f97f6540e24f(CTRPluginFramework::MenuEntry *entry);

// 村のアイテム全部除去 (GROUP_02339)
void 村のアイテム全部除去_f9c59c4f751d(CTRPluginFramework::MenuEntry *entry);

// コーヒー (GROUP_02345)
void コーヒー_fa8470260da7(CTRPluginFramework::MenuEntry *entry);

// 3p歩数無限 (GROUP_02357)
void Cheat_3p歩数無限_fbefdc409e30(CTRPluginFramework::MenuEntry *entry);

// スコップ掘る (GROUP_02385)
void スコップ掘る_fe8edc28ffb7(CTRPluginFramework::MenuEntry *entry);

// 卵 アメ 変更 (GROUP_02386)
void 卵_アメ_変更_feb02c71088a(CTRPluginFramework::MenuEntry *entry);

// 飲み物 (GROUP_02391)
void 飲み物_ff49ce3d3766(CTRPluginFramework::MenuEntry *entry);

} }
