// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace PlayerMovement {

// プレイヤー4に移動 (GROUP_00038)
void プレイヤー4に移動_03e163a24e2a(CTRPluginFramework::MenuEntry *entry);

// 花の上を走っても散らない (GROUP_00070)
void 花の上を走っても散らない_06dcb4a60578(CTRPluginFramework::MenuEntry *entry);

// プレイヤー位置保存 (GROUP_00127)
void プレイヤー位置保存_0dd2e8e6eced(CTRPluginFramework::MenuEntry *entry);

// アクション連打 ASM解除 (GROUP_00153)
void アクション連打_ASM解除_1191dede34e8(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(右) (GROUP_00179)
void プレイヤー1_右_1415d75a82cf(CTRPluginFramework::MenuEntry *entry);

// スピードハック (GROUP_00194)
void スピードハック_1579b5701ada(CTRPluginFramework::MenuEntry *entry);

// 非プレイヤー乗っ取り (GROUP_00259)
void 非プレイヤー乗っ取り_1d2e5775afc8(CTRPluginFramework::MenuEntry *entry);

// くらげに刺される (GROUP_00282)
void くらげに刺される_2006727d9bd1(CTRPluginFramework::MenuEntry *entry);

// 透明化解除 (GROUP_00336)
void 透明化解除_256e11f20e64(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(2階) (GROUP_00349)
void プレイヤー1_2階_26d3b675c3f0(CTRPluginFramework::MenuEntry *entry);

// 足を消すモーション (GROUP_00365)
void 足を消すモーション_282f8b5904fc(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート3P(外) (GROUP_00386)
void プレイヤーテレポート3P_外_2a2e5f2ceb70(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(居間) (GROUP_00429)
void プレイヤー4_居間_2ede524447be(CTRPluginFramework::MenuEntry *entry);

// かっぱを自分の所へ移動(ZR+↑→↓) (GROUP_00504)
void かっぱを自分の所へ移動_ZR_377f701571b8(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(地下) (GROUP_00509)
void プレイヤー3_地下_3810b3999187(CTRPluginFramework::MenuEntry *entry);

// 強制的に次の動作に移れる (GROUP_00521)
void 強制的に次の動作に移れる_388006159468(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート2P(外) (GROUP_00561)
void プレイヤーテレポート2P_外_3cbc8ed614ce(CTRPluginFramework::MenuEntry *entry);

// アクション連打 ASM (GROUP_00565)
void アクション連打_ASM_3d23d208cf9b(CTRPluginFramework::MenuEntry *entry);

// 透明化 (GROUP_00585)
void 透明化_3f979529fc49(CTRPluginFramework::MenuEntry *entry);

// かっぱを2Pの所へ移動(ZR+↑→↓) (GROUP_00599)
void かっぱを2Pの所へ移動_ZR_411665062a9a(CTRPluginFramework::MenuEntry *entry);

// プレイヤーが黒く点滅する (GROUP_00662)
void プレイヤーが黒く点滅する_4746ef2e549a(CTRPluginFramework::MenuEntry *entry);

// 女歩き (GROUP_00681)
void 女歩き_4982acd5607b(CTRPluginFramework::MenuEntry *entry);

// 座標移動2(+A) (GROUP_00704)
void 座標移動2_A_4b8fc8fbe932(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(奥) (GROUP_00725)
void プレイヤー3_奥_4cbdf473283e(CTRPluginFramework::MenuEntry *entry);

// 歩いてくる (GROUP_00808)
void 歩いてくる_5525ef81279b(CTRPluginFramework::MenuEntry *entry);

// 食べる OFF (GROUP_00811)
void 食べる_OFF_55788dd40cff(CTRPluginFramework::MenuEntry *entry);

// 1Pの見た目コピー (GROUP_00825)
void Cheat_1Pの見た目コピー_5784579876f9(CTRPluginFramework::MenuEntry *entry);

// ami speed (GROUP_00896)
void ami_speed_5eed6351def6(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(奥) (GROUP_00901)
void プレイヤー1_奥_5f437850129e(CTRPluginFramework::MenuEntry *entry);

// 座って寝る (GROUP_00904)
void 座って寝る_5fdf72676ed4(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(地下) (GROUP_00932)
void プレイヤー4_地下_62d11d3bbd3b(CTRPluginFramework::MenuEntry *entry);

// 急ブレーキ (GROUP_00933)
void 急ブレーキ_62fdabd628cc(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(奥) (GROUP_00954)
void プレイヤー4_奥_65cf99b1fcbf(CTRPluginFramework::MenuEntry *entry);

// スローモーションアニメ (GROUP_00971)
void スローモーションアニメ_6737b42d9a40(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(右) (GROUP_00986)
void プレイヤー2_右_68b19911d2a7(CTRPluginFramework::MenuEntry *entry);

// エリア移動時の自動歩行 (GROUP_00987)
void エリア移動時の自動歩行_68c78f40b374(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2に移動 (GROUP_00997)
void プレイヤー2に移動_699edf6ff370(CTRPluginFramework::MenuEntry *entry);

// かっぱを4Pの所へ移動(ZR+↑→↓) (GROUP_01005)
void かっぱを4Pの所へ移動_ZR_6aa788035393(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1に移動 (GROUP_01009)
void プレイヤー1に移動_6b14c4873f74(CTRPluginFramework::MenuEntry *entry);

// プレスプレイヤー (GROUP_01028)
void プレスプレイヤー_6e087659dec8(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(地下) (GROUP_01059)
void プレイヤー1_地下_7103f9a46bf4(CTRPluginFramework::MenuEntry *entry);

// クク座標移動(Cスティック) (GROUP_01079)
void クク座標移動_Cスティック_730b84d3c0d7(CTRPluginFramework::MenuEntry *entry);

// モヤモヤ (GROUP_01080)
void モヤモヤ_730db7fdfaa2(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(左) (GROUP_01081)
void プレイヤー4_左_73327f3f4261(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(左) (GROUP_01126)
void プレイヤー1_左_78e10907ff54(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(2階) (GROUP_01133)
void プレイヤー3_2階_795d9099719c(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(地下) (GROUP_01157)
void プレイヤー2_地下_7c716c587f8d(CTRPluginFramework::MenuEntry *entry);

// 歩きながらリアクション (GROUP_01173)
void 歩きながらリアクション_7de08e8941f6(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(2階) (GROUP_01223)
void プレイヤー2_2階_830849faeb4d(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート4P(外) (GROUP_01236)
void プレイヤーテレポート4P_外_84cf4e20ba44(CTRPluginFramework::MenuEntry *entry);

// 座標移動1の向き指定 (GROUP_01241)
void 座標移動1の向き指定_851012ed288e(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(2階) (GROUP_01244)
void プレイヤー4_2階_856f591f7340(CTRPluginFramework::MenuEntry *entry);

// ストーカー室外版 (GROUP_01269)
void ストーカー室外版_8826fa16182e(CTRPluginFramework::MenuEntry *entry);

// 歩いた場所のエフェクト変更 (GROUP_01270)
void 歩いた場所のエフェクト変更_882eb96742ef(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3に移動 (GROUP_01290)
void プレイヤー3に移動_8a12cbdc05ae(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(右) (GROUP_01314)
void プレイヤー3_右_8c395f14fb91(CTRPluginFramework::MenuEntry *entry);

// プレイヤー1(居間) (GROUP_01319)
void プレイヤー1_居間_8cb00d1c8183(CTRPluginFramework::MenuEntry *entry);

// 泳げない (GROUP_01320)
void 泳げない_8cbdc8230f09(CTRPluginFramework::MenuEntry *entry);

// プレイヤー4(右) (GROUP_01322)
void プレイヤー4_右_8d0bf9c69832(CTRPluginFramework::MenuEntry *entry);

// 置き花火 (GROUP_01325)
void 置き花火_8d58bd2424c0(CTRPluginFramework::MenuEntry *entry);

// 住人歩くスピード (GROUP_01361)
void 住人歩くスピード_914842623534(CTRPluginFramework::MenuEntry *entry);

// 海の上を歩ける (GROUP_01362)
void 海の上を歩ける_916281fc5807(CTRPluginFramework::MenuEntry *entry);

// 穴に落ちない オフ (GROUP_01395)
void 穴に落ちない_オフ_9565eef17400(CTRPluginFramework::MenuEntry *entry);

// プレイヤーテレポート1P(外) (GROUP_01426)
void プレイヤーテレポート1P_外_98dba00c2e74(CTRPluginFramework::MenuEntry *entry);

// 倒れながら歩く (GROUP_01495)
void 倒れながら歩く_a04805e541d5(CTRPluginFramework::MenuEntry *entry);

// 座標移動1(+A) (GROUP_01514)
void 座標移動1_A_a256f51a65ee(CTRPluginFramework::MenuEntry *entry);

// ドアを開ける (GROUP_01536)
void ドアを開ける_a452acb4d40c(CTRPluginFramework::MenuEntry *entry);

// ネタ強制終了/固定 [/] (GROUP_01538)
void ネタ強制終了_固定_a486d6688a91(CTRPluginFramework::MenuEntry *entry);

// ゲームスピード (GROUP_01541)
void ゲームスピード_a4bbab4aa6f0(CTRPluginFramework::MenuEntry *entry);

// 船に移動 (GROUP_01576)
void 船に移動_a882afa2c94f(CTRPluginFramework::MenuEntry *entry);

// 持ちながら泳ぐ (GROUP_01591)
void 持ちながら泳ぐ_aa546e9d94db(CTRPluginFramework::MenuEntry *entry);

// 駅員座標移動 (GROUP_01608)
void 駅員座標移動_ab451765363a(CTRPluginFramework::MenuEntry *entry);

// 手を広げる (GROUP_01619)
void 手を広げる_aca43bf464b8(CTRPluginFramework::MenuEntry *entry);

// 首が180度回転する (GROUP_01659)
void 首が180度回転する_b25bbd867ae0(CTRPluginFramework::MenuEntry *entry);

// モーションリセット R (GROUP_01691)
void モーションリセット_R_b63ab80cc319(CTRPluginFramework::MenuEntry *entry);

// どこでも泳ぐASM (GROUP_01693)
void どこでも泳ぐASM_b63b7202c4c2(CTRPluginFramework::MenuEntry *entry);

// クーコ座標移動(Cスティック) (GROUP_01731)
void クーコ座標移動_Cスティック_ba3c0b7f5bb5(CTRPluginFramework::MenuEntry *entry);

// 村の配置物を透明化 (GROUP_01751)
void 村の配置物を透明化_bc2aeac38ee3(CTRPluginFramework::MenuEntry *entry);

// 首が折れる (GROUP_01757)
void 首が折れる_bc969f5f800f(CTRPluginFramework::MenuEntry *entry);

// 座標移動3(スティック) (GROUP_01772)
void 座標移動3_スティック_bf1263695647(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(居間) (GROUP_01790)
void プレイヤー2_居間_c0e104ec4e47(CTRPluginFramework::MenuEntry *entry);

// ムーンジャンプ (GROUP_01800)
void ムーンジャンプ_c1839cb31e8f(CTRPluginFramework::MenuEntry *entry);

// プレイヤーの歩くスピード (GROUP_01813)
void プレイヤーの歩くスピード_c2c9476305f6(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(奥) (GROUP_01823)
void プレイヤー2_奥_c412ca54fa5c(CTRPluginFramework::MenuEntry *entry);

// こける (GROUP_01825)
void こける_c438d4000d4f(CTRPluginFramework::MenuEntry *entry);

// プレイヤーが黒くなる (GROUP_01879)
void プレイヤーが黒くなる_ca69431cf52b(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(左) (GROUP_01931)
void プレイヤー3_左_d11811f3d05a(CTRPluginFramework::MenuEntry *entry);

// かっぱを3Pの所へ移動(ZR+↑→↓) (GROUP_01996)
void かっぱを3Pの所へ移動_ZR_d79124493aea(CTRPluginFramework::MenuEntry *entry);

// プレイヤー2(左) (GROUP_02002)
void プレイヤー2_左_d82cfe366390(CTRPluginFramework::MenuEntry *entry);

// 首が上向きになる (GROUP_02091)
void 首が上向きになる_e080c387143a(CTRPluginFramework::MenuEntry *entry);

// 男走り (GROUP_02099)
void 男走り_e1f572bc9f56(CTRPluginFramework::MenuEntry *entry);

// ゲーム速度上昇 (GROUP_02126)
void ゲーム速度上昇_e50c8c6a55a1(CTRPluginFramework::MenuEntry *entry);

// 男歩き (GROUP_02140)
void 男歩き_e5d8eac2e087(CTRPluginFramework::MenuEntry *entry);

// 顔消滅 (GROUP_02148)
void 顔消滅_e647b054afd2(CTRPluginFramework::MenuEntry *entry);

// 走ってくる (GROUP_02158)
void 走ってくる_e70423eb1de8(CTRPluginFramework::MenuEntry *entry);

// 女走り (GROUP_02199)
void 女走り_eb91ea0e1f40(CTRPluginFramework::MenuEntry *entry);

// 自分叩くピコピコ (GROUP_02201)
void 自分叩くピコピコ_ebdcfd4e957f(CTRPluginFramework::MenuEntry *entry);

// プレイヤー3(居間) (GROUP_02222)
void プレイヤー3_居間_ee6470ab6d3a(CTRPluginFramework::MenuEntry *entry);

// ババア座標移動(Cスティック) (GROUP_02243)
void ババア座標移動_Cスティック_f073af81a4eb(CTRPluginFramework::MenuEntry *entry);

// 気絶(元に戻る) (GROUP_02269)
void 気絶_元に戻る_f309c4e3a906(CTRPluginFramework::MenuEntry *entry);

// 泳ぐ [++/] (GROUP_02343)
void 泳ぐ_fa22af137356(CTRPluginFramework::MenuEntry *entry);

// 浮いて寝る (GROUP_02361)
void 浮いて寝る_fc1ff08479a0(CTRPluginFramework::MenuEntry *entry);

// 木をゆすると岩のモーション (GROUP_02367)
void 木をゆすると岩のモーション_fc92991144e6(CTRPluginFramework::MenuEntry *entry);

// 岩動作 (GROUP_02388)
void 岩動作_fee79c433e4a(CTRPluginFramework::MenuEntry *entry);

} }
