// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace Review {

// ドロップ解除 (GROUP_00001)
void ドロップ解除_001daf60af6e(CTRPluginFramework::MenuEntry *entry);

// スタイリングする (GROUP_00002)
void スタイリングする_002a9a3aadbf(CTRPluginFramework::MenuEntry *entry);

// 前回転でドロップ (GROUP_00005)
void 前回転でドロップ_00747b80f64f(CTRPluginFramework::MenuEntry *entry);

// 12 (GROUP_00006)
void Cheat_12_0075979443d1(CTRPluginFramework::MenuEntry *entry);

// クラッカー (GROUP_00008)
void クラッカー_00e55e2a97c9(CTRPluginFramework::MenuEntry *entry);

// どこでも家具変更可能(オンライン対応) (GROUP_00014)
void どこでも家具変更可能_オンライン対応_019402770dfe(CTRPluginFramework::MenuEntry *entry);

// 5×5マスに変更on (GROUP_00019)
void Cheat_5_5マスに変更on_0218e6acbf2d(CTRPluginFramework::MenuEntry *entry);

// クク 2 (GROUP_00020)
void クク_2_021c77565d9b(CTRPluginFramework::MenuEntry *entry);

// 黄緑 (GROUP_00024)
void 黄緑_0261af7ec3b4(CTRPluginFramework::MenuEntry *entry);

// フレッシュで (GROUP_00025)
void フレッシュで_02665a5f3b58(CTRPluginFramework::MenuEntry *entry);

// 22 (GROUP_00027)
void Cheat_22_029cb7e657da(CTRPluginFramework::MenuEntry *entry);

// 服屋 (GROUP_00029)
void 服屋_02b6b97dabb2(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00032)
void p_0380149f2868(CTRPluginFramework::MenuEntry *entry);

// 連続流れ星 (GROUP_00040)
void 連続流れ星_03ffab62450d(CTRPluginFramework::MenuEntry *entry);

// 大富豪 (GROUP_00044)
void 大富豪_047c9bdc0675(CTRPluginFramework::MenuEntry *entry);

// ばばあスネーク (GROUP_00045)
void ばばあスネーク_049b24670f6f(CTRPluginFramework::MenuEntry *entry);

// NPC 食べる (GROUP_00048)
void NPC_食べる_04f22f620202(CTRPluginFramework::MenuEntry *entry);

// 濃い緑 (GROUP_00049)
void 濃い緑_04f8d2969959(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_00051)
void 茶色_0531c689a7a8(CTRPluginFramework::MenuEntry *entry);

// 3-3の地形変更 (GROUP_00055)
void Cheat_3_3の地形変更_055c4e4c0f0c(CTRPluginFramework::MenuEntry *entry);

// 流れ星 (GROUP_00056)
void 流れ星_057ae89a9efd(CTRPluginFramework::MenuEntry *entry);

// 1p (GROUP_00058)
void Cheat_1p_059ae7925128(CTRPluginFramework::MenuEntry *entry);

// 29 (GROUP_00063)
void Cheat_29_060b63efc01d(CTRPluginFramework::MenuEntry *entry);

// 10 (GROUP_00071)
void Cheat_10_06e2dc20e32a(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_00074)
void 有効_070363d1e532(CTRPluginFramework::MenuEntry *entry);

// chat (GROUP_00076)
void chat_0735ade4126d(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00077)
void 自分に_0739ce857089(CTRPluginFramework::MenuEntry *entry);

// bba 2 (GROUP_00080)
void bba_2_07c94aadd0ee(CTRPluginFramework::MenuEntry *entry);

// 3-1の地形変更 (GROUP_00082)
void Cheat_3_1の地形変更_07e70598ea65(CTRPluginFramework::MenuEntry *entry);

// メッセージ速度 (GROUP_00084)
void メッセージ速度_082a3f4d9bed(CTRPluginFramework::MenuEntry *entry);

// 4 (GROUP_00091)
void Cheat_4_08df8c2d33e8(CTRPluginFramework::MenuEntry *entry);

// 金色 (GROUP_00094)
void 金色_09188183b903(CTRPluginFramework::MenuEntry *entry);

// 30 (GROUP_00099)
void Cheat_30_09bfb555e449(CTRPluginFramework::MenuEntry *entry);

// アッシュブラウン (GROUP_00103)
void アッシュブラウン_0a40ac1ac9a4(CTRPluginFramework::MenuEntry *entry);

// ハニワのレンタルアイテム変更 (GROUP_00104)
void ハニワのレンタルアイテム変更_0a4772f99d4e(CTRPluginFramework::MenuEntry *entry);

// 掘ってドロップ (GROUP_00105)
void 掘ってドロップ_0a92f9ce2c1a(CTRPluginFramework::MenuEntry *entry);

// 2 (GROUP_00106)
void Cheat_2_0aaef3f0bd35(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00108)
void 自分に_0ad5bb0482c9(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00109)
void 座標移動_0b163466aef0(CTRPluginFramework::MenuEntry *entry);

// 空気椅子 (GROUP_00114)
void 空気椅子_0bbe44dd785b(CTRPluginFramework::MenuEntry *entry);

// カフェ (GROUP_00115)
void カフェ_0bd7c8edd3d4(CTRPluginFramework::MenuEntry *entry);

// 27 (GROUP_00118)
void Cheat_27_0c19b1a7ef99(CTRPluginFramework::MenuEntry *entry);

// ハチ (GROUP_00119)
void ハチ_0c225ede9113(CTRPluginFramework::MenuEntry *entry);

// 穴に落ちない (GROUP_00122)
void 穴に落ちない_0c6551875cef(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00123)
void p_0c89d375a27c(CTRPluginFramework::MenuEntry *entry);

// 3-4の地形変更 (GROUP_00124)
void Cheat_3_4の地形変更_0cca37597834(CTRPluginFramework::MenuEntry *entry);

// 画面が青 (GROUP_00125)
void 画面が青_0d6c02413411(CTRPluginFramework::MenuEntry *entry);

// 3P (GROUP_00128)
void Cheat_3P_0de1e39d7b38(CTRPluginFramework::MenuEntry *entry);

// NPC チカチカ (GROUP_00129)
void NPC_チカチカ_0e1a290d84dd(CTRPluginFramework::MenuEntry *entry);

// 座り寝 (GROUP_00130)
void 座り寝_0e871cc73653(CTRPluginFramework::MenuEntry *entry);

// よろける (GROUP_00131)
void よろける_0e8dfd41b8d5(CTRPluginFramework::MenuEntry *entry);

// 4P (GROUP_00135)
void Cheat_4P_0f4cce1a3c2d(CTRPluginFramework::MenuEntry *entry);

// bba 2 (GROUP_00137)
void bba_2_0f64e12ed37f(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00139)
void p_0f77c04372db(CTRPluginFramework::MenuEntry *entry);

// sopaca (GROUP_00140)
void sopaca_0f89bb7643aa(CTRPluginFramework::MenuEntry *entry);

// 王冠 (GROUP_00141)
void 王冠_0fbf45d4e165(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00142)
void p_0fe27f6c4c05(CTRPluginFramework::MenuEntry *entry);

// 動作乗っ取りP4 (GROUP_00144)
void 動作乗っ取りP4_10437d6d78fb(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00145)
void p_1067fab0e4a5(CTRPluginFramework::MenuEntry *entry);

// 揺らしてドロップ (GROUP_00146)
void 揺らしてドロップ_106f047ab5f8(CTRPluginFramework::MenuEntry *entry);

// 2-2の地形変更 (GROUP_00150)
void Cheat_2_2の地形変更_1137d1c797ee(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00151)
void p_113d1cd478ab(CTRPluginFramework::MenuEntry *entry);

// 食べる (GROUP_00156)
void 食べる_11c43379c72c(CTRPluginFramework::MenuEntry *entry);

// オン (GROUP_00159)
void オン_1201f0c119d7(CTRPluginFramework::MenuEntry *entry);

// 海から出る (GROUP_00161)
void 海から出る_126892f4e84a(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00166)
void 自分に_132799db83f4(CTRPluginFramework::MenuEntry *entry);

// 4-1の地形変更 (GROUP_00167)
void Cheat_4_1の地形変更_1341aa0d9b78(CTRPluginFramework::MenuEntry *entry);

// 根性で乗り越える (GROUP_00169)
void 根性で乗り越える_13555f53f482(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00170)
void 座標移動_1360e556beea(CTRPluginFramework::MenuEntry *entry);

// 海から出る (GROUP_00175)
void 海から出る_13d8707cf92c(CTRPluginFramework::MenuEntry *entry);

// 明るい茶色 (GROUP_00180)
void 明るい茶色_1431f8a809db(CTRPluginFramework::MenuEntry *entry);

// ジョウロ (GROUP_00181)
void ジョウロ_148a6cbd515a(CTRPluginFramework::MenuEntry *entry);

// 空気椅子 (GROUP_00183)
void 空気椅子_1492d8f8780b(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00188)
void 自分に_151d1bfb8809(CTRPluginFramework::MenuEntry *entry);

// デパート1階 (GROUP_00189)
void デパート1階_152e65c5470d(CTRPluginFramework::MenuEntry *entry);

// 誰も寄せつけたくない (GROUP_00199)
void 誰も寄せつけたくない_15e7035b30f2(CTRPluginFramework::MenuEntry *entry);

// 役場 (GROUP_00202)
void 役場_1645a6068944(CTRPluginFramework::MenuEntry *entry);

// 2-2の地形変更 (GROUP_00203)
void Cheat_2_2の地形変更_164ac1a80eb7(CTRPluginFramework::MenuEntry *entry);

// クーコ 3 (GROUP_00207)
void クーコ_3_16dbd4ad6609(CTRPluginFramework::MenuEntry *entry);

// 豆 (GROUP_00208)
void 豆_16f349ba955a(CTRPluginFramework::MenuEntry *entry);

// 13 (GROUP_00209)
void Cheat_13_170051ff4927(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00210)
void p_17185f512ac9(CTRPluginFramework::MenuEntry *entry);

// 押されない (GROUP_00213)
void 押されない_1784d1a611f2(CTRPluginFramework::MenuEntry *entry);

// 壁抜け (GROUP_00215)
void 壁抜け_17dcad0d6340(CTRPluginFramework::MenuEntry *entry);

// クラゲに刺される (GROUP_00216)
void クラゲに刺される_17e270c37364(CTRPluginFramework::MenuEntry *entry);

// NPC 着替える (エフェクトなし) (GROUP_00218)
void NPC_着替える_エフェクトなし_1802cbbf7aff(CTRPluginFramework::MenuEntry *entry);

// ENG (GROUP_00219)
void ENG_1816b98408af(CTRPluginFramework::MenuEntry *entry);

// けだるいゆるさ (GROUP_00224)
void けだるいゆるさ_18b36b6ae0a2(CTRPluginFramework::MenuEntry *entry);

// 1-2の地形変更 (GROUP_00227)
void Cheat_1_2の地形変更_194412347a2d(CTRPluginFramework::MenuEntry *entry);

// ハンマー動作 (GROUP_00228)
void ハンマー動作_194d4aadeebd(CTRPluginFramework::MenuEntry *entry);

// マイデザを貼る1P (GROUP_00236)
void マイデザを貼る1P_1a706389187a(CTRPluginFramework::MenuEntry *entry);

// トンネル (GROUP_00241)
void トンネル_1ac22c9dbcf5(CTRPluginFramework::MenuEntry *entry);

// アッシュブラウン (GROUP_00242)
void アッシュブラウン_1acebc922f78(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_00244)
void 茶色_1b1e209218c6(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00251)
void 座標移動_1ba64d426c3a(CTRPluginFramework::MenuEntry *entry);

// 1回で木切れる (GROUP_00252)
void Cheat_1回で木切れる_1be6d798626a(CTRPluginFramework::MenuEntry *entry);

// 占いの館 (GROUP_00253)
void 占いの館_1bf08da2c11c(CTRPluginFramework::MenuEntry *entry);

// motimono (GROUP_00256)
void motimono_1c4148dc70fd(CTRPluginFramework::MenuEntry *entry);

// ふるさとチケット (GROUP_00268)
void ふるさとチケット_1e97c0d42551(CTRPluginFramework::MenuEntry *entry);

// P1判定(ホスト)ON (GROUP_00269)
void P1判定_ホスト_ON_1eacfd9e7c0c(CTRPluginFramework::MenuEntry *entry);

// スタイリングする (GROUP_00271)
void スタイリングする_1f02543b4421(CTRPluginFramework::MenuEntry *entry);

// *ひなたっぴ* (GROUP_00273)
void ひなたっぴ_1f28174221c7(CTRPluginFramework::MenuEntry *entry);

// chat (GROUP_00276)
void chat_1f6d6391db70(CTRPluginFramework::MenuEntry *entry);

// アクセサリーショップ (GROUP_00281)
void アクセサリーショップ_1feb09666a1b(CTRPluginFramework::MenuEntry *entry);

// 自然が一番 (GROUP_00284)
void 自然が一番_2027528da44b(CTRPluginFramework::MenuEntry *entry);

// ぼさぼさ (GROUP_00285)
void ぼさぼさ_202d5ae067a8(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00286)
void p_2032572b7cd3(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00287)
void p_20361eb4930a(CTRPluginFramework::MenuEntry *entry);

// ばばあ (GROUP_00290)
void ばばあ_20629760126d(CTRPluginFramework::MenuEntry *entry);

// 23 (GROUP_00291)
void Cheat_23_20b0dcb83619(CTRPluginFramework::MenuEntry *entry);

// クク 3 (GROUP_00301)
void クク_3_21e631b0d8f5(CTRPluginFramework::MenuEntry *entry);

// 3p (GROUP_00302)
void Cheat_3p_220f3526b1b4(CTRPluginFramework::MenuEntry *entry);

// ハンマー動作 (GROUP_00306)
void ハンマー動作_225b9463fc15(CTRPluginFramework::MenuEntry *entry);

// 回転 (GROUP_00307)
void 回転_22933411c30a(CTRPluginFramework::MenuEntry *entry);

// 5×5マスに変更off (GROUP_00308)
void Cheat_5_5マスに変更off_2293830a0e8c(CTRPluginFramework::MenuEntry *entry);

// 網 (GROUP_00310)
void 網_22ff882bbc05(CTRPluginFramework::MenuEntry *entry);

// 8 (GROUP_00314)
void Cheat_8_236edfa0f628(CTRPluginFramework::MenuEntry *entry);

// 掘ると岩のエフェクト (GROUP_00316)
void 掘ると岩のエフェクト_237f83bb577e(CTRPluginFramework::MenuEntry *entry);

// ドロップアイテム変更 (GROUP_00319)
void ドロップアイテム変更_242452704fbd(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00320)
void 自分に_2425672338c5(CTRPluginFramework::MenuEntry *entry);

// 4-2の地形変更 (GROUP_00321)
void Cheat_4_2の地形変更_246d869ba47a(CTRPluginFramework::MenuEntry *entry);

// オートドロップ (GROUP_00326)
void オートドロップ_24db4492f868(CTRPluginFramework::MenuEntry *entry);

// 水中に潜る (GROUP_00327)
void 水中に潜る_24e64c3f6435(CTRPluginFramework::MenuEntry *entry);

// 3p (GROUP_00328)
void Cheat_3p_24fb9047a6e3(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00330)
void 自分に_253ab5446a95(CTRPluginFramework::MenuEntry *entry);

// オノ (GROUP_00331)
void オノ_254550f81752(CTRPluginFramework::MenuEntry *entry);

// デートなんです (GROUP_00334)
void デートなんです_255ab8c85817(CTRPluginFramework::MenuEntry *entry);

// 白 (GROUP_00342)
void 白_264f6337f2c9(CTRPluginFramework::MenuEntry *entry);

// 空気イス (GROUP_00344)
void 空気イス_266e2e1a969a(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00346)
void 座標移動_26a5bdd8a58b(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_00355)
void 緑_276fa0d6cd41(CTRPluginFramework::MenuEntry *entry);

// 美容院 (GROUP_00356)
void 美容院_277f96addee3(CTRPluginFramework::MenuEntry *entry);

// 黄緑 (GROUP_00357)
void 黄緑_2787e09b11cc(CTRPluginFramework::MenuEntry *entry);

// 気絶 (GROUP_00359)
void 気絶_27b257536800(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_00360)
void 未完成_27da89388fff(CTRPluginFramework::MenuEntry *entry);

// 4-4の地形変更 (GROUP_00363)
void Cheat_4_4の地形変更_27e34d32d5f2(CTRPluginFramework::MenuEntry *entry);

// 20 (GROUP_00366)
void Cheat_20_285d38dd545c(CTRPluginFramework::MenuEntry *entry);

// 落ちる (GROUP_00367)
void 落ちる_286e2f73f05c(CTRPluginFramework::MenuEntry *entry);

// アクション停止 (GROUP_00370)
void アクション停止_28aff4ac74d2(CTRPluginFramework::MenuEntry *entry);

// 1-4の地形変更 (GROUP_00372)
void Cheat_1_4の地形変更_28d2dd39b2e0(CTRPluginFramework::MenuEntry *entry);

// 物を置く P1 (GROUP_00375)
void 物を置く_P1_28f58332977d(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00376)
void 座標移動_28fb64cf5bf7(CTRPluginFramework::MenuEntry *entry);

// まめつぶ商店 (GROUP_00377)
void まめつぶ商店_290b6d2cf12a(CTRPluginFramework::MenuEntry *entry);

// 回転 (GROUP_00378)
void 回転_2911253f2286(CTRPluginFramework::MenuEntry *entry);

// 物を重ねて置ける (GROUP_00383)
void 物を重ねて置ける_29e3ddd356af(CTRPluginFramework::MenuEntry *entry);

// 5 (GROUP_00384)
void Cheat_5_29e450db2746(CTRPluginFramework::MenuEntry *entry);

// アクション停止 (GROUP_00390)
void アクション停止_2a9c97ff2d31(CTRPluginFramework::MenuEntry *entry);

// 商品変更2 (GROUP_00392)
void 商品変更2_2b3766e61031(CTRPluginFramework::MenuEntry *entry);

// 埋まってドロップ (GROUP_00393)
void 埋まってドロップ_2b53bf626700(CTRPluginFramework::MenuEntry *entry);

// 流れ星 (GROUP_00394)
void 流れ星_2b5dc46e00f0(CTRPluginFramework::MenuEntry *entry);

// オーキャン (GROUP_00396)
void オーキャン_2b73a31b1c2d(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P4 (外) (GROUP_00403)
void Player_Teleporter_P4_外_2ca068144d3a(CTRPluginFramework::MenuEntry *entry);

// 海の中でも歩く (GROUP_00405)
void 海の中でも歩く_2cd1d7a59311(CTRPluginFramework::MenuEntry *entry);

// 10 (GROUP_00407)
void Cheat_10_2cff442a9406(CTRPluginFramework::MenuEntry *entry);

// あける (GROUP_00408)
void あける_2d04d46a05ef(CTRPluginFramework::MenuEntry *entry);

// いつかは落ち着く (GROUP_00409)
void いつかは落ち着く_2d0633f897e0(CTRPluginFramework::MenuEntry *entry);

// toko tool (GROUP_00410)
void toko_tool_2d113e19e280(CTRPluginFramework::MenuEntry *entry);

// クラゲに刺される (GROUP_00411)
void クラゲに刺される_2d1cc2ee44c3(CTRPluginFramework::MenuEntry *entry);

// 26 (GROUP_00414)
void Cheat_26_2d621842f737(CTRPluginFramework::MenuEntry *entry);

// パーティーだよ (GROUP_00421)
void パーティーだよ_2e1b8872b494(CTRPluginFramework::MenuEntry *entry);

// 2-4の地形変更 (GROUP_00423)
void Cheat_2_4の地形変更_2e550f3a3d60(CTRPluginFramework::MenuEntry *entry);

// 濃い緑 (GROUP_00424)
void 濃い緑_2e57bbba814d(CTRPluginFramework::MenuEntry *entry);

// 24 (GROUP_00428)
void Cheat_24_2eabdeb47ce2(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00432)
void 座標移動_2f242d985da9(CTRPluginFramework::MenuEntry *entry);

// 片づけたい (GROUP_00437)
void 片づけたい_2f9d76b4eeaf(CTRPluginFramework::MenuEntry *entry);

// 連続前転 (GROUP_00440)
void 連続前転_3026c49956ac(CTRPluginFramework::MenuEntry *entry);

// 5 (GROUP_00441)
void Cheat_5_309d368962b6(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_00444)
void 有効_3118ab94a3a0(CTRPluginFramework::MenuEntry *entry);

// 水中にする (GROUP_00445)
void 水中にする_313f2cbb89ca(CTRPluginFramework::MenuEntry *entry);

// ガーリーなゆるさ (GROUP_00450)
void ガーリーなゆるさ_31839fa76fa2(CTRPluginFramework::MenuEntry *entry);

// 立ち泳ぎ (GROUP_00453)
void 立ち泳ぎ_31ca0aada05f(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00456)
void p_3214753800b7(CTRPluginFramework::MenuEntry *entry);

// 立ち寝 (GROUP_00459)
void 立ち寝_328cacbc9b4e(CTRPluginFramework::MenuEntry *entry);

// 根性で乗り越える (GROUP_00461)
void 根性で乗り越える_3295b50776a5(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_00462)
void 完成_32ae840444ad(CTRPluginFramework::MenuEntry *entry);

// 0 (GROUP_00466)
void Cheat_0_3355ead082cb(CTRPluginFramework::MenuEntry *entry);

// スコップ (GROUP_00468)
void スコップ_33680db168c3(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00469)
void p_33908a9ace66(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00471)
void p_33e6385c6b1e(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00478)
void p_34e018868354(CTRPluginFramework::MenuEntry *entry);

// 6 (GROUP_00479)
void Cheat_6_34e1f90ed4be(CTRPluginFramework::MenuEntry *entry);

// 寝る (GROUP_00486)
void 寝る_3598f8c969ae(CTRPluginFramework::MenuEntry *entry);

// じっと耐えます (GROUP_00487)
void じっと耐えます_359cfa30a5e7(CTRPluginFramework::MenuEntry *entry);

// NPC くるりんぱ (エフェクトあり) (GROUP_00488)
void NPC_くるりんぱ_エフェクトあり_359d51f45811(CTRPluginFramework::MenuEntry *entry);

// 薄い紫 (GROUP_00489)
void 薄い紫_35a1a658edfe(CTRPluginFramework::MenuEntry *entry);

// 誰も寄せつけたくない (GROUP_00493)
void 誰も寄せつけたくない_35f0c7127298(CTRPluginFramework::MenuEntry *entry);

// 赤 (GROUP_00498)
void 赤_36ef7873f03a(CTRPluginFramework::MenuEntry *entry);

// 駅 (GROUP_00500)
void 駅_3717a4386ec1(CTRPluginFramework::MenuEntry *entry);

// 商品変更2 (GROUP_00506)
void 商品変更2_37a8080d920b(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00514)
void p_38433f0aaa1f(CTRPluginFramework::MenuEntry *entry);

// 解除 (GROUP_00517)
void 解除_38623a7c1b7e(CTRPluginFramework::MenuEntry *entry);

// ふわっとしたゆるさ (GROUP_00520)
void ふわっとしたゆるさ_3878683dc67f(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00529)
void p_395c5015af08(CTRPluginFramework::MenuEntry *entry);

// スペーストラベラー (GROUP_00531)
void スペーストラベラー_39d04bee5f29(CTRPluginFramework::MenuEntry *entry);

// クラシックな交番 (GROUP_00537)
void クラシックな交番_3a87567aa4fb(CTRPluginFramework::MenuEntry *entry);

// リセット (GROUP_00539)
void リセット_3ab82b1b22f0(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_00540)
void 完成_3acc5b730de0(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00542)
void 座標移動_3b32b8c5c80d(CTRPluginFramework::MenuEntry *entry);

// 豆 (GROUP_00544)
void 豆_3b48c67a09f1(CTRPluginFramework::MenuEntry *entry);

// 地中深くに沈む (GROUP_00548)
void 地中深くに沈む_3baaa064183a(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_00550)
void 緑_3bc4de615022(CTRPluginFramework::MenuEntry *entry);

// 解除 (GROUP_00552)
void 解除_3bd347174e0c(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00555)
void p_3c118b343009(CTRPluginFramework::MenuEntry *entry);

// じっと耐えます (GROUP_00556)
void じっと耐えます_3c6b106db446(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室内 (GROUP_00557)
void スネークモーション_室内_3c70dbd1c339(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00559)
void 座標移動_3c93035f75bf(CTRPluginFramework::MenuEntry *entry);

// 2-3の地形変更 (GROUP_00569)
void Cheat_2_3の地形変更_3d8bb3967b41(CTRPluginFramework::MenuEntry *entry);

// 駅 (GROUP_00570)
void 駅_3e161946f613(CTRPluginFramework::MenuEntry *entry);

// 赤 (GROUP_00571)
void 赤_3e1b8b0dbc6f(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00573)
void 座標移動_3e382cfc89b7(CTRPluginFramework::MenuEntry *entry);

// シャボン玉 (GROUP_00574)
void シャボン玉_3e53408d5d15(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00575)
void p_3e62a9ad45ae(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_00576)
void 完成_3e79389c7491(CTRPluginFramework::MenuEntry *entry);

// ムーンジャンプ P3 (GROUP_00579)
void ムーンジャンプ_P3_3ec5a0f882d6(CTRPluginFramework::MenuEntry *entry);

// クラッカー (GROUP_00580)
void クラッカー_3edfdbd277be(CTRPluginFramework::MenuEntry *entry);

// 泳ぐ (GROUP_00581)
void 泳ぐ_3f11551864f6(CTRPluginFramework::MenuEntry *entry);

// クーコ 4 (GROUP_00582)
void クーコ_4_3f3c3533810f(CTRPluginFramework::MenuEntry *entry);

// 物を置く P4 (GROUP_00583)
void 物を置く_P4_3f3c7ab93507(CTRPluginFramework::MenuEntry *entry);

// オレンジ (GROUP_00586)
void オレンジ_3fa0957ec0d4(CTRPluginFramework::MenuEntry *entry);

// キーボード海外 (GROUP_00587)
void キーボード海外_3fa579412835(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P2 (内) (GROUP_00591)
void Player_Teleporter_P2_内_404dce87d9a6(CTRPluginFramework::MenuEntry *entry);

// 14 (GROUP_00592)
void Cheat_14_406d28df943f(CTRPluginFramework::MenuEntry *entry);

// 片づけたい (GROUP_00594)
void 片づけたい_40ca41bccfb7(CTRPluginFramework::MenuEntry *entry);

// リサイクルショップ (GROUP_00598)
void リサイクルショップ_410ea34b8c95(CTRPluginFramework::MenuEntry *entry);

// お屋敷 (GROUP_00601)
void お屋敷_4152da883b2d(CTRPluginFramework::MenuEntry *entry);

// 渋いいけがき (GROUP_00602)
void 渋いいけがき_418ad29aacbb(CTRPluginFramework::MenuEntry *entry);

// チャット連続送信 (GROUP_00604)
void チャット連続送信_41a96356ab9a(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00607)
void p_424b6a1b4f69(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P1 (外) (GROUP_00613)
void Player_Teleporter_P1_外_42925e2ddf9b(CTRPluginFramework::MenuEntry *entry);

// ムーンジャンプ P2 (GROUP_00619)
void ムーンジャンプ_P2_43196c331811(CTRPluginFramework::MenuEntry *entry);

// 叩かれる (GROUP_00621)
void 叩かれる_434ca825df29(CTRPluginFramework::MenuEntry *entry);

// 連続でクラゲに刺される動作 (GROUP_00622)
void 連続でクラゲに刺される動作_435a2872649b(CTRPluginFramework::MenuEntry *entry);

// 根性で乗り越える (GROUP_00623)
void 根性で乗り越える_438214c8114a(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00624)
void p_43902ffcb836(CTRPluginFramework::MenuEntry *entry);

// 2 (GROUP_00625)
void Cheat_2_43abd40c4198(CTRPluginFramework::MenuEntry *entry);

// 2p (GROUP_00626)
void Cheat_2p_43ac2bba0f24(CTRPluginFramework::MenuEntry *entry);

// 島室内 (GROUP_00627)
void 島室内_43c5fb4a82da(CTRPluginFramework::MenuEntry *entry);

// デパート (GROUP_00631)
void デパート_44022c7d78cb(CTRPluginFramework::MenuEntry *entry);

// 黄色 (GROUP_00632)
void 黄色_44228148bd70(CTRPluginFramework::MenuEntry *entry);

// フランス (GROUP_00633)
void フランス_443105a992c7(CTRPluginFramework::MenuEntry *entry);

// 尻もち (GROUP_00635)
void 尻もち_447e7965726d(CTRPluginFramework::MenuEntry *entry);

// 赤バラ見せびらかす (GROUP_00636)
void 赤バラ見せびらかす_44800c3ba4a4(CTRPluginFramework::MenuEntry *entry);

// 17 (GROUP_00638)
void Cheat_17_44b63b16b459(CTRPluginFramework::MenuEntry *entry);

// スペーストラベラー (GROUP_00644)
void スペーストラベラー_45309a2da39a(CTRPluginFramework::MenuEntry *entry);

// 風車 (GROUP_00645)
void 風車_454fc9f3e836(CTRPluginFramework::MenuEntry *entry);

// ブレーキ (GROUP_00646)
void ブレーキ_45601c1fe17a(CTRPluginFramework::MenuEntry *entry);

// パーティーだよ (GROUP_00649)
void パーティーだよ_45a00da775bc(CTRPluginFramework::MenuEntry *entry);

// 園芸店 (GROUP_00651)
void 園芸店_45ee5d0f2d15(CTRPluginFramework::MenuEntry *entry);

// ホームセンター (GROUP_00658)
void ホームセンター_46f7c2953aec(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00659)
void 座標移動_4700385ebcdc(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00663)
void 座標移動_474f312c9355(CTRPluginFramework::MenuEntry *entry);

// 25 (GROUP_00666)
void Cheat_25_47a885202433(CTRPluginFramework::MenuEntry *entry);

// 7 (GROUP_00667)
void Cheat_7_47b62d3888d1(CTRPluginFramework::MenuEntry *entry);

// ハンマー動作 (GROUP_00668)
void ハンマー動作_4822af1116f8(CTRPluginFramework::MenuEntry *entry);

// みせびらかす (GROUP_00671)
void みせびらかす_4880ec0737ef(CTRPluginFramework::MenuEntry *entry);

// 8 (GROUP_00673)
void Cheat_8_488b9bc48d50(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_00676)
void Cheat_1_48fdd8e9dcb2(CTRPluginFramework::MenuEntry *entry);

// 2-3の地形変更 (GROUP_00677)
void Cheat_2_3の地形変更_4905d3d704a8(CTRPluginFramework::MenuEntry *entry);

// 前回転でドロップ (GROUP_00680)
void 前回転でドロップ_49630f112efe(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_00684)
void 茶色_49a85303a038(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00686)
void p_49caeefcbc94(CTRPluginFramework::MenuEntry *entry);

// 水中に潜る (GROUP_00687)
void 水中に潜る_49ea4a6366e7(CTRPluginFramework::MenuEntry *entry);

// 27 (GROUP_00689)
void Cheat_27_49f39bbb36ca(CTRPluginFramework::MenuEntry *entry);

// 前回転でドロップ (GROUP_00691)
void 前回転でドロップ_4a27446e59ae(CTRPluginFramework::MenuEntry *entry);

// 落ちる (GROUP_00692)
void 落ちる_4a7716ebb242(CTRPluginFramework::MenuEntry *entry);

// 3-1の地形変更 (GROUP_00694)
void Cheat_3_1の地形変更_4a9d1dd4a8d6(CTRPluginFramework::MenuEntry *entry);

// 2p (GROUP_00697)
void Cheat_2p_4aeac7c9f550(CTRPluginFramework::MenuEntry *entry);

// 19 (GROUP_00699)
void Cheat_19_4b05f95c897e(CTRPluginFramework::MenuEntry *entry);

// マイデザイン (GROUP_00700)
void マイデザイン_4b2d3fef472b(CTRPluginFramework::MenuEntry *entry);

// ムーンジャンプ P1 (GROUP_00702)
void ムーンジャンプ_P1_4b6d310b4c66(CTRPluginFramework::MenuEntry *entry);

// オランダ (GROUP_00703)
void オランダ_4b78f4153714(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00709)
void p_4c0d1e767d2f(CTRPluginFramework::MenuEntry *entry);

// どこでも泳げる (GROUP_00714)
void どこでも泳げる_4c589ffa4b51(CTRPluginFramework::MenuEntry *entry);

// 黒色 (GROUP_00722)
void 黒色_4ca5f152a8ac(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00726)
void p_4cca950561bc(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00727)
void p_4ccc3d832422(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量250 (GROUP_00730)
void 紙吹雪量250_4d3e006ed7fc(CTRPluginFramework::MenuEntry *entry);

// 金色 (GROUP_00732)
void 金色_4db4f0ca5dcb(CTRPluginFramework::MenuEntry *entry);

// 14 (GROUP_00739)
void Cheat_14_4e66e41415a5(CTRPluginFramework::MenuEntry *entry);

// 村 (GROUP_00740)
void 村_4e672e708775(CTRPluginFramework::MenuEntry *entry);

// sopaca (GROUP_00742)
void sopaca_4e76ec671240(CTRPluginFramework::MenuEntry *entry);

// 村 (GROUP_00746)
void 村_4ed9d671376b(CTRPluginFramework::MenuEntry *entry);

// 3-2の地形変更 (GROUP_00747)
void Cheat_3_2の地形変更_4efd58160cf1(CTRPluginFramework::MenuEntry *entry);

// たんぽぽ (GROUP_00748)
void たんぽぽ_4f0a91d60e4d(CTRPluginFramework::MenuEntry *entry);

// ベテランで (GROUP_00750)
void ベテランで_4fb390e74d06(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00754)
void p_506d449e35d5(CTRPluginFramework::MenuEntry *entry);

// デパート3階 (GROUP_00757)
void デパート3階_50919bbcfac2(CTRPluginFramework::MenuEntry *entry);

// 3 (GROUP_00758)
void Cheat_3_50ac15c6c3cc(CTRPluginFramework::MenuEntry *entry);

// リッチな条例 (GROUP_00761)
void リッチな条例_51193639e974(CTRPluginFramework::MenuEntry *entry);

// 2-3の地形変更 (GROUP_00762)
void Cheat_2_3の地形変更_511d6301791a(CTRPluginFramework::MenuEntry *entry);

// ずっとヤンチャ (GROUP_00763)
void ずっとヤンチャ_512d96879864(CTRPluginFramework::MenuEntry *entry);

// 黒色 (GROUP_00769)
void 黒色_5184d66b9e05(CTRPluginFramework::MenuEntry *entry);

// 9 (GROUP_00772)
void Cheat_9_519c836d9941(CTRPluginFramework::MenuEntry *entry);

// クラッカー (GROUP_00774)
void クラッカー_51b473d85954(CTRPluginFramework::MenuEntry *entry);

// kaijo (GROUP_00775)
void kaijo_51bd33444491(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00779)
void p_522a9950a176(CTRPluginFramework::MenuEntry *entry);

// ベテランで (GROUP_00782)
void ベテランで_5309a4aaad7d(CTRPluginFramework::MenuEntry *entry);

// 19 (GROUP_00784)
void Cheat_19_53149f38160f(CTRPluginFramework::MenuEntry *entry);

// 切っても切れない (GROUP_00788)
void 切っても切れない_53687df7d8b8(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00789)
void 自分に_53694208e484(CTRPluginFramework::MenuEntry *entry);

// モダンな交番 (GROUP_00791)
void モダンな交番_53747daad66d(CTRPluginFramework::MenuEntry *entry);

// 3-3の地形変更 (GROUP_00794)
void Cheat_3_3の地形変更_53db8d409e60(CTRPluginFramework::MenuEntry *entry);

// 着替える (GROUP_00796)
void 着替える_53fd1101f173(CTRPluginFramework::MenuEntry *entry);

// 乗っ取り (GROUP_00797)
void 乗っ取り_54372431de60(CTRPluginFramework::MenuEntry *entry);

// 15 (GROUP_00804)
void Cheat_15_550f9b6369a9(CTRPluginFramework::MenuEntry *entry);

// 韓国 (GROUP_00806)
void 韓国_55201cb6e93c(CTRPluginFramework::MenuEntry *entry);

// 明るい茶色 (GROUP_00809)
void 明るい茶色_552837a77d72(CTRPluginFramework::MenuEntry *entry);

// けだるいゆるさ (GROUP_00810)
void けだるいゆるさ_552dd6a1a213(CTRPluginFramework::MenuEntry *entry);

// テント (GROUP_00814)
void テント_55bcf1fdb1e0(CTRPluginFramework::MenuEntry *entry);

// マイデザを貼る4P (GROUP_00815)
void マイデザを貼る4P_55c2cecfaec4(CTRPluginFramework::MenuEntry *entry);

// デパート3階 (GROUP_00816)
void デパート3階_55d84a5a301d(CTRPluginFramework::MenuEntry *entry);

// じめんにうめる (GROUP_00823)
void じめんにうめる_56eb4054b024(CTRPluginFramework::MenuEntry *entry);

// 黄色 (GROUP_00824)
void 黄色_571975504f8d(CTRPluginFramework::MenuEntry *entry);

// オーキャン (GROUP_00831)
void オーキャン_5825d83e2093(CTRPluginFramework::MenuEntry *entry);

// 12 (GROUP_00832)
void Cheat_12_587a8b3a9d61(CTRPluginFramework::MenuEntry *entry);

// 王冠 (GROUP_00833)
void 王冠_589d913a7d4d(CTRPluginFramework::MenuEntry *entry);

// 3 (GROUP_00837)
void Cheat_3_58d7545ca9e8(CTRPluginFramework::MenuEntry *entry);

// 2-1の地形変更 (GROUP_00838)
void Cheat_2_1の地形変更_58d9348257fc(CTRPluginFramework::MenuEntry *entry);

// 置けない表示消す (GROUP_00839)
void 置けない表示消す_590ef5e9204c(CTRPluginFramework::MenuEntry *entry);

// ALL (GROUP_00841)
void ALL_594036b095b9(CTRPluginFramework::MenuEntry *entry);

// 青色 (GROUP_00842)
void 青色_5957bfff4ed0(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00846)
void 座標移動_597dfd8e3386(CTRPluginFramework::MenuEntry *entry);

// タイマーをはかる (GROUP_00848)
void タイマーをはかる_59dfabf983d9(CTRPluginFramework::MenuEntry *entry);

// 揺らしてドロップ (GROUP_00850)
void 揺らしてドロップ_5a15c17252cb(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00854)
void 自分に_5a4341af127f(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_00859)
void 濃い青_5ad6c492971e(CTRPluginFramework::MenuEntry *entry);

// 無効 (GROUP_00860)
void 無効_5adef4d0c841(CTRPluginFramework::MenuEntry *entry);

// スクショ無効 (GROUP_00864)
void スクショ無効_5bf39217affa(CTRPluginFramework::MenuEntry *entry);

// 風船 (GROUP_00865)
void 風船_5c17a1a7e052(CTRPluginFramework::MenuEntry *entry);

// ずっとやんちゃ (GROUP_00866)
void ずっとやんちゃ_5c362218cc41(CTRPluginFramework::MenuEntry *entry);

// 連続アクション (GROUP_00867)
void 連続アクション_5c3d2ae54b8f(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00871)
void p_5cf70a38a011(CTRPluginFramework::MenuEntry *entry);

// なんでもおいしい (GROUP_00875)
void なんでもおいしい_5d2040ef7d37(CTRPluginFramework::MenuEntry *entry);

// 1P (GROUP_00877)
void Cheat_1P_5d3dbe9d5e9a(CTRPluginFramework::MenuEntry *entry);

// 黒 (GROUP_00880)
void 黒_5d49011e8c98(CTRPluginFramework::MenuEntry *entry);

// しまう (GROUP_00881)
void しまう_5da38672191d(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P1 (内) (GROUP_00884)
void Player_Teleporter_P1_内_5de2995b0c6a(CTRPluginFramework::MenuEntry *entry);

// 4p (GROUP_00886)
void Cheat_4p_5decd998d6b0(CTRPluginFramework::MenuEntry *entry);

// 食べる (GROUP_00891)
void 食べる_5e6788c312cb(CTRPluginFramework::MenuEntry *entry);

// ブラジル (GROUP_00894)
void ブラジル_5ea2f5b4cbc2(CTRPluginFramework::MenuEntry *entry);

// オンにしてる間島のアイテム無料 (GROUP_00897)
void オンにしてる間島のアイテム無料_5efc4cef527b(CTRPluginFramework::MenuEntry *entry);

// オノを壊す (GROUP_00900)
void オノを壊す_5f39138111b3(CTRPluginFramework::MenuEntry *entry);

// ベテランで (GROUP_00902)
void ベテランで_5f4a7d56f490(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_00903)
void 有効_5f961ca11154(CTRPluginFramework::MenuEntry *entry);

// やったー (GROUP_00906)
void やったー_5ff755feea0a(CTRPluginFramework::MenuEntry *entry);

// 島室内 (GROUP_00907)
void 島室内_6005c33e6596(CTRPluginFramework::MenuEntry *entry);

// 4 (GROUP_00908)
void Cheat_4_6037dbe33897(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00909)
void p_606a33e44320(CTRPluginFramework::MenuEntry *entry);

// もの渡す (GROUP_00910)
void もの渡す_608ac79a8925(CTRPluginFramework::MenuEntry *entry);

// 6 (GROUP_00914)
void Cheat_6_60de0d40d818(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_00916)
void スネークモーション_室外_60ec3813518b(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P3 (外) (GROUP_00918)
void Player_Teleporter_P3_外_6121e8bc4491(CTRPluginFramework::MenuEntry *entry);

// 24 (GROUP_00919)
void Cheat_24_613f0e7552ed(CTRPluginFramework::MenuEntry *entry);

// けだるいゆるさ (GROUP_00920)
void けだるいゆるさ_6147b54273ed(CTRPluginFramework::MenuEntry *entry);

// 尻もち (GROUP_00921)
void 尻もち_617420b8d52f(CTRPluginFramework::MenuEntry *entry);

// たんぽぽ (GROUP_00923)
void たんぽぽ_61874ce7c8c0(CTRPluginFramework::MenuEntry *entry);

// ドア (GROUP_00924)
void ドア_61a6fee968f7(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_00925)
void スネークモーション_室外_61c5f07fc571(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_00927)
void 茶色_62745ad2697c(CTRPluginFramework::MenuEntry *entry);

// こうご (GROUP_00929)
void こうご_6285374b44a2(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00931)
void 座標移動_62c1b23ceefe(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00935)
void 自分に_632c13c007f3(CTRPluginFramework::MenuEntry *entry);

// オノ跳ね返り (GROUP_00940)
void オノ跳ね返り_6389b9c93c65(CTRPluginFramework::MenuEntry *entry);

// 泳ぐ (GROUP_00941)
void 泳ぐ_63af7b4b3977(CTRPluginFramework::MenuEntry *entry);

// 島室外 (GROUP_00943)
void 島室外_63d18f3a7799(CTRPluginFramework::MenuEntry *entry);

// デートなんです (GROUP_00948)
void デートなんです_64f34208c0b0(CTRPluginFramework::MenuEntry *entry);

// 服屋 (GROUP_00949)
void 服屋_656d9a8e3844(CTRPluginFramework::MenuEntry *entry);

// シャボン玉 (GROUP_00950)
void シャボン玉_6571c6680c0a(CTRPluginFramework::MenuEntry *entry);

// 白 (GROUP_00953)
void 白_65b9e9b12d8c(CTRPluginFramework::MenuEntry *entry);

// 10 (GROUP_00955)
void Cheat_10_65f561916b1b(CTRPluginFramework::MenuEntry *entry);

// 連続気絶 (GROUP_00958)
void 連続気絶_662801210f1d(CTRPluginFramework::MenuEntry *entry);

// 日本 (GROUP_00959)
void 日本_662a3d9e2dda(CTRPluginFramework::MenuEntry *entry);

// 空気椅子 (GROUP_00960)
void 空気椅子_663b2d5c3677(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_00961)
void 自分に_665a8e5c1873(CTRPluginFramework::MenuEntry *entry);

// ぼさぼさ (GROUP_00962)
void ぼさぼさ_6680981ac7c5(CTRPluginFramework::MenuEntry *entry);

// 潜る1 (GROUP_00963)
void 潜る1_6684ea8a4ce4(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_00964)
void p_66a12c83008d(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_00965)
void 座標移動_66a847d24b5e(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_00970)
void 未完成_66f4bf319a65(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_00977)
void 緑_67db5c73e65a(CTRPluginFramework::MenuEntry *entry);

// kuko 2 (GROUP_00981)
void kuko_2_685ac6a1580c(CTRPluginFramework::MenuEntry *entry);

// 1-2の地形変更 (GROUP_00983)
void Cheat_1_2の地形変更_687bdb46f287(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室内 (GROUP_00984)
void スネークモーション_室内_68955fea87bc(CTRPluginFramework::MenuEntry *entry);

// 4-1の地形変更 (GROUP_00993)
void Cheat_4_1の地形変更_69713cdc20c3(CTRPluginFramework::MenuEntry *entry);

// 置いても見えない (GROUP_00995)
void 置いても見えない_698e0dd43387(CTRPluginFramework::MenuEntry *entry);

// 黒 (GROUP_00999)
void 黒_6a25ec529ad5(CTRPluginFramework::MenuEntry *entry);

// わざとだよ (GROUP_01004)
void わざとだよ_6a6bfd4cce96(CTRPluginFramework::MenuEntry *entry);

// 風船 (GROUP_01007)
void 風船_6adba59668bf(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01008)
void 自分に_6b0837d96867(CTRPluginFramework::MenuEntry *entry);

// どこでもうき投げれる (GROUP_01017)
void どこでもうき投げれる_6c8964fca099(CTRPluginFramework::MenuEntry *entry);

// 坊主になる (GROUP_01019)
void 坊主になる_6cdf6cf3fc7d(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01023)
void p_6d446ec8ede4(CTRPluginFramework::MenuEntry *entry);

// 受け取る (GROUP_01024)
void 受け取る_6d63d8aa0ab4(CTRPluginFramework::MenuEntry *entry);

// 1-1の地形変更 (GROUP_01025)
void Cheat_1_1の地形変更_6d6c214ed052(CTRPluginFramework::MenuEntry *entry);

// 2p (GROUP_01027)
void Cheat_2p_6dd68e546c0a(CTRPluginFramework::MenuEntry *entry);

// 7 (GROUP_01033)
void Cheat_7_6e9886647795(CTRPluginFramework::MenuEntry *entry);

// 坊主になる (GROUP_01037)
void 坊主になる_6eb9f709b932(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01045)
void 座標移動_6fa60f50247d(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01046)
void p_6fae84c5df85(CTRPluginFramework::MenuEntry *entry);

// 憧れたい (GROUP_01049)
void 憧れたい_700e55e57bff(CTRPluginFramework::MenuEntry *entry);

// よろける (GROUP_01053)
void よろける_706eb3ea5a1c(CTRPluginFramework::MenuEntry *entry);

// オン (GROUP_01061)
void オン_715ac9b96b77(CTRPluginFramework::MenuEntry *entry);

// 止まると動きがフリーズ (GROUP_01062)
void 止まると動きがフリーズ_7171906722a2(CTRPluginFramework::MenuEntry *entry);

// テクスチャ変更 (GROUP_01069)
void テクスチャ変更_720030dc66ee(CTRPluginFramework::MenuEntry *entry);

// ベテランで (GROUP_01070)
void ベテランで_7266a8a2cdbf(CTRPluginFramework::MenuEntry *entry);

// 画面が緑 (GROUP_01073)
void 画面が緑_7295720e6a1e(CTRPluginFramework::MenuEntry *entry);

// フレッシュで (GROUP_01074)
void フレッシュで_729e4eb9ac62(CTRPluginFramework::MenuEntry *entry);

// スコップ (GROUP_01075)
void スコップ_72ac957cc3ae(CTRPluginFramework::MenuEntry *entry);

// toko tool (GROUP_01077)
void toko_tool_72c5641dce41(CTRPluginFramework::MenuEntry *entry);

// 2-4の地形変更 (GROUP_01089)
void Cheat_2_4の地形変更_73bb0087c8f9(CTRPluginFramework::MenuEntry *entry);

// 前転 (GROUP_01091)
void 前転_73c2d5abc241(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01093)
void p_73f39ab11f48(CTRPluginFramework::MenuEntry *entry);

// 唾を吐く (GROUP_01095)
void 唾を吐く_7447369a7f6c(CTRPluginFramework::MenuEntry *entry);

// 潜る2 (GROUP_01096)
void 潜る2_749b7719cdc7(CTRPluginFramework::MenuEntry *entry);

// ホームセンター (GROUP_01098)
void ホームセンター_74cf2cf776b8(CTRPluginFramework::MenuEntry *entry);

// 元に戻す (GROUP_01099)
void 元に戻す_750a70317d9c(CTRPluginFramework::MenuEntry *entry);

// 1p (GROUP_01103)
void Cheat_1p_756d7a6b747a(CTRPluginFramework::MenuEntry *entry);

// アクション連発 (GROUP_01111)
void アクション連発_7635327eaa3d(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01112)
void p_7642eda4e883(CTRPluginFramework::MenuEntry *entry);

// 永遠のドリーマー (GROUP_01113)
void 永遠のドリーマー_76430ca49d11(CTRPluginFramework::MenuEntry *entry);

// 22 (GROUP_01115)
void Cheat_22_76e44f0e3273(CTRPluginFramework::MenuEntry *entry);

// NPC 着替えさせる (GROUP_01123)
void NPC_着替えさせる_77f543e23a8f(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_01124)
void 濃い青_7824be4cbe55(CTRPluginFramework::MenuEntry *entry);

// 4p (GROUP_01128)
void Cheat_4p_791238ef27b4(CTRPluginFramework::MenuEntry *entry);

// タイマーをはかる (GROUP_01129)
void タイマーをはかる_79224150a5de(CTRPluginFramework::MenuEntry *entry);

// motimono (GROUP_01130)
void motimono_792b42837867(CTRPluginFramework::MenuEntry *entry);

// 網 (GROUP_01132)
void 網_795500c7ab3d(CTRPluginFramework::MenuEntry *entry);

// シナモロール (GROUP_01134)
void シナモロール_79b05c841803(CTRPluginFramework::MenuEntry *entry);

// 動作乗っ取り解除 (GROUP_01137)
void 動作乗っ取り解除_7a69f250f46e(CTRPluginFramework::MenuEntry *entry);

// 21 (GROUP_01138)
void Cheat_21_7a6f5f3af07f(CTRPluginFramework::MenuEntry *entry);

// おサイフにしまう (GROUP_01139)
void おサイフにしまう_7aa8f89c32b4(CTRPluginFramework::MenuEntry *entry);

// 足で消してドロップ (GROUP_01140)
void 足で消してドロップ_7abacfed9ff4(CTRPluginFramework::MenuEntry *entry);

// ハチ (GROUP_01143)
void ハチ_7b03677a09fb(CTRPluginFramework::MenuEntry *entry);

// 2-4の地形変更 (GROUP_01145)
void Cheat_2_4の地形変更_7b3cc62ae1f4(CTRPluginFramework::MenuEntry *entry);

// 埋めるときの動作3P (GROUP_01148)
void 埋めるときの動作3P_7b4efa66a2c6(CTRPluginFramework::MenuEntry *entry);

// パーティーだよ (GROUP_01150)
void パーティーだよ_7bad81aee778(CTRPluginFramework::MenuEntry *entry);

// 食べる (GROUP_01151)
void 食べる_7bb7067c3f2d(CTRPluginFramework::MenuEntry *entry);

// モダンな交番 (GROUP_01152)
void モダンな交番_7bef7ec692d6(CTRPluginFramework::MenuEntry *entry);

// カフェ (GROUP_01153)
void カフェ_7bf64a4cec94(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01160)
void p_7c8d2bc1be5f(CTRPluginFramework::MenuEntry *entry);

// 0 (GROUP_01163)
void Cheat_0_7d0996f68bbc(CTRPluginFramework::MenuEntry *entry);

// 4p (GROUP_01164)
void Cheat_4p_7d17271e7e84(CTRPluginFramework::MenuEntry *entry);

// ものとる (GROUP_01167)
void ものとる_7d9eea823b19(CTRPluginFramework::MenuEntry *entry);

// 自然が一番 (GROUP_01169)
void 自然が一番_7da9d8f47291(CTRPluginFramework::MenuEntry *entry);

// 地面に植える (GROUP_01171)
void 地面に植える_7dd7a3825776(CTRPluginFramework::MenuEntry *entry);

// 15 (GROUP_01174)
void Cheat_15_7dedbe977f0a(CTRPluginFramework::MenuEntry *entry);

// 地面透明化 (GROUP_01177)
void 地面透明化_7e3bb1e51716(CTRPluginFramework::MenuEntry *entry);

// 17 (GROUP_01179)
void Cheat_17_7e4d64b0a8d6(CTRPluginFramework::MenuEntry *entry);

// 赤 (GROUP_01180)
void 赤_7e563cd99372(CTRPluginFramework::MenuEntry *entry);

// 商店街 (GROUP_01188)
void 商店街_7f16b9d0e71a(CTRPluginFramework::MenuEntry *entry);

// 16 (GROUP_01190)
void Cheat_16_7f35f08dabd8(CTRPluginFramework::MenuEntry *entry);

// 空気椅子 (GROUP_01191)
void 空気椅子_7f5f7c3c663f(CTRPluginFramework::MenuEntry *entry);

// 誰も寄せつけたくない (GROUP_01192)
void 誰も寄せつけたくない_7f6433d02f08(CTRPluginFramework::MenuEntry *entry);

// 自然が一番 (GROUP_01195)
void 自然が一番_7f9ace3e122e(CTRPluginFramework::MenuEntry *entry);

// 1-4の地形変更 (GROUP_01197)
void Cheat_1_4の地形変更_8013746c7f65(CTRPluginFramework::MenuEntry *entry);

// ふわっとしたゆるさ (GROUP_01198)
void ふわっとしたゆるさ_802dd1a6802a(CTRPluginFramework::MenuEntry *entry);

// 地面透明化 (GROUP_01205)
void 地面透明化_8103dbf326ae(CTRPluginFramework::MenuEntry *entry);

// 置けない表示消す (GROUP_01208)
void 置けない表示消す_81333873301f(CTRPluginFramework::MenuEntry *entry);

// オン島でフレンド申請 (GROUP_01209)
void オン島でフレンド申請_817df57a737e(CTRPluginFramework::MenuEntry *entry);

// 12 (GROUP_01211)
void Cheat_12_81a478c0d6fa(CTRPluginFramework::MenuEntry *entry);

// neta (GROUP_01212)
void neta_81a8dadbf5de(CTRPluginFramework::MenuEntry *entry);

// 無効 (GROUP_01214)
void 無効_81ca76508f17(CTRPluginFramework::MenuEntry *entry);

// 無効 (GROUP_01216)
void 無効_81f332ce7765(CTRPluginFramework::MenuEntry *entry);

// 工事中 (GROUP_01217)
void 工事中_82127beaa1e3(CTRPluginFramework::MenuEntry *entry);

// 金色 (GROUP_01224)
void 金色_830e1cfeee4d(CTRPluginFramework::MenuEntry *entry);

// アイテムを残す (GROUP_01232)
void アイテムを残す_84005b1b49c9(CTRPluginFramework::MenuEntry *entry);

// いつかは落ち着く (GROUP_01233)
void いつかは落ち着く_84191024a17a(CTRPluginFramework::MenuEntry *entry);

// 連続アミ振り (GROUP_01234)
void 連続アミ振り_84464e3af463(CTRPluginFramework::MenuEntry *entry);

// toko tool (GROUP_01235)
void toko_tool_8498e220dd99(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_01238)
void スネークモーション_室外_84d39bf27804(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01240)
void p_84fe1a6136ee(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01243)
void p_85233f8473c5(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01246)
void p_8597f2c6f523(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_01247)
void 緑_85999b5445c1(CTRPluginFramework::MenuEntry *entry);

// 12 (GROUP_01248)
void Cheat_12_859d1f583fc1(CTRPluginFramework::MenuEntry *entry);

// NPC 豆まき (GROUP_01249)
void NPC_豆まき_85c9ad58ad73(CTRPluginFramework::MenuEntry *entry);

// オン島でフレンド申請 (GROUP_01250)
void オン島でフレンド申請_85dac82c9c32(CTRPluginFramework::MenuEntry *entry);

// 憧れたい (GROUP_01251)
void 憧れたい_85ea804f5a0a(CTRPluginFramework::MenuEntry *entry);

// 黄色 (GROUP_01252)
void 黄色_86169de6e504(CTRPluginFramework::MenuEntry *entry);

// スコップ解除 (GROUP_01253)
void スコップ解除_861d7ca1af8e(CTRPluginFramework::MenuEntry *entry);

// メガホン (GROUP_01254)
void メガホン_864373920bfe(CTRPluginFramework::MenuEntry *entry);

// リサイクルショップ (GROUP_01255)
void リサイクルショップ_8648c93b689d(CTRPluginFramework::MenuEntry *entry);

// マイデザ (GROUP_01257)
void マイデザ_867a0ea3a5d6(CTRPluginFramework::MenuEntry *entry);

// 15×15マスに変更off (GROUP_01259)
void Cheat_15_15マスに変更off_86882e8e50fc(CTRPluginFramework::MenuEntry *entry);

// 白 (GROUP_01260)
void 白_86d5a36268bf(CTRPluginFramework::MenuEntry *entry);

// 4-4の地形変更 (GROUP_01263)
void Cheat_4_4の地形変更_878e16edcfe9(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作でドロップ (GROUP_01266)
void 岩壊す動作でドロップ_87c4133b9722(CTRPluginFramework::MenuEntry *entry);

// 3p (GROUP_01273)
void Cheat_3p_885dae0844b5(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_01275)
void 緑_887078d931ad(CTRPluginFramework::MenuEntry *entry);

// 白 (GROUP_01276)
void 白_888d7a144f74(CTRPluginFramework::MenuEntry *entry);

// 空気イス (GROUP_01277)
void 空気イス_88951c35cc65(CTRPluginFramework::MenuEntry *entry);

// 島平地化 (GROUP_01278)
void 島平地化_8899164413e1(CTRPluginFramework::MenuEntry *entry);

// マイデザを貼る3P (GROUP_01279)
void マイデザを貼る3P_88c2640b3405(CTRPluginFramework::MenuEntry *entry);

// 根性で乗り越える (GROUP_01280)
void 根性で乗り越える_88e9d5a7b9d5(CTRPluginFramework::MenuEntry *entry);

// ウィンドウ (GROUP_01281)
void ウィンドウ_88f39b46919d(CTRPluginFramework::MenuEntry *entry);

// あける (GROUP_01285)
void あける_89b7b9ea168c(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_01289)
void 完成_89f1348b9fe1(CTRPluginFramework::MenuEntry *entry);

// 物を重ねて置ける (GROUP_01295)
void 物を重ねて置ける_8a82c5ef5f8e(CTRPluginFramework::MenuEntry *entry);

// 29 (GROUP_01298)
void Cheat_29_8aefed083624(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01304)
void p_8ba42a91b480(CTRPluginFramework::MenuEntry *entry);

// 恐怖の森 (GROUP_01309)
void 恐怖の森_8bf5cfe6fe05(CTRPluginFramework::MenuEntry *entry);

// 23 (GROUP_01310)
void Cheat_23_8c0581066f64(CTRPluginFramework::MenuEntry *entry);

// 1p (GROUP_01311)
void Cheat_1p_8c0d59bc70d8(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01313)
void 自分に_8c33a435e656(CTRPluginFramework::MenuEntry *entry);

// CLUB444 (GROUP_01315)
void CLUB444_8c47738025e1(CTRPluginFramework::MenuEntry *entry);

// 赤褐色 (GROUP_01318)
void 赤褐色_8ca5f3a8994c(CTRPluginFramework::MenuEntry *entry);

// 2歩いたところが消える (GROUP_01329)
void Cheat_2歩いたところが消える_8d98d432fdb8(CTRPluginFramework::MenuEntry *entry);

// あみ (GROUP_01332)
void あみ_8dc88acdee10(CTRPluginFramework::MenuEntry *entry);

// 駅 (GROUP_01333)
void 駅_8dfed3009f00(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P4 (内) (GROUP_01341)
void Player_Teleporter_P4_内_8ec7a7ee792f(CTRPluginFramework::MenuEntry *entry);

// ピコハン (GROUP_01343)
void ピコハン_8f79fa843a3c(CTRPluginFramework::MenuEntry *entry);

// どこでも家具変更を元に戻す (GROUP_01348)
void どこでも家具変更を元に戻す_8ffc9dbd950b(CTRPluginFramework::MenuEntry *entry);

// 3-4の地形変更 (GROUP_01349)
void Cheat_3_4の地形変更_9025d1f6f136(CTRPluginFramework::MenuEntry *entry);

// あみ (GROUP_01352)
void あみ_903ef7b4a85e(CTRPluginFramework::MenuEntry *entry);

// 青いモダンな屋根 (GROUP_01353)
void 青いモダンな屋根_908df86bb618(CTRPluginFramework::MenuEntry *entry);

// 花 (GROUP_01356)
void 花_90ec710f8e32(CTRPluginFramework::MenuEntry *entry);

// 美容院 (GROUP_01358)
void 美容院_91211d62f05b(CTRPluginFramework::MenuEntry *entry);

// ALL (GROUP_01359)
void ALL_91252a1e3b4b(CTRPluginFramework::MenuEntry *entry);

// スコップで埋める (GROUP_01360)
void スコップで埋める_9147b1cd6d52(CTRPluginFramework::MenuEntry *entry);

// オレンジ (GROUP_01364)
void オレンジ_917ad689f8ed(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01365)
void p_91c9b8e68cd3(CTRPluginFramework::MenuEntry *entry);

// デートなんです (GROUP_01366)
void デートなんです_91fcd2cf4059(CTRPluginFramework::MenuEntry *entry);

// 5 (GROUP_01368)
void Cheat_5_921216b98edc(CTRPluginFramework::MenuEntry *entry);

// しまう (GROUP_01372)
void しまう_92a1f2aec75d(CTRPluginFramework::MenuEntry *entry);

// 役場 (GROUP_01374)
void 役場_92bb0eb866df(CTRPluginFramework::MenuEntry *entry);

// 叩かれる (GROUP_01378)
void 叩かれる_937ea6f38715(CTRPluginFramework::MenuEntry *entry);

// サーバーを日本に変更 (GROUP_01385)
void サーバーを日本に変更_943b81ff04ef(CTRPluginFramework::MenuEntry *entry);

// 王冠 (GROUP_01388)
void 王冠_94ca1a00dd50(CTRPluginFramework::MenuEntry *entry);

// キーボード日本 (GROUP_01389)
void キーボード日本_94f14c9f4a63(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作でドロップ (GROUP_01390)
void 岩壊す動作でドロップ_94f29a9b798c(CTRPluginFramework::MenuEntry *entry);

// 憧れたい (GROUP_01393)
void 憧れたい_952e6c4a0a4f(CTRPluginFramework::MenuEntry *entry);

// 0 (GROUP_01403)
void Cheat_0_9685f67f48a3(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_01404)
void 完成_96b7773be88a(CTRPluginFramework::MenuEntry *entry);

// 15×15マスに変更on (GROUP_01406)
void Cheat_15_15マスに変更on_976411c6eb6f(CTRPluginFramework::MenuEntry *entry);

// 3 (GROUP_01408)
void Cheat_3_9790ab5b1a57(CTRPluginFramework::MenuEntry *entry);

// じっと耐えます (GROUP_01409)
void じっと耐えます_9791fde46cf7(CTRPluginFramework::MenuEntry *entry);

// 5 (GROUP_01416)
void Cheat_5_9805d3b69e88(CTRPluginFramework::MenuEntry *entry);

// ぼさぼさ (GROUP_01418)
void ぼさぼさ_981f4c287a53(CTRPluginFramework::MenuEntry *entry);

// くしゃみ連発 (GROUP_01421)
void くしゃみ連発_98511953d04b(CTRPluginFramework::MenuEntry *entry);

// 着替える (GROUP_01423)
void 着替える_9888b203f5c1(CTRPluginFramework::MenuEntry *entry);

// 地中深くに沈む (GROUP_01424)
void 地中深くに沈む_9891fbbb33f9(CTRPluginFramework::MenuEntry *entry);

// しまう (GROUP_01425)
void しまう_98ac8388260a(CTRPluginFramework::MenuEntry *entry);

// 手を振る (GROUP_01430)
void 手を振る_997d53870428(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_01436)
void 有効_9a0ec63f40d4(CTRPluginFramework::MenuEntry *entry);

// スコップで埋める (GROUP_01439)
void スコップで埋める_9a7f1a8b89aa(CTRPluginFramework::MenuEntry *entry);

// 受け取る (GROUP_01440)
void 受け取る_9a832815d094(CTRPluginFramework::MenuEntry *entry);

// 片づけたい (GROUP_01445)
void 片づけたい_9b0cffdd16a3(CTRPluginFramework::MenuEntry *entry);

// 釣り (GROUP_01446)
void 釣り_9b3b788264b4(CTRPluginFramework::MenuEntry *entry);

// 2-1の地形変更 (GROUP_01447)
void Cheat_2_1の地形変更_9b3bca19c1c1(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01448)
void p_9b42e0622b7d(CTRPluginFramework::MenuEntry *entry);

// 線香花火 (GROUP_01449)
void 線香花火_9b75251d1df4(CTRPluginFramework::MenuEntry *entry);

// 4-4の地形変更 (GROUP_01455)
void Cheat_4_4の地形変更_9bde373555ac(CTRPluginFramework::MenuEntry *entry);

// のむ (GROUP_01463)
void のむ_9c9018bcee5c(CTRPluginFramework::MenuEntry *entry);

// パーティーだよ (GROUP_01470)
void パーティーだよ_9ddaf2b1d169(CTRPluginFramework::MenuEntry *entry);

// 流れ星 (GROUP_01472)
void 流れ星_9e25c57a65ec(CTRPluginFramework::MenuEntry *entry);

// オートドロップ (GROUP_01478)
void オートドロップ_9e8d59886831(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_01479)
void 未完成_9ea605680158(CTRPluginFramework::MenuEntry *entry);

// 7 (GROUP_01480)
void Cheat_7_9ebeebaea72e(CTRPluginFramework::MenuEntry *entry);

// 20 (GROUP_01482)
void Cheat_20_9ef99ef314c7(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01485)
void 自分に_9f5771d9d62c(CTRPluginFramework::MenuEntry *entry);

// CLUB444 (GROUP_01487)
void CLUB444_9f996010101b(CTRPluginFramework::MenuEntry *entry);

// 0 (GROUP_01488)
void Cheat_0_9fc0fac6c60d(CTRPluginFramework::MenuEntry *entry);

// maideza (GROUP_01491)
void maideza_a00fa854b2ce(CTRPluginFramework::MenuEntry *entry);

// オノ跳ね返り (GROUP_01500)
void オノ跳ね返り_a12d6928a9ac(CTRPluginFramework::MenuEntry *entry);

// 足で消してドロップ (GROUP_01504)
void 足で消してドロップ_a1cd0cf361b3(CTRPluginFramework::MenuEntry *entry);

// たんぽぽ (GROUP_01509)
void たんぽぽ_a21161d57729(CTRPluginFramework::MenuEntry *entry);

// 置いても見えない (GROUP_01511)
void 置いても見えない_a22d1877946f(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_01512)
void 濃い青_a242621d1ebb(CTRPluginFramework::MenuEntry *entry);

// frend (GROUP_01513)
void frend_a24fce7b84b3(CTRPluginFramework::MenuEntry *entry);

// 赤褐色 (GROUP_01515)
void 赤褐色_a295c55e4fa9(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01517)
void 座標移動_a2e2df182cff(CTRPluginFramework::MenuEntry *entry);

// 靴屋 (GROUP_01521)
void 靴屋_a30dc1f18a6b(CTRPluginFramework::MenuEntry *entry);

// 憧れたい (GROUP_01523)
void 憧れたい_a364b6ef3ecc(CTRPluginFramework::MenuEntry *entry);

// 連続アクション (GROUP_01524)
void 連続アクション_a36be94d69c2(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01525)
void 座標移動_a376955799d3(CTRPluginFramework::MenuEntry *entry);

// zukan (GROUP_01528)
void zukan_a3c6b3ab1d5b(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_01531)
void 濃い青_a40a12062615(CTRPluginFramework::MenuEntry *entry);

// 潜る (GROUP_01533)
void 潜る_a41de373b125(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01537)
void 自分に_a4664d505648(CTRPluginFramework::MenuEntry *entry);

// 11 (GROUP_01539)
void Cheat_11_a48b450ddc00(CTRPluginFramework::MenuEntry *entry);

// 工事中 (GROUP_01542)
void 工事中_a52105a7cd64(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01544)
void 自分に_a549c83264b9(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_01548)
void 茶色_a62378e3fe97(CTRPluginFramework::MenuEntry *entry);

// 画面が黄色(黒) (GROUP_01550)
void 画面が黄色_黒_a632c7f2852a(CTRPluginFramework::MenuEntry *entry);

// 0 (GROUP_01551)
void Cheat_0_a63db98da3c8(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01553)
void p_a6679e1b145d(CTRPluginFramework::MenuEntry *entry);

// 7 (GROUP_01559)
void Cheat_7_a6db5e414620(CTRPluginFramework::MenuEntry *entry);

// 4-1の地形変更 (GROUP_01561)
void Cheat_4_1の地形変更_a6f21bebe771(CTRPluginFramework::MenuEntry *entry);

// (i)エフェクトID一覧表 <ID=名> (GROUP_01562)
void i_エフェクトID一覧表_ID_名_a6f26992c528(CTRPluginFramework::MenuEntry *entry);

// のむ (GROUP_01564)
void のむ_a7522158033d(CTRPluginFramework::MenuEntry *entry);

// クラシックな交番 (GROUP_01565)
void クラシックな交番_a7570d620919(CTRPluginFramework::MenuEntry *entry);

// 3-3の地形変更 (GROUP_01567)
void Cheat_3_3の地形変更_a79fee675a45(CTRPluginFramework::MenuEntry *entry);

// ドロップ解除 (GROUP_01568)
void ドロップ解除_a7d4a68f6356(CTRPluginFramework::MenuEntry *entry);

// ずっとヤンチャ (GROUP_01569)
void ずっとヤンチャ_a7d6e02428f0(CTRPluginFramework::MenuEntry *entry);

// けだるいゆるさ (GROUP_01571)
void けだるいゆるさ_a7ea8e7bf19d(CTRPluginFramework::MenuEntry *entry);

// 11 (GROUP_01574)
void Cheat_11_a8748b92f4b8(CTRPluginFramework::MenuEntry *entry);

// 商店街 (GROUP_01578)
void 商店街_a8b69c159f20(CTRPluginFramework::MenuEntry *entry);

// フレッシュで (GROUP_01580)
void フレッシュで_a8e4dfb97dec(CTRPluginFramework::MenuEntry *entry);

// 連続アミ振り (GROUP_01582)
void 連続アミ振り_a92159c8fd28(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01583)
void 座標移動_a93670c24662(CTRPluginFramework::MenuEntry *entry);

// 28 (GROUP_01584)
void Cheat_28_a95c8d31e6e5(CTRPluginFramework::MenuEntry *entry);

// 4-2の地形変更 (GROUP_01585)
void Cheat_4_2の地形変更_a95d9d0cdec8(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01587)
void p_a9927e920ec7(CTRPluginFramework::MenuEntry *entry);

// こうご (GROUP_01588)
void こうご_a9d0754ca606(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01589)
void p_a9f3ad9a10ae(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01590)
void p_aa00981ea543(CTRPluginFramework::MenuEntry *entry);

// 2P (GROUP_01594)
void Cheat_2P_aa64018399a7(CTRPluginFramework::MenuEntry *entry);

// シャボン玉 (GROUP_01595)
void シャボン玉_aa84ccd80a90(CTRPluginFramework::MenuEntry *entry);

// ふるさとチケット (GROUP_01596)
void ふるさとチケット_aaac681034a8(CTRPluginFramework::MenuEntry *entry);

// マイデザ (GROUP_01600)
void マイデザ_aaebb7a488fb(CTRPluginFramework::MenuEntry *entry);

// わざとだよ (GROUP_01604)
void わざとだよ_ab0ffb382067(CTRPluginFramework::MenuEntry *entry);

// sakana speed (GROUP_01611)
void sakana_speed_abc23b08b6b4(CTRPluginFramework::MenuEntry *entry);

// 水色 (GROUP_01615)
void 水色_ac328ff1e6ff(CTRPluginFramework::MenuEntry *entry);

// ウィンドウ (GROUP_01616)
void ウィンドウ_ac80d4ed5691(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_01617)
void スネークモーション_室外_ac8df04c2c0c(CTRPluginFramework::MenuEntry *entry);

// 11 (GROUP_01618)
void Cheat_11_ac9e6bb8c1f6(CTRPluginFramework::MenuEntry *entry);

// ワープ (GROUP_01621)
void ワープ_accfb6ebd037(CTRPluginFramework::MenuEntry *entry);

// 掘ってドロップ (GROUP_01622)
void 掘ってドロップ_acd3d76a0e17(CTRPluginFramework::MenuEntry *entry);

// 青色 (GROUP_01630)
void 青色_add0700e92dc(CTRPluginFramework::MenuEntry *entry);

// セーブメニュー出さない (GROUP_01631)
void セーブメニュー出さない_addf1e7bc9e6(CTRPluginFramework::MenuEntry *entry);

// メガホン (GROUP_01633)
void メガホン_ae2c0079f850(CTRPluginFramework::MenuEntry *entry);

// 風車 (GROUP_01634)
void 風車_ae784c72506b(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01636)
void p_ae9d5650261a(CTRPluginFramework::MenuEntry *entry);

// 通常 (GROUP_01637)
void 通常_aeaab521eddb(CTRPluginFramework::MenuEntry *entry);

// 1-3の地形変更 (GROUP_01641)
void Cheat_1_3の地形変更_afa7d5ac6b62(CTRPluginFramework::MenuEntry *entry);

// やったー (GROUP_01642)
void やったー_b003663c46fb(CTRPluginFramework::MenuEntry *entry);

// maideza (GROUP_01643)
void maideza_b064098e16c3(CTRPluginFramework::MenuEntry *entry);

// テクスチャ変更 (GROUP_01644)
void テクスチャ変更_b09e122ff320(CTRPluginFramework::MenuEntry *entry);

// アイテム全て卵判定 (GROUP_01645)
void アイテム全て卵判定_b0cd1af4a992(CTRPluginFramework::MenuEntry *entry);

// パチンコ (GROUP_01646)
void パチンコ_b0e1f5f2af78(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_01647)
void 未完成_b114917db3c3(CTRPluginFramework::MenuEntry *entry);

// kuko 2 (GROUP_01650)
void kuko_2_b1662af823c5(CTRPluginFramework::MenuEntry *entry);

// 4-3の地形変更 (GROUP_01651)
void Cheat_4_3の地形変更_b17176840c4c(CTRPluginFramework::MenuEntry *entry);

// 埋めるときの動作2P (GROUP_01652)
void 埋めるときの動作2P_b1738e8f1998(CTRPluginFramework::MenuEntry *entry);

// デパート (GROUP_01653)
void デパート_b17fe9f54370(CTRPluginFramework::MenuEntry *entry);

// ばばあ (GROUP_01654)
void ばばあ_b1995532d4e4(CTRPluginFramework::MenuEntry *entry);

// zukan (GROUP_01655)
void zukan_b19e949b4156(CTRPluginFramework::MenuEntry *entry);

// 埋まってドロップ (GROUP_01664)
void 埋まってドロップ_b378d90b4430(CTRPluginFramework::MenuEntry *entry);

// 埋めるときの動作1P (GROUP_01665)
void 埋めるときの動作1P_b3915fc97979(CTRPluginFramework::MenuEntry *entry);

// キツネロ商店 (GROUP_01666)
void キツネロ商店_b398c87c8bd0(CTRPluginFramework::MenuEntry *entry);

// 網 (GROUP_01667)
void 網_b3a679d94475(CTRPluginFramework::MenuEntry *entry);

// ALL (GROUP_01670)
void ALL_b3f77e19c5d6(CTRPluginFramework::MenuEntry *entry);

// 水色 (GROUP_01671)
void 水色_b41dfc940438(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_01672)
void 完成_b4356c605e4e(CTRPluginFramework::MenuEntry *entry);

// 3-4の地形変更 (GROUP_01676)
void Cheat_3_4の地形変更_b479199c2134(CTRPluginFramework::MenuEntry *entry);

// 2 (GROUP_01678)
void Cheat_2_b4a4ae281041(CTRPluginFramework::MenuEntry *entry);

// 傘動作 (GROUP_01681)
void 傘動作_b4cd10dd18f4(CTRPluginFramework::MenuEntry *entry);

// やめるのみ (GROUP_01682)
void やめるのみ_b4d3f755b8e1(CTRPluginFramework::MenuEntry *entry);

// 手を振る (GROUP_01684)
void 手を振る_b54aee71d01b(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01694)
void 座標移動_b65fa9efd6c8(CTRPluginFramework::MenuEntry *entry);

// 1-3の地形変更 (GROUP_01696)
void Cheat_1_3の地形変更_b68b0ee571e5(CTRPluginFramework::MenuEntry *entry);

// 黒 (GROUP_01699)
void 黒_b726e849bef0(CTRPluginFramework::MenuEntry *entry);

// アイテム置ける範囲を広くする(15×15) (GROUP_01700)
void アイテム置ける範囲を広くする_15_15_b74141a85d57(CTRPluginFramework::MenuEntry *entry);

// 日本 (GROUP_01703)
void 日本_b74e9b9818ee(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作でドロップ (GROUP_01704)
void 岩壊す動作でドロップ_b75ad7cc201a(CTRPluginFramework::MenuEntry *entry);

// 金 (GROUP_01705)
void 金_b7630ed0419a(CTRPluginFramework::MenuEntry *entry);

// アクション連発 (GROUP_01712)
void アクション連発_b859472568a0(CTRPluginFramework::MenuEntry *entry);

// 18 (GROUP_01713)
void Cheat_18_b8a22df8595f(CTRPluginFramework::MenuEntry *entry);

// Rでかっぱ着替え動作 (GROUP_01714)
void Rでかっぱ着替え動作_b8a49221a5c4(CTRPluginFramework::MenuEntry *entry);

// 前転 (GROUP_01715)
void 前転_b8a9d57790bc(CTRPluginFramework::MenuEntry *entry);

// 3 (GROUP_01717)
void Cheat_3_b8dd53dd22f4(CTRPluginFramework::MenuEntry *entry);

// スコップ (GROUP_01718)
void スコップ_b910b2efa0d4(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01719)
void p_b921647617e9(CTRPluginFramework::MenuEntry *entry);

// 9 (GROUP_01721)
void Cheat_9_b93d623de867(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_01724)
void Cheat_1_b9d4cbe2db31(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01730)
void p_ba35c227e9ea(CTRPluginFramework::MenuEntry *entry);

// P1判定(ホスト)OFF (GROUP_01733)
void P1判定_ホスト_OFF_ba6595dc4dc0(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01738)
void 座標移動_bb38f88272dd(CTRPluginFramework::MenuEntry *entry);

// 空気イス (GROUP_01742)
void 空気イス_bb6c1af211f4(CTRPluginFramework::MenuEntry *entry);

// パチンコ (GROUP_01746)
void パチンコ_bbbeb447a43e(CTRPluginFramework::MenuEntry *entry);

// ブラジル (GROUP_01749)
void ブラジル_bbfb040bc320(CTRPluginFramework::MenuEntry *entry);

// メガホン (GROUP_01750)
void メガホン_bc12368c6ca4(CTRPluginFramework::MenuEntry *entry);

// ハッケミィのテント (GROUP_01752)
void ハッケミィのテント_bc3fd1daffca(CTRPluginFramework::MenuEntry *entry);

// 2-2の地形変更 (GROUP_01754)
void Cheat_2_2の地形変更_bc65d27d3d98(CTRPluginFramework::MenuEntry *entry);

// 30 (GROUP_01763)
void Cheat_30_be07b0844485(CTRPluginFramework::MenuEntry *entry);

// Bury (GROUP_01764)
void Bury_be255ca8fb85(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01768)
void 座標移動_be692d920ce1(CTRPluginFramework::MenuEntry *entry);

// アメリカ (GROUP_01770)
void アメリカ_beb2ad203be3(CTRPluginFramework::MenuEntry *entry);

// 食べる (GROUP_01771)
void 食べる_beb948a4f929(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01774)
void p_bf4fb9d2f0be(CTRPluginFramework::MenuEntry *entry);

// 水色 (GROUP_01776)
void 水色_bf6679edc827(CTRPluginFramework::MenuEntry *entry);

// 赤 (GROUP_01779)
void 赤_bfc5547f9e8f(CTRPluginFramework::MenuEntry *entry);

// 商品変更1 (GROUP_01780)
void 商品変更1_bfdd371320cc(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01783)
void 自分に_c01334583b6e(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01784)
void p_c0138546fcb4(CTRPluginFramework::MenuEntry *entry);

// デパート2階 (GROUP_01786)
void デパート2階_c060a0d1228b(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P3 (内) (GROUP_01794)
void Player_Teleporter_P3_内_c123f40ae16c(CTRPluginFramework::MenuEntry *entry);

// 片づけたい (GROUP_01795)
void 片づけたい_c14267757966(CTRPluginFramework::MenuEntry *entry);

// クラッカー (GROUP_01801)
void クラッカー_c1da081ec190(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01802)
void 自分に_c1dbfb3a5383(CTRPluginFramework::MenuEntry *entry);

// Off (GROUP_01803)
void Off_c1e07a39c38e(CTRPluginFramework::MenuEntry *entry);

// ピンク (GROUP_01804)
void ピンク_c1fb0606ff54(CTRPluginFramework::MenuEntry *entry);

// ジョウロ (GROUP_01805)
void ジョウロ_c20a0be28294(CTRPluginFramework::MenuEntry *entry);

// みせびらかす (GROUP_01806)
void みせびらかす_c20a27a55c6d(CTRPluginFramework::MenuEntry *entry);

// 泣き虫 (GROUP_01807)
void 泣き虫_c20a51d3aad2(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01808)
void 座標移動_c22b1c9572f5(CTRPluginFramework::MenuEntry *entry);

// オフ (GROUP_01809)
void オフ_c237deb0b174(CTRPluginFramework::MenuEntry *entry);

// Player Teleporter P2 (外) (GROUP_01810)
void Player_Teleporter_P2_外_c25d526ffc7b(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量250 (GROUP_01814)
void 紙吹雪量250_c2d5c44c64f0(CTRPluginFramework::MenuEntry *entry);

// いつかは落ち着く (GROUP_01816)
void いつかは落ち着く_c2eee62ee629(CTRPluginFramework::MenuEntry *entry);

// frend (GROUP_01817)
void frend_c31d9ad03b5d(CTRPluginFramework::MenuEntry *entry);

// デパート2階 (GROUP_01818)
void デパート2階_c345ea61ba89(CTRPluginFramework::MenuEntry *entry);

// nottori (GROUP_01819)
void nottori_c34c076a3090(CTRPluginFramework::MenuEntry *entry);

// 青色 (GROUP_01820)
void 青色_c3d005572065(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01821)
void p_c3e6c0b777cd(CTRPluginFramework::MenuEntry *entry);

// 3-2の地形変更 (GROUP_01822)
void Cheat_3_2の地形変更_c40888404721(CTRPluginFramework::MenuEntry *entry);

// Rでかっぱ着替え動作 (GROUP_01824)
void Rでかっぱ着替え動作_c422c12eb922(CTRPluginFramework::MenuEntry *entry);

// 傘 (GROUP_01828)
void 傘_c4bc23e7552c(CTRPluginFramework::MenuEntry *entry);

// Drop (GROUP_01831)
void Drop_c55267848644(CTRPluginFramework::MenuEntry *entry);

// オノ (GROUP_01833)
void オノ_c5873ed9384f(CTRPluginFramework::MenuEntry *entry);

// 釣り (GROUP_01834)
void 釣り_c59a78a8ce9a(CTRPluginFramework::MenuEntry *entry);

// 4 (GROUP_01836)
void Cheat_4_c5af246622ec(CTRPluginFramework::MenuEntry *entry);

// 工事中 (GROUP_01838)
void 工事中_c5cf2cb49583(CTRPluginFramework::MenuEntry *entry);

// 赤バラ見せびらかす (GROUP_01841)
void 赤バラ見せびらかす_c616a3436387(CTRPluginFramework::MenuEntry *entry);

// 13 (GROUP_01842)
void Cheat_13_c621f4e8c630(CTRPluginFramework::MenuEntry *entry);

// 赤褐色 (GROUP_01844)
void 赤褐色_c694ab3338ee(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01847)
void p_c716115f81fb(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01849)
void p_c71748e51514(CTRPluginFramework::MenuEntry *entry);

// 18 (GROUP_01850)
void Cheat_18_c733b94b48fa(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01853)
void 自分に_c772fce3b96b(CTRPluginFramework::MenuEntry *entry);

// 1P (GROUP_01855)
void Cheat_1P_c79374d13193(CTRPluginFramework::MenuEntry *entry);

// 薄い紫 (GROUP_01857)
void 薄い紫_c7ba64c5d844(CTRPluginFramework::MenuEntry *entry);

// 起き上がる (GROUP_01858)
void 起き上がる_c7d62c3a4188(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01861)
void p_c8588049e10a(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01862)
void 座標移動_c85959f661e9(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01863)
void 自分に_c8738a9be7fe(CTRPluginFramework::MenuEntry *entry);

// 豆まき (GROUP_01866)
void 豆まき_c8a43044eaa2(CTRPluginFramework::MenuEntry *entry);

// 2 (GROUP_01870)
void Cheat_2_c92675d57b6e(CTRPluginFramework::MenuEntry *entry);

// 置いたものが置き花火になる (GROUP_01871)
void 置いたものが置き花火になる_c97392526a1f(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_01872)
void 緑_c9a76dd5487f(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_01883)
void 濃い青_cab52db54ac3(CTRPluginFramework::MenuEntry *entry);

// 連続気絶 (GROUP_01884)
void 連続気絶_cac85a029eb9(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01885)
void p_caded20bfdb3(CTRPluginFramework::MenuEntry *entry);

// 乗っ取り (GROUP_01886)
void 乗っ取り_caeca0423e13(CTRPluginFramework::MenuEntry *entry);

// 1-1の地形変更 (GROUP_01887)
void Cheat_1_1の地形変更_cb3a9ceb572b(CTRPluginFramework::MenuEntry *entry);

// いつかは落ち着く (GROUP_01888)
void いつかは落ち着く_cb476578ed33(CTRPluginFramework::MenuEntry *entry);

// Bury (GROUP_01890)
void Bury_cbad1596b135(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01891)
void 座標移動_cbb35eccfb3e(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_01892)
void 座標移動_cbbc710b11f9(CTRPluginFramework::MenuEntry *entry);

// 穴に落ちない (GROUP_01894)
void 穴に落ちない_cbd3a4139e14(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01896)
void 自分に_cc1887eb0a2a(CTRPluginFramework::MenuEntry *entry);

// 6 (GROUP_01897)
void Cheat_6_cc39cff5c913(CTRPluginFramework::MenuEntry *entry);

// 26 (GROUP_01898)
void Cheat_26_cc45cc21f739(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_01899)
void 未完成_cc7d77296c2d(CTRPluginFramework::MenuEntry *entry);

// ばばあ (GROUP_01902)
void ばばあ_cd7bcad5a979(CTRPluginFramework::MenuEntry *entry);

// 恐怖の森 (GROUP_01907)
void 恐怖の森_ce4c8caf27cd(CTRPluginFramework::MenuEntry *entry);

// 濃い緑 (GROUP_01908)
void 濃い緑_ceaef5c73398(CTRPluginFramework::MenuEntry *entry);

// 1-2の地形変更 (GROUP_01912)
void Cheat_1_2の地形変更_cf1022a35b80(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01915)
void p_cf6ab4acff71(CTRPluginFramework::MenuEntry *entry);

// ピンク (GROUP_01916)
void ピンク_cf6c8fbe97d9(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01917)
void p_cf88761f252c(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01918)
void 自分に_cf9707518b08(CTRPluginFramework::MenuEntry *entry);

// 5 (GROUP_01920)
void Cheat_5_d01b2e4e9f52(CTRPluginFramework::MenuEntry *entry);

// 立ち寝 (GROUP_01922)
void 立ち寝_d046fd0d587a(CTRPluginFramework::MenuEntry *entry);

// kaijo (GROUP_01923)
void kaijo_d047cef495ad(CTRPluginFramework::MenuEntry *entry);

// スクショ無効 (GROUP_01924)
void スクショ無効_d082f1495f4b(CTRPluginFramework::MenuEntry *entry);

// nottori (GROUP_01925)
void nottori_d0aec62ab713(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01926)
void p_d0b4c0646950(CTRPluginFramework::MenuEntry *entry);

// じめんにうめる (GROUP_01927)
void じめんにうめる_d0cd0abc830e(CTRPluginFramework::MenuEntry *entry);

// 2-1の地形変更 (GROUP_01930)
void Cheat_2_1の地形変更_d0fd5a8f4cd1(CTRPluginFramework::MenuEntry *entry);

// ずっとヤンチャ (GROUP_01932)
void ずっとヤンチャ_d11d3fb90a65(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01936)
void p_d162968e66f5(CTRPluginFramework::MenuEntry *entry);

// ピコハン (GROUP_01937)
void ピコハン_d188aadbd5a2(CTRPluginFramework::MenuEntry *entry);

// スタイリングする (GROUP_01938)
void スタイリングする_d19ebe0016af(CTRPluginFramework::MenuEntry *entry);

// 改行 (GROUP_01939)
void 改行_d1b1b8c46366(CTRPluginFramework::MenuEntry *entry);

// 商品変更1 (GROUP_01940)
void 商品変更1_d2249a913dd1(CTRPluginFramework::MenuEntry *entry);

// 受付かっぱ (GROUP_01941)
void 受付かっぱ_d228f1911993(CTRPluginFramework::MenuEntry *entry);

// 2P (GROUP_01944)
void Cheat_2P_d241f70d5f8a(CTRPluginFramework::MenuEntry *entry);

// 3 (GROUP_01945)
void Cheat_3_d243e3f0f9fd(CTRPluginFramework::MenuEntry *entry);

// オノを壊す (GROUP_01948)
void オノを壊す_d2886e13ca88(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01950)
void p_d2a29bfbdce6(CTRPluginFramework::MenuEntry *entry);

// neta (GROUP_01951)
void neta_d2cccc9742bc(CTRPluginFramework::MenuEntry *entry);

// 揺らしてドロップ (GROUP_01952)
void 揺らしてドロップ_d2e9a0a5ad1a(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室内 (GROUP_01954)
void スネークモーション_室内_d31498f9a7f7(CTRPluginFramework::MenuEntry *entry);

// 28 (GROUP_01955)
void Cheat_28_d34e3d6dc45a(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_01960)
void スネークモーション_室外_d3a8efefb932(CTRPluginFramework::MenuEntry *entry);

// 釣竿を引き戻す (GROUP_01961)
void 釣竿を引き戻す_d3b38f47d5cf(CTRPluginFramework::MenuEntry *entry);

// 誰も寄せつけたくない (GROUP_01963)
void 誰も寄せつけたくない_d3eb4a24bd9e(CTRPluginFramework::MenuEntry *entry);

// NPC 消える (GROUP_01964)
void NPC_消える_d3edc477e515(CTRPluginFramework::MenuEntry *entry);

// シナモロール (GROUP_01965)
void シナモロール_d3f3ea40db64(CTRPluginFramework::MenuEntry *entry);

// 泳ぐ (GROUP_01968)
void 泳ぐ_d49eb0de589c(CTRPluginFramework::MenuEntry *entry);

// マイデザでドロップ (GROUP_01970)
void マイデザでドロップ_d4cd28932e84(CTRPluginFramework::MenuEntry *entry);

// 画面が赤 (GROUP_01971)
void 画面が赤_d4e541a0b35f(CTRPluginFramework::MenuEntry *entry);

// 薄い紫 (GROUP_01974)
void 薄い紫_d550e2403a3e(CTRPluginFramework::MenuEntry *entry);

// 無効 (GROUP_01975)
void 無効_d55cf1904804(CTRPluginFramework::MenuEntry *entry);

// 掘って岩のエフェクトが出てドロップ (GROUP_01976)
void 掘って岩のエフェクトが出てドロップ_d5731411e8ae(CTRPluginFramework::MenuEntry *entry);

// 4 (GROUP_01978)
void Cheat_4_d5816e14c5c1(CTRPluginFramework::MenuEntry *entry);

// くしゃみ連発 (GROUP_01979)
void くしゃみ連発_d5b1a8f4c752(CTRPluginFramework::MenuEntry *entry);

// 4p (GROUP_01980)
void Cheat_4p_d5c42728ad2a(CTRPluginFramework::MenuEntry *entry);

// 傘 (GROUP_01983)
void 傘_d5ffdcf981ad(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01984)
void p_d61b1c840a93(CTRPluginFramework::MenuEntry *entry);

// 海の中でも歩く (GROUP_01987)
void 海の中でも歩く_d6cdd378ac0a(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_01989)
void 自分に_d6e915137207(CTRPluginFramework::MenuEntry *entry);

// わざとだよ (GROUP_01994)
void わざとだよ_d772ebbbe6e0(CTRPluginFramework::MenuEntry *entry);

// 8 (GROUP_01997)
void Cheat_8_d7aa88207bcb(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_01999)
void p_d7ea78991a3f(CTRPluginFramework::MenuEntry *entry);

// 掘って岩のエフェクトが出てドロップ (GROUP_02005)
void 掘って岩のエフェクトが出てドロップ_d87dd7717ea1(CTRPluginFramework::MenuEntry *entry);

// 地上にする (GROUP_02009)
void 地上にする_d919d45356f3(CTRPluginFramework::MenuEntry *entry);

// 前転 (GROUP_02010)
void 前転_d92963c3d861(CTRPluginFramework::MenuEntry *entry);

// アメリカ (GROUP_02011)
void アメリカ_d96183304de0(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02014)
void 自分に_d98d0cfce817(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_02016)
void 未完成_da0cb2e98fe4(CTRPluginFramework::MenuEntry *entry);

// 11 (GROUP_02017)
void Cheat_11_da1032f4cee7(CTRPluginFramework::MenuEntry *entry);

// ブレーキ (GROUP_02018)
void ブレーキ_da370863ea04(CTRPluginFramework::MenuEntry *entry);

// *れいん* (GROUP_02020)
void れいん_da9398d7b519(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02023)
void p_db059f9ce3dc(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02024)
void 座標移動_db12ef681100(CTRPluginFramework::MenuEntry *entry);

// 2p (GROUP_02027)
void Cheat_2p_db316b9ce13f(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02028)
void 座標移動_db36ca2b3036(CTRPluginFramework::MenuEntry *entry);

// ピンク (GROUP_02029)
void ピンク_db466a82fd68(CTRPluginFramework::MenuEntry *entry);

// 緑 (GROUP_02030)
void 緑_db4fc396a230(CTRPluginFramework::MenuEntry *entry);

// テント (GROUP_02039)
void テント_dc0fe236f9fc(CTRPluginFramework::MenuEntry *entry);

// 足で消してドロップ (GROUP_02042)
void 足で消してドロップ_dc2fedbf3f31(CTRPluginFramework::MenuEntry *entry);

// マイデザを貼る2P (GROUP_02044)
void マイデザを貼る2P_dc3ef6aa3be1(CTRPluginFramework::MenuEntry *entry);

// 靴屋 (GROUP_02047)
void 靴屋_dc78fd8e7478(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02048)
void p_dc8e56fae983(CTRPluginFramework::MenuEntry *entry);

// カナダ (GROUP_02051)
void カナダ_dccca3dd44d7(CTRPluginFramework::MenuEntry *entry);

// 連続流れ星 (GROUP_02053)
void 連続流れ星_dcdff0f68fbe(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_02054)
void 有効_dce12cfee9c0(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_02055)
void Cheat_1_dce55b3160bb(CTRPluginFramework::MenuEntry *entry);

// 元に戻す (GROUP_02056)
void 元に戻す_dced76fb261d(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02059)
void p_dd21dad402eb(CTRPluginFramework::MenuEntry *entry);

// 潜る (GROUP_02062)
void 潜る_dd3e7f98820f(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02063)
void 自分に_dd4da80c29f3(CTRPluginFramework::MenuEntry *entry);

// 島室外 (GROUP_02064)
void 島室外_ddd4d5676393(CTRPluginFramework::MenuEntry *entry);

// 2 (GROUP_02067)
void Cheat_2_ddfc7d27df31(CTRPluginFramework::MenuEntry *entry);

// 潜る1 (GROUP_02068)
void 潜る1_de5ca0693d59(CTRPluginFramework::MenuEntry *entry);

// スタイリングする (GROUP_02070)
void スタイリングする_de84da957406(CTRPluginFramework::MenuEntry *entry);

// neta (GROUP_02071)
void neta_de90dae6277d(CTRPluginFramework::MenuEntry *entry);

// 潜る (GROUP_02072)
void 潜る_deb15d7d4746(CTRPluginFramework::MenuEntry *entry);

// 25 (GROUP_02073)
void Cheat_25_deb7de154a04(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02077)
void 座標移動_df25db842c15(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02080)
void p_df6985af0b28(CTRPluginFramework::MenuEntry *entry);

// 未完成 (GROUP_02083)
void 未完成_dfc9f4575bec(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02084)
void 自分に_dfd928870e11(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室内 (GROUP_02085)
void スネークモーション_室内_dff457edd629(CTRPluginFramework::MenuEntry *entry);

// じっと耐えます (GROUP_02086)
void じっと耐えます_dff5ef087560(CTRPluginFramework::MenuEntry *entry);

// 置く (GROUP_02087)
void 置く_e03e8db695e3(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_02088)
void Cheat_1_e0415dc8b905(CTRPluginFramework::MenuEntry *entry);

// 埋まってドロップ (GROUP_02090)
void 埋まってドロップ_e06c33219aec(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02095)
void 座標移動_e1257a333921(CTRPluginFramework::MenuEntry *entry);

// おサイフにしまう (GROUP_02097)
void おサイフにしまう_e19711da382d(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02101)
void 座標移動_e20803661b7f(CTRPluginFramework::MenuEntry *entry);

// 立ち泳ぎ (GROUP_02102)
void 立ち泳ぎ_e26324fe2b4c(CTRPluginFramework::MenuEntry *entry);

// 村 (GROUP_02104)
void 村_e2b552211a2e(CTRPluginFramework::MenuEntry *entry);

// 物を置く P2 (GROUP_02112)
void 物を置く_P2_e3cea2aee0ac(CTRPluginFramework::MenuEntry *entry);

// オレンジ (GROUP_02113)
void オレンジ_e3fe03510d8d(CTRPluginFramework::MenuEntry *entry);

// 3-2の地形変更 (GROUP_02116)
void Cheat_3_2の地形変更_e415dac64f11(CTRPluginFramework::MenuEntry *entry);

// デパート1階 (GROUP_02117)
void デパート1階_e43ac0e931cb(CTRPluginFramework::MenuEntry *entry);

// 3p (GROUP_02119)
void Cheat_3p_e4531d3306d5(CTRPluginFramework::MenuEntry *entry);

// 黒色 (GROUP_02120)
void 黒色_e45f9f0c6248(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02122)
void p_e4b8c147df85(CTRPluginFramework::MenuEntry *entry);

// ジョウロ (GROUP_02129)
void ジョウロ_e52c9d07483f(CTRPluginFramework::MenuEntry *entry);

// 1p (GROUP_02132)
void Cheat_1p_e549c7fc0719(CTRPluginFramework::MenuEntry *entry);

// 連続でクラゲに刺される動作 (GROUP_02135)
void 連続でクラゲに刺される動作_e590fa87b8b0(CTRPluginFramework::MenuEntry *entry);

// 有効 (GROUP_02136)
void 有効_e599ac8e822e(CTRPluginFramework::MenuEntry *entry);

// 時雨 (GROUP_02138)
void 時雨_e5b8602350f8(CTRPluginFramework::MenuEntry *entry);

// 3-1の地形変更 (GROUP_02141)
void Cheat_3_1の地形変更_e5e72bfa4402(CTRPluginFramework::MenuEntry *entry);

// フランス (GROUP_02142)
void フランス_e5e7435a99d3(CTRPluginFramework::MenuEntry *entry);

// オレンジ (GROUP_02143)
void オレンジ_e5eb6a1e807c(CTRPluginFramework::MenuEntry *entry);

// 韓国 (GROUP_02144)
void 韓国_e5f866fd557d(CTRPluginFramework::MenuEntry *entry);

// 止まると動きがフリーズ (GROUP_02145)
void 止まると動きがフリーズ_e611d7209693(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02147)
void p_e647a333c3c6(CTRPluginFramework::MenuEntry *entry);

// チャットで何も打たないで送信できる (GROUP_02151)
void チャットで何も打たないで送信できる_e662d8bc052a(CTRPluginFramework::MenuEntry *entry);

// 6 (GROUP_02157)
void Cheat_6_e6db10671037(CTRPluginFramework::MenuEntry *entry);

// 風船 (GROUP_02160)
void 風船_e727ca4a7cb2(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02166)
void 自分に_e7f63ee873dd(CTRPluginFramework::MenuEntry *entry);

// ALL (GROUP_02170)
void ALL_e84af54bdbf5(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02172)
void p_e88837c289fb(CTRPluginFramework::MenuEntry *entry);

// 大富豪 (GROUP_02173)
void 大富豪_e8937f835b7e(CTRPluginFramework::MenuEntry *entry);

// 青いモダンな屋根 (GROUP_02177)
void 青いモダンな屋根_e9070df8847d(CTRPluginFramework::MenuEntry *entry);

// 4-2の地形変更 (GROUP_02178)
void Cheat_4_2の地形変更_e91d4c2b901f(CTRPluginFramework::MenuEntry *entry);

// 16 (GROUP_02179)
void Cheat_16_e934cfb609a2(CTRPluginFramework::MenuEntry *entry);

// 線香花火 (GROUP_02181)
void 線香花火_e97d3bc46414(CTRPluginFramework::MenuEntry *entry);

// 自然が一番 (GROUP_02185)
void 自然が一番_e9f2c3a69547(CTRPluginFramework::MenuEntry *entry);

// ピコハン (GROUP_02189)
void ピコハン_ea2fdb8c4a67(CTRPluginFramework::MenuEntry *entry);

// 物を置く P3 (GROUP_02192)
void 物を置く_P3_eab7d479a915(CTRPluginFramework::MenuEntry *entry);

// 起き上がる (GROUP_02195)
void 起き上がる_eb13d328177f(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02197)
void 自分に_eb81d60f915b(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02198)
void p_eb877e7a30f6(CTRPluginFramework::MenuEntry *entry);

// どこでも泳げる (GROUP_02200)
void どこでも泳げる_ebb35921b57f(CTRPluginFramework::MenuEntry *entry);

// 無効 (GROUP_02202)
void 無効_ebfdbc7faa41(CTRPluginFramework::MenuEntry *entry);

// 連続前転 (GROUP_02206)
void 連続前転_ec2bd069cd67(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02209)
void p_ec6b0c2261b1(CTRPluginFramework::MenuEntry *entry);

// 1-3の地形変更 (GROUP_02210)
void Cheat_1_3の地形変更_ec8d351376a1(CTRPluginFramework::MenuEntry *entry);

// 6 (GROUP_02212)
void Cheat_6_ecb374e82e1a(CTRPluginFramework::MenuEntry *entry);

// ワープ (GROUP_02217)
void ワープ_edc1cf90781c(CTRPluginFramework::MenuEntry *entry);

// 座り寝 (GROUP_02224)
void 座り寝_ee91bc10cd37(CTRPluginFramework::MenuEntry *entry);

// 4-3の地形変更 (GROUP_02228)
void Cheat_4_3の地形変更_ef0e83d7d10d(CTRPluginFramework::MenuEntry *entry);

// 唾を吐く (GROUP_02230)
void 唾を吐く_ef2b52a01d54(CTRPluginFramework::MenuEntry *entry);

// 工事中 (GROUP_02234)
void 工事中_eff3a283ca8c(CTRPluginFramework::MenuEntry *entry);

// 座標移動 (GROUP_02235)
void 座標移動_eff6001c477c(CTRPluginFramework::MenuEntry *entry);

// 10 (GROUP_02236)
void Cheat_10_effcf753de96(CTRPluginFramework::MenuEntry *entry);

// 寝る (GROUP_02240)
void 寝る_f0600d443f22(CTRPluginFramework::MenuEntry *entry);

// わざとだよ (GROUP_02245)
void わざとだよ_f0894dcb9b12(CTRPluginFramework::MenuEntry *entry);

// パチンコ (GROUP_02246)
void パチンコ_f0d4eb64ffce(CTRPluginFramework::MenuEntry *entry);

// 何でもスライド操作で置ける (GROUP_02248)
void 何でもスライド操作で置ける_f0e3df7d2939(CTRPluginFramework::MenuEntry *entry);

// フレッシュで (GROUP_02249)
void フレッシュで_f142e60d8855(CTRPluginFramework::MenuEntry *entry);

// 8 (GROUP_02250)
void Cheat_8_f14bb3ae50d2(CTRPluginFramework::MenuEntry *entry);

// 4 (GROUP_02253)
void Cheat_4_f1895be033e6(CTRPluginFramework::MenuEntry *entry);

// 黄緑 (GROUP_02257)
void 黄緑_f20ada3f59ef(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_02260)
void Cheat_1_f239f1e56c09(CTRPluginFramework::MenuEntry *entry);

// 4-3の地形変更 (GROUP_02261)
void Cheat_4_3の地形変更_f2405c969e9c(CTRPluginFramework::MenuEntry *entry);

// ツアータイム無限 (GROUP_02262)
void ツアータイム無限_f25a0f38dd11(CTRPluginFramework::MenuEntry *entry);

// ガーリーなゆるさ (GROUP_02264)
void ガーリーなゆるさ_f294793e401c(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02268)
void p_f3032e28704d(CTRPluginFramework::MenuEntry *entry);

// オートドロップ (GROUP_02274)
void オートドロップ_f3e1517bbc65(CTRPluginFramework::MenuEntry *entry);

// スネークモーション 室外 (GROUP_02275)
void スネークモーション_室外_f416cc04f00c(CTRPluginFramework::MenuEntry *entry);

// 埋めるときの動作4P (GROUP_02276)
void 埋めるときの動作4P_f42b768192de(CTRPluginFramework::MenuEntry *entry);

// もの渡す (GROUP_02279)
void もの渡す_f46588d55a1f(CTRPluginFramework::MenuEntry *entry);

// 潜る2 (GROUP_02282)
void 潜る2_f48782d49370(CTRPluginFramework::MenuEntry *entry);

// 置いても見えない (GROUP_02286)
void 置いても見えない_f4d13265bf3f(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02287)
void 自分に_f4f0c052dd3a(CTRPluginFramework::MenuEntry *entry);

// 濃い青 (GROUP_02291)
void 濃い青_f50e02f58dc7(CTRPluginFramework::MenuEntry *entry);

// 釣竿を引き戻す (GROUP_02292)
void 釣竿を引き戻す_f5118a0d0b49(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02293)
void p_f55f5f757fdc(CTRPluginFramework::MenuEntry *entry);

// 1-1の地形変更 (GROUP_02295)
void Cheat_1_1の地形変更_f59a6933ca94(CTRPluginFramework::MenuEntry *entry);

// 31 (GROUP_02299)
void Cheat_31_f6072bdb57cf(CTRPluginFramework::MenuEntry *entry);

// アッシュブラウン (GROUP_02309)
void アッシュブラウン_f6e9f7cc0d3c(CTRPluginFramework::MenuEntry *entry);

// メガホン (GROUP_02311)
void メガホン_f72b2467b064(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02313)
void p_f75a26ff1f02(CTRPluginFramework::MenuEntry *entry);

// ジョウロ (GROUP_02316)
void ジョウロ_f7734beecc71(CTRPluginFramework::MenuEntry *entry);

// アクセサリーショップ (GROUP_02317)
void アクセサリーショップ_f7a40816eca2(CTRPluginFramework::MenuEntry *entry);

// 完成 (GROUP_02322)
void 完成_f82bbcd78769(CTRPluginFramework::MenuEntry *entry);

// 4P (GROUP_02325)
void Cheat_4P_f85258fdf6ed(CTRPluginFramework::MenuEntry *entry);

// 海から出る (GROUP_02326)
void 海から出る_f89387030ea6(CTRPluginFramework::MenuEntry *entry);

// sakana speed (GROUP_02327)
void sakana_speed_f89dbbbbdebc(CTRPluginFramework::MenuEntry *entry);

// ワープ (GROUP_02329)
void ワープ_f8b9f6907ac9(CTRPluginFramework::MenuEntry *entry);

// ドア (GROUP_02330)
void ドア_f8c16e500350(CTRPluginFramework::MenuEntry *entry);

// chat (GROUP_02337)
void chat_f9a5bf219ba1(CTRPluginFramework::MenuEntry *entry);

// 3P (GROUP_02341)
void Cheat_3P_f9e891a9e618(CTRPluginFramework::MenuEntry *entry);

// 7 (GROUP_02342)
void Cheat_7_f9f508587dba(CTRPluginFramework::MenuEntry *entry);

// ぼさぼさ (GROUP_02348)
void ぼさぼさ_faedeefb047f(CTRPluginFramework::MenuEntry *entry);

// 気絶 (GROUP_02349)
void 気絶_fb416b90c97d(CTRPluginFramework::MenuEntry *entry);

// 風船 (GROUP_02352)
void 風船_fb5ff1b7b512(CTRPluginFramework::MenuEntry *entry);

// 茶色 (GROUP_02354)
void 茶色_fb9350df94a9(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02358)
void 自分に_fc032f3b29fb(CTRPluginFramework::MenuEntry *entry);

// クラッカー (GROUP_02359)
void クラッカー_fc03922459d2(CTRPluginFramework::MenuEntry *entry);

// オフ (GROUP_02360)
void オフ_fc1130d09277(CTRPluginFramework::MenuEntry *entry);

// 21 (GROUP_02363)
void Cheat_21_fc46559111bd(CTRPluginFramework::MenuEntry *entry);

// 園芸店 (GROUP_02364)
void 園芸店_fc5803705fc0(CTRPluginFramework::MenuEntry *entry);

// 9 (GROUP_02365)
void Cheat_9_fc72a701892f(CTRPluginFramework::MenuEntry *entry);

// 1 (GROUP_02366)
void Cheat_1_fc902090edfe(CTRPluginFramework::MenuEntry *entry);

// 31 (GROUP_02369)
void Cheat_31_fca97ba92fa8(CTRPluginFramework::MenuEntry *entry);

// 全バッジ金の手紙 (GROUP_02371)
void 全バッジ金の手紙_fcba5c45f5d4(CTRPluginFramework::MenuEntry *entry);

// デートなんです (GROUP_02372)
void デートなんです_fcd0499504f0(CTRPluginFramework::MenuEntry *entry);

// 服屋 (GROUP_02377)
void 服屋_fdba5dee7016(CTRPluginFramework::MenuEntry *entry);

// オン島で電気操作 (GROUP_02378)
void オン島で電気操作_fe3f8516628f(CTRPluginFramework::MenuEntry *entry);

// カナダ (GROUP_02380)
void カナダ_fe507ebbe798(CTRPluginFramework::MenuEntry *entry);

// 自分に (GROUP_02383)
void 自分に_fe57c71a74e9(CTRPluginFramework::MenuEntry *entry);

// 坊主になる (GROUP_02387)
void 坊主になる_feca1af72b94(CTRPluginFramework::MenuEntry *entry);

// p (GROUP_02390)
void p_ff2922f2900f(CTRPluginFramework::MenuEntry *entry);

// 明るい茶色 (GROUP_02392)
void 明るい茶色_ff5d1574837c(CTRPluginFramework::MenuEntry *entry);

// 9 (GROUP_02394)
void Cheat_9_ff8d81d0e9d6(CTRPluginFramework::MenuEntry *entry);

// 服屋 (GROUP_02395)
void 服屋_ff910274e78e(CTRPluginFramework::MenuEntry *entry);

// まめつぶ商店 (GROUP_02397)
void まめつぶ商店_ffd48b976132(CTRPluginFramework::MenuEntry *entry);

} }
