// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace System {

// 白いポスト (GROUP_00003)
void 白いポスト_00508e338a9a(CTRPluginFramework::MenuEntry *entry);

// 地上の芝生緑化 (GROUP_00009)
void 地上の芝生緑化_00f267d603f4(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(雷) (GROUP_00011)
void 音反映チート_雷_016d100f9482(CTRPluginFramework::MenuEntry *entry);

// 2029 (GROUP_00012)
void Cheat_2029_016d4a77e32f(CTRPluginFramework::MenuEntry *entry);

// 2019 (GROUP_00013)
void Cheat_2019_016de13ac96e(CTRPluginFramework::MenuEntry *entry);

// チリ (GROUP_00015)
void チリ_019e2abcafff(CTRPluginFramework::MenuEntry *entry);

// アラブな壁 (GROUP_00016)
void アラブな壁_01a0f4d1e7eb(CTRPluginFramework::MenuEntry *entry);

// 特殊配列4 (GROUP_00018)
void 特殊配列4_020d8c6b3c3c(CTRPluginFramework::MenuEntry *entry);

// 2046 (GROUP_00022)
void Cheat_2046_024f5f5497d5(CTRPluginFramework::MenuEntry *entry);

// リメイクしていない (GROUP_00023)
void リメイクしていない_0251a915dc24(CTRPluginFramework::MenuEntry *entry);

// 埋める (GROUP_00026)
void 埋める_0282949e89b4(CTRPluginFramework::MenuEntry *entry);

// レンタルハニワ機能 (GROUP_00030)
void レンタルハニワ機能_0337f9936fbf(CTRPluginFramework::MenuEntry *entry);

// フレンド申請 (GROUP_00031)
void フレンド申請_035e5c1ef119(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 BBBB (GROUP_00035)
void 夢番地中4桁_BBBB_03ad7c005c54(CTRPluginFramework::MenuEntry *entry);

// 6黄緑 (GROUP_00036)
void Cheat_6黄緑_03d4658322a3(CTRPluginFramework::MenuEntry *entry);

// 赤バラ食べる (GROUP_00041)
void 赤バラ食べる_04008422f23c(CTRPluginFramework::MenuEntry *entry);

// 横に降りる (GROUP_00042)
void 横に降りる_0419793c5842(CTRPluginFramework::MenuEntry *entry);

// 国籍なし (GROUP_00043)
void 国籍なし_04775cd134be(CTRPluginFramework::MenuEntry *entry);

// わー (GROUP_00047)
void わー_04be16f96a93(CTRPluginFramework::MenuEntry *entry);

// 2039 (GROUP_00050)
void Cheat_2039_04ff976bbbbd(CTRPluginFramework::MenuEntry *entry);

// カントリーな屋根 (GROUP_00053)
void カントリーな屋根_0533b6961441(CTRPluginFramework::MenuEntry *entry);

// 博物館F2 未完成 (GROUP_00054)
void 博物館F2_未完成_0535954df3b1(CTRPluginFramework::MenuEntry *entry);

// 不可能 (GROUP_00059)
void 不可能_059ea328a73d(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 5555 (GROUP_00060)
void 夢番地上4桁_5555_05c202e6b5ce(CTRPluginFramework::MenuEntry *entry);

// 解除(副作用あり) (GROUP_00061)
void 解除_副作用あり_05cdd11e424b(CTRPluginFramework::MenuEntry *entry);

// 切り株掘る動作 掘り出す (GROUP_00064)
void 切り株掘る動作_掘り出す_06189997934f(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 9999 (GROUP_00065)
void 夢番地中4桁_9999_06519a5c509e(CTRPluginFramework::MenuEntry *entry);

// 発光 (GROUP_00067)
void 発光_06677fed9144(CTRPluginFramework::MenuEntry *entry);

// St.Kitts and Nevis (GROUP_00068)
void St_Kitts_and_Nevis_068b5af4aeec(CTRPluginFramework::MenuEntry *entry);

// フーっ (GROUP_00069)
void フーっ_06c990d38186(CTRPluginFramework::MenuEntry *entry);

// レンガの壁 (GROUP_00079)
void レンガの壁_077737880e59(CTRPluginFramework::MenuEntry *entry);

// 桜量120 (GROUP_00081)
void 桜量120_07d96ba677dd(CTRPluginFramework::MenuEntry *entry);

// アジアな壁 (GROUP_00086)
void アジアな壁_088d011bbdef(CTRPluginFramework::MenuEntry *entry);

// 左から右 (GROUP_00087)
void 左から右_08950055a958(CTRPluginFramework::MenuEntry *entry);

// 3オレンジ (GROUP_00088)
void Cheat_3オレンジ_08b20fa61c56(CTRPluginFramework::MenuEntry *entry);

// 四角いポスト (GROUP_00090)
void 四角いポスト_08c362b222ba(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧左奥1 昆虫 (GROUP_00092)
void 博物館1階_奧左奥1_昆虫_08ea97cc0e67(CTRPluginFramework::MenuEntry *entry);

// 住人9の引っ越し (GROUP_00098)
void 住人9の引っ越し_096e191b664e(CTRPluginFramework::MenuEntry *entry);

// Jamaica (GROUP_00100)
void Jamaica_09c3e7f1b564(CTRPluginFramework::MenuEntry *entry);

// Albania (GROUP_00101)
void Albania_09fef362ef8a(CTRPluginFramework::MenuEntry *entry);

// !g (GROUP_00102)
void g_0a38f42c9ccd(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 3333 (GROUP_00107)
void 夢番地中4桁_3333_0aaf29613e53(CTRPluginFramework::MenuEntry *entry);

// スペシャルバッチ-C (GROUP_00112)
void スペシャルバッチ_C_0b76bf5b7cfa(CTRPluginFramework::MenuEntry *entry);

// Austria (GROUP_00117)
void Austria_0c049081a547(CTRPluginFramework::MenuEntry *entry);

// 明るさUP off (GROUP_00120)
void 明るさUP_off_0c383afaf8be(CTRPluginFramework::MenuEntry *entry);

// 曲線的な柵 (GROUP_00121)
void 曲線的な柵_0c3aae26527b(CTRPluginFramework::MenuEntry *entry);

// 黒い屋根がわら (GROUP_00126)
void 黒い屋根がわら_0db517ce60ce(CTRPluginFramework::MenuEntry *entry);

// なし (GROUP_00133)
void なし_0eae7baeb821(CTRPluginFramework::MenuEntry *entry);

// 住人6 (GROUP_00134)
void 住人6_0f40e845a75c(CTRPluginFramework::MenuEntry *entry);

// 日焼け4 (GROUP_00136)
void 日焼け4_0f61217aa619(CTRPluginFramework::MenuEntry *entry);

// 地面が真っ暗 (GROUP_00138)
void 地面が真っ暗_0f76c29de898(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧左奥2 昆虫 (GROUP_00143)
void 博物館1階_奧左奥2_昆虫_0fec55bd7cb3(CTRPluginFramework::MenuEntry *entry);

// エンジン (GROUP_00149)
void エンジン_110c5c130571(CTRPluginFramework::MenuEntry *entry);

// 男5 (GROUP_00152)
void 男5_118fa40850a2(CTRPluginFramework::MenuEntry *entry);

// マーメイドな丸ドア (GROUP_00155)
void マーメイドな丸ドア_11b863d4cc05(CTRPluginFramework::MenuEntry *entry);

// 黄色いポスト (GROUP_00157)
void 黄色いポスト_11c4373ee657(CTRPluginFramework::MenuEntry *entry);

// トタンな屋根 (GROUP_00163)
void トタンな屋根_12b89425d197(CTRPluginFramework::MenuEntry *entry);

// Peru (GROUP_00164)
void Peru_1315df66464b(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 1111 (GROUP_00165)
void 夢番地下4桁_1111_1323b190d62d(CTRPluginFramework::MenuEntry *entry);

// 近未来の屋根 (GROUP_00172)
void 近未来の屋根_139d5e1e0096(CTRPluginFramework::MenuEntry *entry);

// コンクリートな敷石 (GROUP_00173)
void コンクリートな敷石_13af3c532d15(CTRPluginFramework::MenuEntry *entry);

// 岩の屋根 (GROUP_00174)
void 岩の屋根_13c8b5395f9a(CTRPluginFramework::MenuEntry *entry);

// コンクリートの屋根 (GROUP_00178)
void コンクリートの屋根_14064db789ed(CTRPluginFramework::MenuEntry *entry);

// スペシャルバッチ-A (GROUP_00187)
void スペシャルバッチ_A_14df94bfca2d(CTRPluginFramework::MenuEntry *entry);

// 2016 (GROUP_00190)
void Cheat_2016_1533710d64c4(CTRPluginFramework::MenuEntry *entry);

// ドロップタイプ (GROUP_00192)
void ドロップタイプ_155714be4fa5(CTRPluginFramework::MenuEntry *entry);

// 船から降りる (GROUP_00193)
void 船から降りる_156d9bdf3007(CTRPluginFramework::MenuEntry *entry);

// 60FPS (GROUP_00195)
void Cheat_60FPS_15a5894c8da0(CTRPluginFramework::MenuEntry *entry);

// 住人7の引っ越し (GROUP_00198)
void 住人7の引っ越し_15cfa7b4bda4(CTRPluginFramework::MenuEntry *entry);

// Grenada (GROUP_00201)
void Grenada_163b03f825a3(CTRPluginFramework::MenuEntry *entry);

// もの拾う (GROUP_00204)
void もの拾う_1667c472c7fc(CTRPluginFramework::MenuEntry *entry);

// ばあ!? (GROUP_00211)
void ばあ_173de21afd38(CTRPluginFramework::MenuEntry *entry);

// 支持率100% (GROUP_00214)
void 支持率100_178a80478ffe(CTRPluginFramework::MenuEntry *entry);

// 写真館(商店街のみ) (GROUP_00222)
void 写真館_商店街のみ_187e4a54d808(CTRPluginFramework::MenuEntry *entry);

// 筆まめ (GROUP_00223)
void 筆まめ_187fe96848bb(CTRPluginFramework::MenuEntry *entry);

// ホームセンターまめつぶ (GROUP_00225)
void ホームセンターまめつぶ_18da7df45e61(CTRPluginFramework::MenuEntry *entry);

// 2014 (GROUP_00229)
void Cheat_2014_194d4ba8d7ad(CTRPluginFramework::MenuEntry *entry);

// スペシャルをカーニバル1にする (GROUP_00230)
void スペシャルをカーニバル1にする_19877fa33fa0(CTRPluginFramework::MenuEntry *entry);

// 日焼け14 (GROUP_00231)
void 日焼け14_199d8712b993(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 手前左 化石1 (GROUP_00232)
void 博物館1階_手前左_化石1_19b8970dca0f(CTRPluginFramework::MenuEntry *entry);

// 料理 (GROUP_00233)
void 料理_1a1114990297(CTRPluginFramework::MenuEntry *entry);

// メルヘンなポスト (GROUP_00234)
void メルヘンなポスト_1a5179270691(CTRPluginFramework::MenuEntry *entry);

// 画面切り替え (GROUP_00235)
void 画面切り替え_1a5212c1945b(CTRPluginFramework::MenuEntry *entry);

// オーストリア (GROUP_00237)
void オーストリア_1a776b61d05a(CTRPluginFramework::MenuEntry *entry);

// 穴からすぐ出る (GROUP_00243)
void 穴からすぐ出る_1b0e5cdf629e(CTRPluginFramework::MenuEntry *entry);

// 噴水に変更 (GROUP_00247)
void 噴水に変更_1b439f578d0d(CTRPluginFramework::MenuEntry *entry);

// 空が青色になる (GROUP_00249)
void 空が青色になる_1b552602f206(CTRPluginFramework::MenuEntry *entry);

// スネーク動作ID用乗っ取り(外中対応) (GROUP_00250)
void スネーク動作ID用乗っ取り_外中対応_1b90d120b076(CTRPluginFramework::MenuEntry *entry);

// 置いた場所に高速ドロップ (GROUP_00254)
void 置いた場所に高速ドロップ_1c1bd6240a96(CTRPluginFramework::MenuEntry *entry);

// 重ね着 (GROUP_00255)
void 重ね着_1c2181cf75d1(CTRPluginFramework::MenuEntry *entry);

// 埋める動作を繰り返す (GROUP_00257)
void 埋める動作を繰り返す_1c54e3d24a10(CTRPluginFramework::MenuEntry *entry);

// スペシャルを戻す (GROUP_00258)
void スペシャルを戻す_1cb82b074da5(CTRPluginFramework::MenuEntry *entry);

// 釣り竿+か (GROUP_00261)
void 釣り竿_か_1dc26ae4726d(CTRPluginFramework::MenuEntry *entry);

// 拾ってドロップ (GROUP_00263)
void 拾ってドロップ_1e26312a90a9(CTRPluginFramework::MenuEntry *entry);

// 博物館2階 中央 (GROUP_00264)
void 博物館2階_中央_1e500b39a616(CTRPluginFramework::MenuEntry *entry);

// 縦画面化 (GROUP_00266)
void 縦画面化_1e60e1d4b6f1(CTRPluginFramework::MenuEntry *entry);

// 座る (GROUP_00267)
void 座る_1e75d32d2dc6(CTRPluginFramework::MenuEntry *entry);

// 和風な交番に変更 (GROUP_00275)
void 和風な交番に変更_1f4a7284c61a(CTRPluginFramework::MenuEntry *entry);

// 浮き寝 (GROUP_00277)
void 浮き寝_1f7cbd765c36(CTRPluginFramework::MenuEntry *entry);

// 地面に吸い込まれる (GROUP_00279)
void 地面に吸い込まれる_1fc6545b7e05(CTRPluginFramework::MenuEntry *entry);

// セーブできるようになりました (GROUP_00280)
void セーブできるようになりました_1fcf8f7c76e4(CTRPluginFramework::MenuEntry *entry);

// Mexico (GROUP_00288)
void Mexico_20463347b217(CTRPluginFramework::MenuEntry *entry);

// クラシックな交番に変更 (GROUP_00289)
void クラシックな交番に変更_204d7872f666(CTRPluginFramework::MenuEntry *entry);

// お祈り (GROUP_00292)
void お祈り_20b82af5bc1b(CTRPluginFramework::MenuEntry *entry);

// 夢見の館 (GROUP_00294)
void 夢見の館_21106dffa0b8(CTRPluginFramework::MenuEntry *entry);

// horu (GROUP_00295)
void horu_212154633608(CTRPluginFramework::MenuEntry *entry);

// 不揃いな石の屋根 (GROUP_00296)
void 不揃いな石の屋根_2133acd56420(CTRPluginFramework::MenuEntry *entry);

// しょぼいポスト (GROUP_00297)
void しょぼいポスト_2154c791273c(CTRPluginFramework::MenuEntry *entry);

// アラブな黄色いドア (GROUP_00300)
void アラブな黄色いドア_21b3b1b558e3(CTRPluginFramework::MenuEntry *entry);

// 連続でスコップで掘る動作 (GROUP_00303)
void 連続でスコップで掘る動作_22192a2b77a8(CTRPluginFramework::MenuEntry *entry);

// 銀バッジ (GROUP_00304)
void 銀バッジ_222aeab6f427(CTRPluginFramework::MenuEntry *entry);

// やまぶ黄色の屋根 (GROUP_00309)
void やまぶ黄色の屋根_22eefba8ae59(CTRPluginFramework::MenuEntry *entry);

// 男14 (GROUP_00312)
void 男14_230fb209923d(CTRPluginFramework::MenuEntry *entry);

// 高速メニュー表示 (GROUP_00313)
void 高速メニュー表示_2310b667e362(CTRPluginFramework::MenuEntry *entry);

// Montserrat (GROUP_00315)
void Montserrat_237beffb21b5(CTRPluginFramework::MenuEntry *entry);

// 黄金の屋根 (GROUP_00317)
void 黄金の屋根_239c19aac176(CTRPluginFramework::MenuEntry *entry);

// ロイヤルな壁 (GROUP_00318)
void ロイヤルな壁_240bae10bab2(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(スタート) (GROUP_00322)
void 音反映チート_スタート_24726484071b(CTRPluginFramework::MenuEntry *entry);

// ピンクの丸ドア (GROUP_00323)
void ピンクの丸ドア_24b5a742f0c4(CTRPluginFramework::MenuEntry *entry);

// 女29 (GROUP_00324)
void 女29_24bc0fc0aabe(CTRPluginFramework::MenuEntry *entry);

// 恐怖の森2 (GROUP_00329)
void 恐怖の森2_2505d9fc2685(CTRPluginFramework::MenuEntry *entry);

// 日焼け15 (GROUP_00332)
void 日焼け15_2546861b5dea(CTRPluginFramework::MenuEntry *entry);

// 茶色い丸ドア (GROUP_00333)
void 茶色い丸ドア_2556b6ae4517(CTRPluginFramework::MenuEntry *entry);

// 金属のポスト (GROUP_00337)
void 金属のポスト_2594a7bd0954(CTRPluginFramework::MenuEntry *entry);

// 黄 (GROUP_00338)
void 黄_259c73c1bbd5(CTRPluginFramework::MenuEntry *entry);

// 色とりどりな玉砂利 (GROUP_00341)
void 色とりどりな玉砂利_264ab3f5de2f(CTRPluginFramework::MenuEntry *entry);

// 掘って岩ドロップ (GROUP_00345)
void 掘って岩ドロップ_26a036d72452(CTRPluginFramework::MenuEntry *entry);

// 手降る (GROUP_00347)
void 手降る_26aef4bb8294(CTRPluginFramework::MenuEntry *entry);

// 5金色 (GROUP_00351)
void Cheat_5金色_26d481bd24f5(CTRPluginFramework::MenuEntry *entry);

// 33333 (GROUP_00352)
void Cheat_33333_26fff5edbc00(CTRPluginFramework::MenuEntry *entry);

// 喜ぶ (GROUP_00354)
void 喜ぶ_27405a33d858(CTRPluginFramework::MenuEntry *entry);

// 2044 (GROUP_00358)
void Cheat_2044_2797442401d8(CTRPluginFramework::MenuEntry *entry);

// 近未来の丸ドア (GROUP_00361)
void 近未来の丸ドア_27e11b39d513(CTRPluginFramework::MenuEntry *entry);

// アンティグアバーブーダ (GROUP_00362)
void アンティグアバーブーダ_27e17347f8e3(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 2222 (GROUP_00364)
void 夢番地中4桁_2222_28076be770c9(CTRPluginFramework::MenuEntry *entry);

// セーブメニュー出さない [start+/] (GROUP_00368)
void セーブメニュー出さない_start_287b962ab6a6(CTRPluginFramework::MenuEntry *entry);

// あつ森風の色彩 (GROUP_00369)
void あつ森風の色彩_2887e584b62d(CTRPluginFramework::MenuEntry *entry);

// スコップの判定解除 (GROUP_00371)
void スコップの判定解除_28b0122c8568(CTRPluginFramework::MenuEntry *entry);

// 14緑 (GROUP_00374)
void Cheat_14緑_28f09167b8cd(CTRPluginFramework::MenuEntry *entry);

// 連続で水をあげる動作 (GROUP_00379)
void 連続で水をあげる動作_291978d868e9(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 7777 (GROUP_00380)
void 夢番地上4桁_7777_296faad156b5(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 1111 (GROUP_00387)
void 夢番地中4桁_1111_2a5918efd9bc(CTRPluginFramework::MenuEntry *entry);

// 無限に埋める、食べる オフ (GROUP_00388)
void 無限に埋める_食べる_オフ_2a667c79aed8(CTRPluginFramework::MenuEntry *entry);

// Uruguay (GROUP_00389)
void Uruguay_2a70dc94cf9a(CTRPluginFramework::MenuEntry *entry);

// スペシャルを飛び込むにする (GROUP_00391)
void スペシャルを飛び込むにする_2addf599fb1e(CTRPluginFramework::MenuEntry *entry);

// 日焼け13 (GROUP_00395)
void 日焼け13_2b6195360c2a(CTRPluginFramework::MenuEntry *entry);

// モダンないえ (GROUP_00397)
void モダンないえ_2b959ee6b1e0(CTRPluginFramework::MenuEntry *entry);

// CLUB444 ライブ中 (GROUP_00398)
void CLUB444_ライブ中_2bd8e0230fe5(CTRPluginFramework::MenuEntry *entry);

// 黄金の柵 (GROUP_00402)
void 黄金の柵_2c906f0ef136(CTRPluginFramework::MenuEntry *entry);

// 和風な丸ドア (GROUP_00404)
void 和風な丸ドア_2cb592fc523b(CTRPluginFramework::MenuEntry *entry);

// 12濃い青 (GROUP_00406)
void Cheat_12濃い青_2cf285a64f9c(CTRPluginFramework::MenuEntry *entry);

// 髪型変更オフ (GROUP_00412)
void 髪型変更オフ_2d2b64277680(CTRPluginFramework::MenuEntry *entry);

// グロ (GROUP_00413)
void グロ_2d494a904e97(CTRPluginFramework::MenuEntry *entry);

// 四角いログハウスのドア (GROUP_00415)
void 四角いログハウスのドア_2da2dae2405f(CTRPluginFramework::MenuEntry *entry);

// 首を傾げる (GROUP_00416)
void 首を傾げる_2dc91382cfd5(CTRPluginFramework::MenuEntry *entry);

// わふうのおしろ (GROUP_00419)
void わふうのおしろ_2e0e99268d3d(CTRPluginFramework::MenuEntry *entry);

// 青い柵 (GROUP_00422)
void 青い柵_2e5456d2b1d0(CTRPluginFramework::MenuEntry *entry);

// 住人2の引っ越し解除 (GROUP_00425)
void 住人2の引っ越し解除_2e592042a6e2(CTRPluginFramework::MenuEntry *entry);

// 連続でクラゲに刺された状態から治る動作 (GROUP_00427)
void 連続でクラゲに刺された状態から治る動作_2ea7cbe5ee47(CTRPluginFramework::MenuEntry *entry);

// 網の動作 (GROUP_00431)
void 網の動作_2efd87a3989f(CTRPluginFramework::MenuEntry *entry);

// 2032 (GROUP_00433)
void Cheat_2032_2f2eea15de38(CTRPluginFramework::MenuEntry *entry);

// メルヘンな屋根 (GROUP_00438)
void メルヘンな屋根_2ff4ee5d2fc3(CTRPluginFramework::MenuEntry *entry);

// 粗い石畳 (GROUP_00442)
void 粗い石畳_3106413cece9(CTRPluginFramework::MenuEntry *entry);

// 岩と土の壁 (GROUP_00443)
void 岩と土の壁_31184f6f9183(CTRPluginFramework::MenuEntry *entry);

// 急ブレーキ無効化 (GROUP_00448)
void 急ブレーキ無効化_31600e00f9d8(CTRPluginFramework::MenuEntry *entry);

// 青 (GROUP_00451)
void 青_318cb3cacd76(CTRPluginFramework::MenuEntry *entry);

// 気絶(中) (動作がおかしくなった時実行) (GROUP_00454)
void 気絶_中_動作がおかしくなった時実行_31d70ebd4b2d(CTRPluginFramework::MenuEntry *entry);

// 昼の明るさ (GROUP_00455)
void 昼の明るさ_31e351d43c22(CTRPluginFramework::MenuEntry *entry);

// 四角いメルヘンなドア (GROUP_00458)
void 四角いメルヘンなドア_32432c315ea3(CTRPluginFramework::MenuEntry *entry);

// 赤い屋根 (GROUP_00463)
void 赤い屋根_32c88f3ff9e7(CTRPluginFramework::MenuEntry *entry);

// 明るさUP (GROUP_00464)
void 明るさUP_32f50e675ade(CTRPluginFramework::MenuEntry *entry);

// オノ壊れる (GROUP_00467)
void オノ壊れる_3366c70c6b05(CTRPluginFramework::MenuEntry *entry);

// 若葉色のポスト (GROUP_00472)
void 若葉色のポスト_33ef135177b7(CTRPluginFramework::MenuEntry *entry);

// 靴屋 工事中 (GROUP_00473)
void 靴屋_工事中_344c140fdd8b(CTRPluginFramework::MenuEntry *entry);

// 紫のでこぼこ屋根 (GROUP_00474)
void 紫のでこぼこ屋根_34694f05cb5e(CTRPluginFramework::MenuEntry *entry);

// お菓子の壁 (GROUP_00475)
void お菓子の壁_3480bc8a100f(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 EEEE (GROUP_00480)
void 夢番地上4桁_EEEE_34fdc55744b6(CTRPluginFramework::MenuEntry *entry);

// 影が青色になる (GROUP_00481)
void 影が青色になる_3503138f05c6(CTRPluginFramework::MenuEntry *entry);

// マップアイコン (GROUP_00485)
void マップアイコン_3583eb7dc990(CTRPluginFramework::MenuEntry *entry);

// コケる外 (GROUP_00490)
void コケる外_35a484b7c08a(CTRPluginFramework::MenuEntry *entry);

// いっぺんに置ける (GROUP_00491)
void いっぺんに置ける_35ae38a8329c(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量180 (GROUP_00492)
void 紙吹雪量180_35af78deb7ad(CTRPluginFramework::MenuEntry *entry);

// 四角い竹のドア (GROUP_00496)
void 四角い竹のドア_36748cdfa313(CTRPluginFramework::MenuEntry *entry);

// 空が赤色になる (GROUP_00499)
void 空が赤色になる_36f456293f83(CTRPluginFramework::MenuEntry *entry);

// グレーのモダンな屋根 (GROUP_00501)
void グレーのモダンな屋根_373c60a3c5aa(CTRPluginFramework::MenuEntry *entry);

// 切り株掘る動作 埋める (GROUP_00502)
void 切り株掘る動作_埋める_374b3aa9952c(CTRPluginFramework::MenuEntry *entry);

// CLU444 未完成 (GROUP_00503)
void CLU444_未完成_375ee2f22f02(CTRPluginFramework::MenuEntry *entry);

// 落とし穴 (GROUP_00505)
void 落とし穴_37a803a4468c(CTRPluginFramework::MenuEntry *entry);

// 丸太の柵 (GROUP_00508)
void 丸太の柵_3800ef4d93e7(CTRPluginFramework::MenuEntry *entry);

// 駅員の位置をもとに戻す (GROUP_00510)
void 駅員の位置をもとに戻す_381ce68b2c23(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 手前右 美術館 (GROUP_00512)
void 博物館1階_手前右_美術館_382e979dc630(CTRPluginFramework::MenuEntry *entry);

// メガホン文字出す (GROUP_00515)
void メガホン文字出す_3845ead4b8c4(CTRPluginFramework::MenuEntry *entry);

// 日焼け1 (GROUP_00516)
void 日焼け1_385adb2a4bd2(CTRPluginFramework::MenuEntry *entry);

// 8白 (GROUP_00523)
void Cheat_8白_38bf7c043c18(CTRPluginFramework::MenuEntry *entry);

// 赤いレンガのかこい (GROUP_00526)
void 赤いレンガのかこい_390bc976b79c(CTRPluginFramework::MenuEntry *entry);

// 2050 (GROUP_00527)
void Cheat_2050_3912a811d17b(CTRPluginFramework::MenuEntry *entry);

// 変な座り方 (GROUP_00530)
void 変な座り方_39afd9fbd2f1(CTRPluginFramework::MenuEntry *entry);

// Paraguay (GROUP_00532)
void Paraguay_39f773e10884(CTRPluginFramework::MenuEntry *entry);

// 男1 (GROUP_00534)
void 男1_3a3b3396c867(CTRPluginFramework::MenuEntry *entry);

// 謎テキスト (GROUP_00535)
void 謎テキスト_3a4a449fbf75(CTRPluginFramework::MenuEntry *entry);

// 転ぶ (GROUP_00536)
void 転ぶ_3a5d6c57d18d(CTRPluginFramework::MenuEntry *entry);

// 一階(大) (GROUP_00538)
void 一階_大_3a9ac3d7b2d9(CTRPluginFramework::MenuEntry *entry);

// 直線的な壁 (GROUP_00541)
void 直線的な壁_3aeeea0bd343(CTRPluginFramework::MenuEntry *entry);

// Haiti (GROUP_00545)
void Haiti_3b684feaae0e(CTRPluginFramework::MenuEntry *entry);

// 普通 (GROUP_00547)
void 普通_3ba5938c12bd(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量120 (GROUP_00553)
void 紙吹雪量120_3bef653be2ea(CTRPluginFramework::MenuEntry *entry);

// 2028 (GROUP_00554)
void Cheat_2028_3bf3370b23ba(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 4444 (GROUP_00558)
void 夢番地下4桁_4444_3c719d2e524d(CTRPluginFramework::MenuEntry *entry);

// 住人9の引っ越し解除 (GROUP_00560)
void 住人9の引っ越し解除_3caf310d09d5(CTRPluginFramework::MenuEntry *entry);

// Venezuela (GROUP_00562)
void Venezuela_3ccab49d726f(CTRPluginFramework::MenuEntry *entry);

// 面白い (GROUP_00564)
void 面白い_3d0033be6987(CTRPluginFramework::MenuEntry *entry);

// 特殊配列2 (GROUP_00566)
void 特殊配列2_3d2b2fe996c6(CTRPluginFramework::MenuEntry *entry);

// アンギラ (GROUP_00567)
void アンギラ_3d467e77c4bb(CTRPluginFramework::MenuEntry *entry);

// ぴょんたろうダンス (GROUP_00568)
void ぴょんたろうダンス_3d5075ab28e2(CTRPluginFramework::MenuEntry *entry);

// ククスネーク (GROUP_00572)
void ククスネーク_3e372e28f661(CTRPluginFramework::MenuEntry *entry);

// 土の壁 (GROUP_00577)
void 土の壁_3e85e59bb3a7(CTRPluginFramework::MenuEntry *entry);

// 4545 (GROUP_00578)
void Cheat_4545_3eb926ee330b(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 CCCC (GROUP_00584)
void 夢番地上4桁_CCCC_3f949f86b172(CTRPluginFramework::MenuEntry *entry);

// スコップ復元 (GROUP_00589)
void スコップ復元_40012c23ef4d(CTRPluginFramework::MenuEntry *entry);

// 住人6の引っ越し (GROUP_00593)
void 住人6の引っ越し_40a7ce2021f0(CTRPluginFramework::MenuEntry *entry);

// カーニバルダンス1 (GROUP_00595)
void カーニバルダンス1_40d5b60e9005(CTRPluginFramework::MenuEntry *entry);

// 桜オン (GROUP_00596)
void 桜オン_40db2ea0c084(CTRPluginFramework::MenuEntry *entry);

// 窓付き丸ドア (GROUP_00597)
void 窓付き丸ドア_40f20a0e28cc(CTRPluginFramework::MenuEntry *entry);

// スーパー (GROUP_00600)
void スーパー_412e75c5ac17(CTRPluginFramework::MenuEntry *entry);

// ハニワを中心に (GROUP_00603)
void ハニワを中心に_41a44fb1c044(CTRPluginFramework::MenuEntry *entry);

// 岩砕いてドロップ (GROUP_00606)
void 岩砕いてドロップ_42360d63d70e(CTRPluginFramework::MenuEntry *entry);

// 気絶し続ける (GROUP_00608)
void 気絶し続ける_4259f882ab5a(CTRPluginFramework::MenuEntry *entry);

// スーパー病んだ世界 (GROUP_00609)
void スーパー病んだ世界_4266a4cd8a90(CTRPluginFramework::MenuEntry *entry);

// Guadeloupe (GROUP_00614)
void Guadeloupe_42aa06e8c00e(CTRPluginFramework::MenuEntry *entry);

// 2012 (GROUP_00616)
void Cheat_2012_4301e7117858(CTRPluginFramework::MenuEntry *entry);

// 住人10の引っ越し解除 (GROUP_00617)
void 住人10の引っ越し解除_43117d6d2a91(CTRPluginFramework::MenuEntry *entry);

// デパート 3F (GROUP_00629)
void デパート_3F_43dc40410c47(CTRPluginFramework::MenuEntry *entry);

// 2013 (GROUP_00630)
void Cheat_2013_43e4aa2adad5(CTRPluginFramework::MenuEntry *entry);

// 吹き戻し (GROUP_00634)
void 吹き戻し_447e7685199a(CTRPluginFramework::MenuEntry *entry);

// メルヘンな壁 (GROUP_00637)
void メルヘンな壁_448c784e02ae(CTRPluginFramework::MenuEntry *entry);

// 雲が緑色になる (GROUP_00640)
void 雲が緑色になる_44cd7fab3f2f(CTRPluginFramework::MenuEntry *entry);

// ものもらう (GROUP_00643)
void ものもらう_452a63464dec(CTRPluginFramework::MenuEntry *entry);

// 雑貨屋 (GROUP_00647)
void 雑貨屋_4563b1e5437e(CTRPluginFramework::MenuEntry *entry);

// コンビニ (GROUP_00648)
void コンビニ_45966efbf4e5(CTRPluginFramework::MenuEntry *entry);

// 倒れる (GROUP_00650)
void 倒れる_45bbfc9669b0(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 6666 (GROUP_00652)
void 夢番地中4桁_6666_462b3abe8a69(CTRPluginFramework::MenuEntry *entry);

// ラグを無くす (GROUP_00653)
void ラグを無くす_4643a6bed2fc(CTRPluginFramework::MenuEntry *entry);

// 男13 (GROUP_00654)
void 男13_46476d1b8bd5(CTRPluginFramework::MenuEntry *entry);

// 鉱石動作オノ (GROUP_00656)
void 鉱石動作オノ_46b7ffae0c62(CTRPluginFramework::MenuEntry *entry);

// 四角いマーメイドなドア (GROUP_00657)
void 四角いマーメイドなドア_46c905c6cb6a(CTRPluginFramework::MenuEntry *entry);

// 有刺鉄線 (GROUP_00660)
void 有刺鉄線_471aa48b33f1(CTRPluginFramework::MenuEntry *entry);

// 地上の芝生砂漠化 (GROUP_00665)
void 地上の芝生砂漠化_478d73de1464(CTRPluginFramework::MenuEntry *entry);

// 髪乗っ取りするときオン(自分が回転すると反映) (GROUP_00669)
void 髪乗っ取りするときオン_自分が回転すると反映_4833f078dddc(CTRPluginFramework::MenuEntry *entry);

// テクスチャ [/] (GROUP_00670)
void テクスチャ_4875d8d0957e(CTRPluginFramework::MenuEntry *entry);

// ハチに刺される1 (GROUP_00672)
void ハチに刺される1_4881397e7ba5(CTRPluginFramework::MenuEntry *entry);

// 日焼け6 (GROUP_00675)
void 日焼け6_48ab406c81c5(CTRPluginFramework::MenuEntry *entry);

// 船に乗る (GROUP_00679)
void 船に乗る_4943b084d9b4(CTRPluginFramework::MenuEntry *entry);

// 掘ってリンゴが出てドロップ (GROUP_00682)
void 掘ってリンゴが出てドロップ_49933baf46ba(CTRPluginFramework::MenuEntry *entry);

// 掘ったところから火がでる (GROUP_00683)
void 掘ったところから火がでる_49a0041b2afd(CTRPluginFramework::MenuEntry *entry);

// 住人3 (GROUP_00690)
void 住人3_4a18b23c31c6(CTRPluginFramework::MenuEntry *entry);

// 2034 (GROUP_00693)
void Cheat_2034_4a7fa3bb28c9(CTRPluginFramework::MenuEntry *entry);

// リメイク後 (GROUP_00696)
void リメイク後_4ac8eb6645b5(CTRPluginFramework::MenuEntry *entry);

// 男9 (GROUP_00698)
void 男9_4afd19504b7e(CTRPluginFramework::MenuEntry *entry);

// 女33 (GROUP_00701)
void 女33_4b68ba93a6a9(CTRPluginFramework::MenuEntry *entry);

// 黒い屋根 (GROUP_00705)
void 黒い屋根_4ba17dff08d6(CTRPluginFramework::MenuEntry *entry);

// 掘ろうとする (GROUP_00706)
void 掘ろうとする_4bc654b523ea(CTRPluginFramework::MenuEntry *entry);

// ドロップデフォルト (GROUP_00712)
void ドロップデフォルト_4c51ce6562fe(CTRPluginFramework::MenuEntry *entry);

// 穴はじき (GROUP_00713)
void 穴はじき_4c558cde0d7b(CTRPluginFramework::MenuEntry *entry);

// iwa (GROUP_00715)
void iwa_4c6c258ca5ac(CTRPluginFramework::MenuEntry *entry);

// ライトモード (GROUP_00716)
void ライトモード_4c745f7bd26f(CTRPluginFramework::MenuEntry *entry);

// 今週の株価変更 (GROUP_00719)
void 今週の株価変更_4c8c3deab4b9(CTRPluginFramework::MenuEntry *entry);

// 可能 (GROUP_00720)
void 可能_4c911292c4f4(CTRPluginFramework::MenuEntry *entry);

// 音反映させる (GROUP_00723)
void 音反映させる_4caa8ece5e9d(CTRPluginFramework::MenuEntry *entry);

// キキララ (GROUP_00724)
void キキララ_4cb55e9dac58(CTRPluginFramework::MenuEntry *entry);

// 切り株掘る動作 普通 (GROUP_00728)
void 切り株掘る動作_普通_4cf81c491e2b(CTRPluginFramework::MenuEntry *entry);

// 日焼け11 (GROUP_00731)
void 日焼け11_4d91bb5d5179(CTRPluginFramework::MenuEntry *entry);

// 女20 (GROUP_00735)
void 女20_4dee865c8f8c(CTRPluginFramework::MenuEntry *entry);

// ピンクの屋根 (GROUP_00736)
void ピンクの屋根_4e10dbf3c8a6(CTRPluginFramework::MenuEntry *entry);

// サブ3 -> 自分 (GROUP_00738)
void サブ3_自分_4e299d055f41(CTRPluginFramework::MenuEntry *entry);

// 蚊 (GROUP_00744)
void 蚊_4ea911b7d3e3(CTRPluginFramework::MenuEntry *entry);

// 俺のお気に入り (GROUP_00745)
void 俺のお気に入り_4ec021ccd65c(CTRPluginFramework::MenuEntry *entry);

// 商店街(外) (GROUP_00749)
void 商店街_外_4fb2f2aa083f(CTRPluginFramework::MenuEntry *entry);

// 持つ (GROUP_00753)
void 持つ_5012ab0146c4(CTRPluginFramework::MenuEntry *entry);

// 誕生日の火を消す (GROUP_00756)
void 誕生日の火を消す_508cbb8931f7(CTRPluginFramework::MenuEntry *entry);

// 住人1の引っ越し解除 (GROUP_00759)
void 住人1の引っ越し解除_50b86e1f89d4(CTRPluginFramework::MenuEntry *entry);

// かくれんぼ (GROUP_00760)
void かくれんぼ_5116ddfe5134(CTRPluginFramework::MenuEntry *entry);

// コントラスト2 (GROUP_00764)
void コントラスト2_5142d5bea51f(CTRPluginFramework::MenuEntry *entry);

// 落とし穴や穴に落ちない (GROUP_00766)
void 落とし穴や穴に落ちない_515fc9d3eb68(CTRPluginFramework::MenuEntry *entry);

// 黒いわらぶき屋根 (GROUP_00767)
void 黒いわらぶき屋根_5162b462ef70(CTRPluginFramework::MenuEntry *entry);

// 非表示 (GROUP_00768)
void 非表示_5178254bc41e(CTRPluginFramework::MenuEntry *entry);

// 2031 (GROUP_00770)
void Cheat_2031_518c94be0d59(CTRPluginFramework::MenuEntry *entry);

// 四角いぼろいドア (GROUP_00771)
void 四角いぼろいドア_5193f2b2ef21(CTRPluginFramework::MenuEntry *entry);

// 1黒 (GROUP_00773)
void Cheat_1黒_51a2a0e783de(CTRPluginFramework::MenuEntry *entry);

// 水色のポスト (GROUP_00780)
void 水色のポスト_52cccef98d64(CTRPluginFramework::MenuEntry *entry);

// カメヤマテント (GROUP_00781)
void カメヤマテント_52d24ee2dc24(CTRPluginFramework::MenuEntry *entry);

// 視界が広くなるoff (GROUP_00783)
void 視界が広くなるoff_530cae607827(CTRPluginFramework::MenuEntry *entry);

// わかめ (GROUP_00785)
void わかめ_533a65154e0f(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 AAAA (GROUP_00786)
void 夢番地上4桁_AAAA_534c168e5884(CTRPluginFramework::MenuEntry *entry);

// 女25 (GROUP_00790)
void 女25_536d8b173064(CTRPluginFramework::MenuEntry *entry);

// ピンクの敷石 (GROUP_00792)
void ピンクの敷石_53d0fbe1c653(CTRPluginFramework::MenuEntry *entry);

// ドロップ (GROUP_00793)
void ドロップ_53d7cc1eb23b(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 8888 (GROUP_00800)
void 夢番地下4桁_8888_5493cd098af9(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(クラクション) (GROUP_00803)
void 音反映チート_クラクション_54e98c202826(CTRPluginFramework::MenuEntry *entry);

// 小石の石畳 (GROUP_00813)
void 小石の石畳_55b82ae9a579(CTRPluginFramework::MenuEntry *entry);

// セーブ画面とかが喋りだす (GROUP_00817)
void セーブ画面とかが喋りだす_55e1b1a7e14b(CTRPluginFramework::MenuEntry *entry);

// 桜オフ (GROUP_00818)
void 桜オフ_56089819ac04(CTRPluginFramework::MenuEntry *entry);

// Netherlands (GROUP_00819)
void Netherlands_5613af519db6(CTRPluginFramework::MenuEntry *entry);

// スライディング無効化 (GROUP_00820)
void スライディング無効化_56339c90ef97(CTRPluginFramework::MenuEntry *entry);

// 四角い魚窓のドア (GROUP_00822)
void 四角い魚窓のドア_5686edf2bf5d(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 手前左下 (GROUP_00826)
void 博物館1階_手前左下_579e5b367b22(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(達成) (GROUP_00827)
void 音反映チート_達成_57f015f4e0f1(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 BBBB (GROUP_00829)
void 夢番地上4桁_BBBB_5800ea45d2f9(CTRPluginFramework::MenuEntry *entry);

// 女26 (GROUP_00830)
void 女26_581603fd655c(CTRPluginFramework::MenuEntry *entry);

// 動作関係高速化コード (GROUP_00835)
void 動作関係高速化コード_58a672c69a8e(CTRPluginFramework::MenuEntry *entry);

// 男4 (GROUP_00836)
void 男4_58b3675a7a91(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 0000 (GROUP_00840)
void 夢番地上4桁_0000_592465130329(CTRPluginFramework::MenuEntry *entry);

// 男17 (GROUP_00844)
void 男17_596ed1a62e63(CTRPluginFramework::MenuEntry *entry);

// メルヘンな丸ドア (GROUP_00845)
void メルヘンな丸ドア_597504d12806(CTRPluginFramework::MenuEntry *entry);

// St.Lucia (GROUP_00851)
void St_Lucia_5a1716ba0581(CTRPluginFramework::MenuEntry *entry);

// いけがき (GROUP_00852)
void いけがき_5a1a7cfa26d0(CTRPluginFramework::MenuEntry *entry);

// 連続で帽子を脱ぐ動作 (GROUP_00856)
void 連続で帽子を脱ぐ動作_5a924665b73b(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作でドロップ2 (GROUP_00858)
void 岩壊す動作でドロップ2_5aa6abd7252d(CTRPluginFramework::MenuEntry *entry);

// 2023 (GROUP_00861)
void Cheat_2023_5af45b32e9bd(CTRPluginFramework::MenuEntry *entry);

// 四角いアラブなドア (GROUP_00862)
void 四角いアラブなドア_5b29d52d0b71(CTRPluginFramework::MenuEntry *entry);

// 駅に変更 (GROUP_00863)
void 駅に変更_5bd7add9da87(CTRPluginFramework::MenuEntry *entry);

// CLUB444 完成 (GROUP_00868)
void CLUB444_完成_5c4e8bd804d6(CTRPluginFramework::MenuEntry *entry);

// 住人2 (GROUP_00870)
void 住人2_5c8719506429(CTRPluginFramework::MenuEntry *entry);

// 非売品を買える (GROUP_00872)
void 非売品を買える_5d08ed0e14d8(CTRPluginFramework::MenuEntry *entry);

// ロッカー機能 (GROUP_00873)
void ロッカー機能_5d0db663a482(CTRPluginFramework::MenuEntry *entry);

// 桜量30 (GROUP_00876)
void 桜量30_5d359f808c13(CTRPluginFramework::MenuEntry *entry);

// 占い (GROUP_00878)
void 占い_5d411a400818(CTRPluginFramework::MenuEntry *entry);

// うさぎ風船セット (GROUP_00885)
void うさぎ風船セット_5dec54894121(CTRPluginFramework::MenuEntry *entry);

// 女18 (GROUP_00887)
void 女18_5df6e2dc561a(CTRPluginFramework::MenuEntry *entry);

// ロイヤルなポスト (GROUP_00888)
void ロイヤルなポスト_5e38b9050ce0(CTRPluginFramework::MenuEntry *entry);

// 女19 (GROUP_00889)
void 女19_5e3992f18efd(CTRPluginFramework::MenuEntry *entry);

// 銀 (GROUP_00890)
void 銀_5e4f7ce8dbec(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧左 昆虫 (GROUP_00893)
void 博物館1階_奧左_昆虫_5e93081fed56(CTRPluginFramework::MenuEntry *entry);

// 回転ドロップ (GROUP_00898)
void 回転ドロップ_5f231b096624(CTRPluginFramework::MenuEntry *entry);

// 住人4の引っ越し解除 (GROUP_00899)
void 住人4の引っ越し解除_5f38f9623202(CTRPluginFramework::MenuEntry *entry);

// 2024 (GROUP_00905)
void Cheat_2024_5febe969025e(CTRPluginFramework::MenuEntry *entry);

// たぬきハウジング (GROUP_00911)
void たぬきハウジング_609f739e332e(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪オフ (GROUP_00917)
void 紙吹雪オフ_610ca4df9883(CTRPluginFramework::MenuEntry *entry);

// ノック (GROUP_00926)
void ノック_623e5f86f01f(CTRPluginFramework::MenuEntry *entry);

// 青いポスト (GROUP_00928)
void 青いポスト_6280fac15d67(CTRPluginFramework::MenuEntry *entry);

// 無限に埋める、食べる オン (GROUP_00930)
void 無限に埋める_食べる_オン_62b7c72da325(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 0000 (GROUP_00934)
void 夢番地中4桁_0000_63051f538424(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 中央 (GROUP_00938)
void 博物館1階_中央_636f8edf4048(CTRPluginFramework::MenuEntry *entry);

// 2041 (GROUP_00939)
void Cheat_2041_637a563592cf(CTRPluginFramework::MenuEntry *entry);

// Franch Guiana (GROUP_00944)
void Franch_Guiana_63e197829e7e(CTRPluginFramework::MenuEntry *entry);

// お菓子の丸ドア (GROUP_00947)
void お菓子の丸ドア_64a8caad4404(CTRPluginFramework::MenuEntry *entry);

// CLUB444 ライブ終わり後 (GROUP_00951)
void CLUB444_ライブ終わり後_658ed8df8cf8(CTRPluginFramework::MenuEntry *entry);

// ツアーリセット (GROUP_00956)
void ツアーリセット_65fe8ed1c15b(CTRPluginFramework::MenuEntry *entry);

// 四角いふうなドア (GROUP_00957)
void 四角いふうなドア_661a905725ac(CTRPluginFramework::MenuEntry *entry);

// hirou (GROUP_00966)
void hirou_66b558c7bc5c(CTRPluginFramework::MenuEntry *entry);

// 2018 (GROUP_00967)
void Cheat_2018_66c488597c0c(CTRPluginFramework::MenuEntry *entry);

// 捨ててドロップ (GROUP_00968)
void 捨ててドロップ_66df3541c323(CTRPluginFramework::MenuEntry *entry);

// 自分で自分たたく(ドM) (GROUP_00969)
void 自分で自分たたく_ドM_66e4672d49ec(CTRPluginFramework::MenuEntry *entry);

// 向きを変えてイスから降りる (GROUP_00972)
void 向きを変えてイスから降りる_674c6d9d0581(CTRPluginFramework::MenuEntry *entry);

// ログハウスの壁 (GROUP_00973)
void ログハウスの壁_678101438680(CTRPluginFramework::MenuEntry *entry);

// 緑のポスト (GROUP_00974)
void 緑のポスト_6794af69e7e9(CTRPluginFramework::MenuEntry *entry);

// 810 (GROUP_00976)
void Cheat_810_67c4d637e374(CTRPluginFramework::MenuEntry *entry);

// 水色の壁 (GROUP_00978)
void 水色の壁_67de101a3caf(CTRPluginFramework::MenuEntry *entry);

// kaijyo (GROUP_00979)
void kaijyo_68090f2564d9(CTRPluginFramework::MenuEntry *entry);

// 住人4 (GROUP_00988)
void 住人4_692097ab71ec(CTRPluginFramework::MenuEntry *entry);

// 切り株掘る動作 岩 (GROUP_00989)
void 切り株掘る動作_岩_69386be616e3(CTRPluginFramework::MenuEntry *entry);

// カラフルな壁 (GROUP_00990)
void カラフルな壁_693a041b3606(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 2222 (GROUP_00994)
void 夢番地下4桁_2222_6982449195be(CTRPluginFramework::MenuEntry *entry);

// 全部金 (GROUP_00996)
void 全部金_6991007600a6(CTRPluginFramework::MenuEntry *entry);

// 乗っ取り C4ムーンジャンプ (GROUP_01000)
void 乗っ取り_C4ムーンジャンプ_6a31f0cde064(CTRPluginFramework::MenuEntry *entry);

// クーコスネーク (GROUP_01002)
void クーコスネーク_6a4697570281(CTRPluginFramework::MenuEntry *entry);

// ゆっくり座る (GROUP_01003)
void ゆっくり座る_6a6131c47b3c(CTRPluginFramework::MenuEntry *entry);

// Australia (GROUP_01006)
void Australia_6ace909a8090(CTRPluginFramework::MenuEntry *entry);

// 横に降りて穴に入る (GROUP_01011)
void 横に降りて穴に入る_6b52c6255fa9(CTRPluginFramework::MenuEntry *entry);

// 鉄の丸ドア (GROUP_01013)
void 鉄の丸ドア_6bf96ee45d6c(CTRPluginFramework::MenuEntry *entry);

// 写真館 (GROUP_01014)
void 写真館_6c22e9a667c1(CTRPluginFramework::MenuEntry *entry);

// ka (GROUP_01015)
void ka_6c8791760fe6(CTRPluginFramework::MenuEntry *entry);

// バッジ無し (GROUP_01018)
void バッジ無し_6ca0f2d9c5d1(CTRPluginFramework::MenuEntry *entry);

// ファンシーワールド (GROUP_01020)
void ファンシーワールド_6d005bb53bdf(CTRPluginFramework::MenuEntry *entry);

// ききーっ (GROUP_01021)
void ききーっ_6d04380255be(CTRPluginFramework::MenuEntry *entry);

// スペシャルをカーニバル3にする (GROUP_01022)
void スペシャルをカーニバル3にする_6d2ea1edfa98(CTRPluginFramework::MenuEntry *entry);

// じゃんけん2 (GROUP_01029)
void じゃんけん2_6e1c55f3dd9b(CTRPluginFramework::MenuEntry *entry);

// 青いメルヘンなドア (GROUP_01030)
void 青いメルヘンなドア_6e363b45f90b(CTRPluginFramework::MenuEntry *entry);

// 穴を埋める動作変更(掘る) (GROUP_01031)
void 穴を埋める動作変更_掘る_6e470c2fa080(CTRPluginFramework::MenuEntry *entry);

// Suriname (GROUP_01032)
void Suriname_6e87b336d9f4(CTRPluginFramework::MenuEntry *entry);

// マーメイドなポスト (GROUP_01034)
void マーメイドなポスト_6ea2a11ecc66(CTRPluginFramework::MenuEntry *entry);

// まめつぶデパート (GROUP_01035)
void まめつぶデパート_6eae779dbeaf(CTRPluginFramework::MenuEntry *entry);

// 無限に置ける オフ (GROUP_01036)
void 無限に置ける_オフ_6eae8a5490cc(CTRPluginFramework::MenuEntry *entry);

// 2049 (GROUP_01038)
void Cheat_2049_6ec8c003f2ec(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 9999 (GROUP_01039)
void 夢番地下4桁_9999_6ef3b048e97b(CTRPluginFramework::MenuEntry *entry);

// 貯金MAX (GROUP_01041)
void 貯金MAX_6f34c65d0352(CTRPluginFramework::MenuEntry *entry);

// マス変更3x3 (GROUP_01042)
void マス変更3x3_6f3be554c4f9(CTRPluginFramework::MenuEntry *entry);

// 住人7の引っ越し解除 (GROUP_01044)
void 住人7の引っ越し解除_6f8726999ca7(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 4444 (GROUP_01048)
void 夢番地上4桁_4444_7000543144c9(CTRPluginFramework::MenuEntry *entry);

// 立て板の壁 (GROUP_01050)
void 立て板の壁_7014f13bf6ed(CTRPluginFramework::MenuEntry *entry);

// デパート 2F (GROUP_01051)
void デパート_2F_7031be2424be(CTRPluginFramework::MenuEntry *entry);

// 一階(中) (GROUP_01054)
void 一階_中_707f43a7a6f4(CTRPluginFramework::MenuEntry *entry);

// 女28 (GROUP_01055)
void 女28_7096096ddd0e(CTRPluginFramework::MenuEntry *entry);

// Rパーカーズに変更 (GROUP_01056)
void Rパーカーズに変更_70b2acb6f64b(CTRPluginFramework::MenuEntry *entry);

// ダンス (GROUP_01057)
void ダンス_70c671880c0c(CTRPluginFramework::MenuEntry *entry);

// 2042 (GROUP_01060)
void Cheat_2042_7124e9b1611f(CTRPluginFramework::MenuEntry *entry);

// 郵便局 (GROUP_01064)
void 郵便局_7176bd9393ad(CTRPluginFramework::MenuEntry *entry);

// 女32 (GROUP_01067)
void 女32_71f355024db0(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 6666 (GROUP_01068)
void 夢番地下4桁_6666_71fea404159b(CTRPluginFramework::MenuEntry *entry);

// まめつぶ (GROUP_01076)
void まめつぶ_72b09da98925(CTRPluginFramework::MenuEntry *entry);

// 日焼け9 (GROUP_01078)
void 日焼け9_72f5f851d2b8(CTRPluginFramework::MenuEntry *entry);

// 緑のメルヘンな屋根 (GROUP_01082)
void 緑のメルヘンな屋根_7357c111ec15(CTRPluginFramework::MenuEntry *entry);

// 男3 (GROUP_01083)
void 男3_736842bac813(CTRPluginFramework::MenuEntry *entry);

// 横に回る (GROUP_01084)
void 横に回る_73841046fe25(CTRPluginFramework::MenuEntry *entry);

// スーパーまめつぶ (GROUP_01085)
void スーパーまめつぶ_73860757ab60(CTRPluginFramework::MenuEntry *entry);

// 桜量60 (GROUP_01088)
void 桜量60_739cdb9bb95f(CTRPluginFramework::MenuEntry *entry);

// 近未来の壁 (GROUP_01090)
void 近未来の壁_73beb618f0cc(CTRPluginFramework::MenuEntry *entry);

// 10赤茶色 (GROUP_01092)
void Cheat_10赤茶色_73c37024d8de(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 FFFF (GROUP_01094)
void 夢番地上4桁_FFFF_74272dd0186d(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 CCCC (GROUP_01097)
void 夢番地下4桁_CCCC_74a2fc90be28(CTRPluginFramework::MenuEntry *entry);

// パナマ (GROUP_01100)
void パナマ_7545f2ece761(CTRPluginFramework::MenuEntry *entry);

// 茶色の屋根 (GROUP_01104)
void 茶色の屋根_7599f3ead90c(CTRPluginFramework::MenuEntry *entry);

// 男11 (GROUP_01106)
void 男11_75ad79f1b30c(CTRPluginFramework::MenuEntry *entry);

// 5濃い青 (GROUP_01108)
void Cheat_5濃い青_761e6669a545(CTRPluginFramework::MenuEntry *entry);

// コケる (GROUP_01110)
void コケる_76316f61b04e(CTRPluginFramework::MenuEntry *entry);

// うす紫の屋根 (GROUP_01114)
void うす紫の屋根_7645f2725ec3(CTRPluginFramework::MenuEntry *entry);

// トタンの柵 (GROUP_01117)
void トタンの柵_7726ace57e95(CTRPluginFramework::MenuEntry *entry);

// 住人5の引っ越し解除 (GROUP_01119)
void 住人5の引っ越し解除_7753d28cbc27(CTRPluginFramework::MenuEntry *entry);

// 四角い窓付きのドア (GROUP_01120)
void 四角い窓付きのドア_7768644d4d7d(CTRPluginFramework::MenuEntry *entry);

// 日焼け3 (GROUP_01121)
void 日焼け3_776b87c08994(CTRPluginFramework::MenuEntry *entry);

// 早着替え (GROUP_01122)
void 早着替え_77dd6aee6837(CTRPluginFramework::MenuEntry *entry);

// 見せびらかす (GROUP_01125)
void 見せびらかす_78638185dfa4(CTRPluginFramework::MenuEntry *entry);

// カタログマニアG (GROUP_01131)
void カタログマニアG_7951f9693e37(CTRPluginFramework::MenuEntry *entry);

// 物億 (GROUP_01136)
void 物億_79dae16ec8bf(CTRPluginFramework::MenuEntry *entry);

// 男 (GROUP_01141)
void 男_7ae91678d593(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪オン (GROUP_01142)
void 紙吹雪オン_7af7d5d8dabf(CTRPluginFramework::MenuEntry *entry);

// 緑の屋根がわら (GROUP_01146)
void 緑の屋根がわら_7b45b38f1f35(CTRPluginFramework::MenuEntry *entry);

// ハチに刺されなくなる (GROUP_01149)
void ハチに刺されなくなる_7babea2cbaad(CTRPluginFramework::MenuEntry *entry);

// 影がピンク白色になる (GROUP_01154)
void 影がピンク白色になる_7c02ce732fb8(CTRPluginFramework::MenuEntry *entry);

// メルヘンなかこい (GROUP_01158)
void メルヘンなかこい_7c7300178049(CTRPluginFramework::MenuEntry *entry);

// 住人7 (GROUP_01159)
void 住人7_7c7b6fd20a36(CTRPluginFramework::MenuEntry *entry);

// スネーク乗っ取りするときオン (GROUP_01161)
void スネーク乗っ取りするときオン_7cc69bda8e06(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 8888 (GROUP_01162)
void 夢番地上4桁_8888_7cf35b866985(CTRPluginFramework::MenuEntry *entry);

// 雲が青色になる (GROUP_01165)
void 雲が青色になる_7d33dade44e2(CTRPluginFramework::MenuEntry *entry);

// 2020 (GROUP_01168)
void Cheat_2020_7da06cfaf0c4(CTRPluginFramework::MenuEntry *entry);

// ビューティーサロン (GROUP_01175)
void ビューティーサロン_7df3838133f8(CTRPluginFramework::MenuEntry *entry);

// 連続リアクション (GROUP_01176)
void 連続リアクション_7e1c2cbcd7c3(CTRPluginFramework::MenuEntry *entry);

// 青いでこぼこ屋根 (GROUP_01182)
void 青いでこぼこ屋根_7e96858232b2(CTRPluginFramework::MenuEntry *entry);

// 最大 (GROUP_01184)
void 最大_7ed72abd1b34(CTRPluginFramework::MenuEntry *entry);

// コントラスト (GROUP_01185)
void コントラスト_7efd73326fa7(CTRPluginFramework::MenuEntry *entry);

// 改造バッジ銅 (GROUP_01186)
void 改造バッジ銅_7f0648d1728f(CTRPluginFramework::MenuEntry *entry);

// 黄金のポスト (GROUP_01187)
void 黄金のポスト_7f067386e17a(CTRPluginFramework::MenuEntry *entry);

// 女 (GROUP_01194)
void 女_7f755aae4612(CTRPluginFramework::MenuEntry *entry);

// クラゲに刺されても即解除 [R] (GROUP_01196)
void クラゲに刺されても即解除_R_7f9b3e47f6e9(CTRPluginFramework::MenuEntry *entry);

// 美容院 未完成 (GROUP_01199)
void 美容院_未完成_8068ea9d0147(CTRPluginFramework::MenuEntry *entry);

// 住人6の引っ越し解除 (GROUP_01200)
void 住人6の引っ越し解除_8070e993644b(CTRPluginFramework::MenuEntry *entry);

// オノ2 (GROUP_01203)
void オノ2_80c3cfc34a1c(CTRPluginFramework::MenuEntry *entry);

// 茶色いレンガの壁 (GROUP_01204)
void 茶色いレンガの壁_80d4f9f2e43e(CTRPluginFramework::MenuEntry *entry);

// 斧で岩割る (GROUP_01206)
void 斧で岩割る_810ae5db1400(CTRPluginFramework::MenuEntry *entry);

// 一階(小) (GROUP_01210)
void 一階_小_819c795ecc42(CTRPluginFramework::MenuEntry *entry);

// 青いレンガの敷石 (GROUP_01213)
void 青いレンガの敷石_81c993d2bcb6(CTRPluginFramework::MenuEntry *entry);

// Guyana (GROUP_01215)
void Guyana_81d2c864c025(CTRPluginFramework::MenuEntry *entry);

// カーニバルダンス4 (GROUP_01218)
void カーニバルダンス4_8219478d4752(CTRPluginFramework::MenuEntry *entry);

// 拡張機能 (GROUP_01219)
void 拡張機能_822e9c00587d(CTRPluginFramework::MenuEntry *entry);

// Saint Vincent and Grenadines (GROUP_01225)
void Saint_Vincent_and_Grenadines_834b0b7692a9(CTRPluginFramework::MenuEntry *entry);

// 2048 (GROUP_01226)
void Cheat_2048_83558c19772e(CTRPluginFramework::MenuEntry *entry);

// オレンジのわらぶき屋根 (GROUP_01229)
void オレンジのわらぶき屋根_8369624dabe7(CTRPluginFramework::MenuEntry *entry);

// 地面の一部が消える (GROUP_01242)
void 地面の一部が消える_8522ecfadfe1(CTRPluginFramework::MenuEntry *entry);

// 気絶(外) (動作がおかしくなった時実行) (GROUP_01258)
void 気絶_外_動作がおかしくなった時実行_86800c14a803(CTRPluginFramework::MenuEntry *entry);

// 男7 (GROUP_01261)
void 男7_86f607f233ea(CTRPluginFramework::MenuEntry *entry);

// USA (GROUP_01264)
void USA_879ca25767b2(CTRPluginFramework::MenuEntry *entry);

// 影が白色になる (GROUP_01265)
void 影が白色になる_87bca8d61063(CTRPluginFramework::MenuEntry *entry);

// CLUB 444 (GROUP_01267)
void CLUB_444_87d54a55b27d(CTRPluginFramework::MenuEntry *entry);

// オートドロップ3x3 (GROUP_01268)
void オートドロップ3x3_8821626fdd4b(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 AAAA (GROUP_01271)
void 夢番地中4桁_AAAA_8848cd439d78(CTRPluginFramework::MenuEntry *entry);

// 影が赤色になる (GROUP_01272)
void 影が赤色になる_88564e47c5fb(CTRPluginFramework::MenuEntry *entry);

// 四角い石畳 (GROUP_01274)
void 四角い石畳_886d0b6a729f(CTRPluginFramework::MenuEntry *entry);

// 夢見の館 完成 (GROUP_01282)
void 夢見の館_完成_89128f120350(CTRPluginFramework::MenuEntry *entry);

// 2033 (GROUP_01283)
void Cheat_2033_8955b9e2c985(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 1111 (GROUP_01284)
void 夢番地上4桁_1111_89ac711a0a7c(CTRPluginFramework::MenuEntry *entry);

// コンクリートの塀 (GROUP_01291)
void コンクリートの塀_8a30c6da3800(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量15 (GROUP_01292)
void 紙吹雪量15_8a369c478cd9(CTRPluginFramework::MenuEntry *entry);

// 15明るい紫 (GROUP_01294)
void Cheat_15明るい紫_8a81a5234251(CTRPluginFramework::MenuEntry *entry);

// 足で消す途中 (GROUP_01296)
void 足で消す途中_8ada41e5fffa(CTRPluginFramework::MenuEntry *entry);

// キノコ (GROUP_01297)
void キノコ_8adcb200f8b0(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作 普通 (GROUP_01299)
void 岩壊す動作_普通_8b0f0b41aa16(CTRPluginFramework::MenuEntry *entry);

// ピンクの壁 (GROUP_01300)
void ピンクの壁_8b57a53c767a(CTRPluginFramework::MenuEntry *entry);

// 早口 (GROUP_01301)
void 早口_8b63826732b9(CTRPluginFramework::MenuEntry *entry);

// 白いレンガの壁 (GROUP_01302)
void 白いレンガの壁_8b6b53aeaf7b(CTRPluginFramework::MenuEntry *entry);

// 日焼け8 (GROUP_01303)
void 日焼け8_8b72174130db(CTRPluginFramework::MenuEntry *entry);

// Nicaragua (GROUP_01305)
void Nicaragua_8bc72e64005d(CTRPluginFramework::MenuEntry *entry);

// 青いマーメイドのかこい (GROUP_01306)
void 青いマーメイドのかこい_8bcc3111e112(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 6666 (GROUP_01307)
void 夢番地上4桁_6666_8bd15418bec5(CTRPluginFramework::MenuEntry *entry);

// 自分の位置にテレポート (GROUP_01308)
void 自分の位置にテレポート_8beae8b25350(CTRPluginFramework::MenuEntry *entry);

// 穴から出られない (GROUP_01317)
void 穴から出られない_8c692dab65d7(CTRPluginFramework::MenuEntry *entry);

// 水 (GROUP_01323)
void 水_8d0fc8fac1b7(CTRPluginFramework::MenuEntry *entry);

// 日焼け2 (GROUP_01326)
void 日焼け2_8d73c01c4b75(CTRPluginFramework::MenuEntry *entry);

// 白い板壁 (GROUP_01327)
void 白い板壁_8d816669294c(CTRPluginFramework::MenuEntry *entry);

// 1茶色 (GROUP_01328)
void Cheat_1茶色_8d91b722d0e2(CTRPluginFramework::MenuEntry *entry);

// 空以外が真っ暗になる (GROUP_01330)
void 空以外が真っ暗になる_8da12c67dc6b(CTRPluginFramework::MenuEntry *entry);

// コロンビア (GROUP_01331)
void コロンビア_8dbc880ca7a8(CTRPluginFramework::MenuEntry *entry);

// 穴落ちる (GROUP_01335)
void 穴落ちる_8e504380cd6c(CTRPluginFramework::MenuEntry *entry);

// 雲が赤色になる (GROUP_01336)
void 雲が赤色になる_8e5774a0d10b(CTRPluginFramework::MenuEntry *entry);

// 覗き込む (GROUP_01337)
void 覗き込む_8e59a63e34d9(CTRPluginFramework::MenuEntry *entry);

// 2040 (GROUP_01338)
void Cheat_2040_8e8327323d1b(CTRPluginFramework::MenuEntry *entry);

// とぶ (GROUP_01340)
void とぶ_8eb2d6188d90(CTRPluginFramework::MenuEntry *entry);

// カラフルな丸ドア (GROUP_01344)
void カラフルな丸ドア_8f7edb66c15d(CTRPluginFramework::MenuEntry *entry);

// 占いの館 完成 (GROUP_01347)
void 占いの館_完成_8fc380ae4c52(CTRPluginFramework::MenuEntry *entry);

// 何かを捕まえる (GROUP_01354)
void 何かを捕まえる_90b9e3560750(CTRPluginFramework::MenuEntry *entry);

// 黒い板壁 (GROUP_01355)
void 黒い板壁_90e198f502c3(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 FFFF (GROUP_01357)
void 夢番地下4桁_FFFF_9114cb7da9a6(CTRPluginFramework::MenuEntry *entry);

// 改造バッジ銀 (GROUP_01367)
void 改造バッジ銀_920ac3a76e19(CTRPluginFramework::MenuEntry *entry);

// 回転岩ドロップ (GROUP_01373)
void 回転岩ドロップ_92b34391a3e5(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 0000 (GROUP_01376)
void 夢番地下4桁_0000_92d3bfb02049(CTRPluginFramework::MenuEntry *entry);

// 金バッジ (GROUP_01377)
void 金バッジ_936c6c1b0f91(CTRPluginFramework::MenuEntry *entry);

// 男2 (GROUP_01380)
void 男2_938f95ddbd03(CTRPluginFramework::MenuEntry *entry);

// 足で消して岩ドロップ (GROUP_01382)
void 足で消して岩ドロップ_93cde260a3f9(CTRPluginFramework::MenuEntry *entry);

// マーメイドな壁 (GROUP_01383)
void マーメイドな壁_93d202ed32a1(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(ピッピッピーッ!) (GROUP_01384)
void 音反映チート_ピッピッピーッ_9428c5f23e56(CTRPluginFramework::MenuEntry *entry);

// 日焼け12 (GROUP_01391)
void 日焼け12_95093a908387(CTRPluginFramework::MenuEntry *entry);

// あわてる (GROUP_01394)
void あわてる_953defc9bf80(CTRPluginFramework::MenuEntry *entry);

// 雪玉 (GROUP_01396)
void 雪玉_958df10248b4(CTRPluginFramework::MenuEntry *entry);

// 視界が広くなるon (GROUP_01397)
void 視界が広くなるon_9591bc30aa4d(CTRPluginFramework::MenuEntry *entry);

// 3緑 (GROUP_01398)
void Cheat_3緑_95a137dc388e(CTRPluginFramework::MenuEntry *entry);

// hikkonuku (GROUP_01399)
void hikkonuku_95bf5e9f9619(CTRPluginFramework::MenuEntry *entry);

// 博物館2階 左奥 (GROUP_01401)
void 博物館2階_左奥_96107c79ec49(CTRPluginFramework::MenuEntry *entry);

// けろっぴ (GROUP_01402)
void けろっぴ_965675cd2a1e(CTRPluginFramework::MenuEntry *entry);

// 紙吹雪量60 (GROUP_01405)
void 紙吹雪量60_96fb9ab6f3e7(CTRPluginFramework::MenuEntry *entry);

// 軽量 (GROUP_01410)
void 軽量_97c9057ff985(CTRPluginFramework::MenuEntry *entry);

// ラッコ (GROUP_01412)
void ラッコ_97d54841f6c9(CTRPluginFramework::MenuEntry *entry);

// ゲームコイン (GROUP_01413)
void ゲームコイン_97dbc560ba3e(CTRPluginFramework::MenuEntry *entry);

// お引取りBOX機能変更 (GROUP_01417)
void お引取りBOX機能変更_981b3a7a5279(CTRPluginFramework::MenuEntry *entry);

// 謎の動き (GROUP_01419)
void 謎の動き_982ad163c82a(CTRPluginFramework::MenuEntry *entry);

// コンクリートの壁 (GROUP_01420)
void コンクリートの壁_98398e3729b9(CTRPluginFramework::MenuEntry *entry);

// 掘る (GROUP_01422)
void 掘る_986e231e444d(CTRPluginFramework::MenuEntry *entry);

// クラゲ刺される瞬間 (GROUP_01427)
void クラゲ刺される瞬間_990422175819(CTRPluginFramework::MenuEntry *entry);

// お気に入り2 (GROUP_01428)
void お気に入り2_993d5fe29b76(CTRPluginFramework::MenuEntry *entry);

// たるのポスト (GROUP_01429)
void たるのポスト_9950b44ef3bf(CTRPluginFramework::MenuEntry *entry);

// カーニバルダンス2 (GROUP_01431)
void カーニバルダンス2_9986f4e140a9(CTRPluginFramework::MenuEntry *entry);

// 影が緑色になる (GROUP_01433)
void 影が緑色になる_99c4f1d02f0d(CTRPluginFramework::MenuEntry *entry);

// cmd作成用 (GROUP_01434)
void cmd作成用_99ea68f1f82e(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧右 魚 (GROUP_01435)
void 博物館1階_奧右_魚_9a0b5e4287cc(CTRPluginFramework::MenuEntry *entry);

// 青い屋根 (GROUP_01437)
void 青い屋根_9a5826d309c2(CTRPluginFramework::MenuEntry *entry);

// スペシャルをカーニバル4にする (GROUP_01438)
void スペシャルをカーニバル4にする_9a672356446b(CTRPluginFramework::MenuEntry *entry);

// ~#00FFFF自分に (GROUP_01442)
void Cheat_00FFFF自分に_9ab65d48da52(CTRPluginFramework::MenuEntry *entry);

// 住人5 (GROUP_01443)
void 住人5_9ab8cb6ea9e5(CTRPluginFramework::MenuEntry *entry);

// 住人8 (GROUP_01450)
void 住人8_9b78ef89a80e(CTRPluginFramework::MenuEntry *entry);

// 傘閉じて消える (GROUP_01451)
void 傘閉じて消える_9b7b83a1e3a5(CTRPluginFramework::MenuEntry *entry);

// 全部銅 (GROUP_01452)
void 全部銅_9ba7bed8f8bc(CTRPluginFramework::MenuEntry *entry);

// 改造バッジ金 (GROUP_01453)
void 改造バッジ金_9bb1101bbfbf(CTRPluginFramework::MenuEntry *entry);

// 足で消す (GROUP_01457)
void 足で消す_9bf03fc3fa25(CTRPluginFramework::MenuEntry *entry);

// じゃんけん1 (GROUP_01458)
void じゃんけん1_9c0da24f4864(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 EEEE (GROUP_01459)
void 夢番地下4桁_EEEE_9c1e538178da(CTRPluginFramework::MenuEntry *entry);

// 夢見の館 未完成 (GROUP_01460)
void 夢見の館_未完成_9c3a15c496cb(CTRPluginFramework::MenuEntry *entry);

// ピンクのポスト (GROUP_01461)
void ピンクのポスト_9c456cc505c6(CTRPluginFramework::MenuEntry *entry);

// 住人1の引っ越し (GROUP_01462)
void 住人1の引っ越し_9c75ec0b00a0(CTRPluginFramework::MenuEntry *entry);

// Guamaterra (GROUP_01464)
void Guamaterra_9cadf55186d3(CTRPluginFramework::MenuEntry *entry);

// 何でも回転で消せる (GROUP_01465)
void 何でも回転で消せる_9d31cdfbe3aa(CTRPluginFramework::MenuEntry *entry);

// kaiten (GROUP_01467)
void kaiten_9d9675df452a(CTRPluginFramework::MenuEntry *entry);

// ピンクの柵 (GROUP_01468)
void ピンクの柵_9da2faab54a8(CTRPluginFramework::MenuEntry *entry);

// サブ2 -> 自分 (GROUP_01473)
void サブ2_自分_9e27c86bbfbe(CTRPluginFramework::MenuEntry *entry);

// 灰色のレンガのかこい (GROUP_01474)
void 灰色のレンガのかこい_9e2ab25f336b(CTRPluginFramework::MenuEntry *entry);

// ぼろい丸ドア (GROUP_01475)
void ぼろい丸ドア_9e49a8503340(CTRPluginFramework::MenuEntry *entry);

// 重量 (GROUP_01481)
void 重量_9ec146c487ad(CTRPluginFramework::MenuEntry *entry);

// 乗っ取り snakeなど (GROUP_01483)
void 乗っ取り_snakeなど_9f3fa606cd05(CTRPluginFramework::MenuEntry *entry);

// エラー (GROUP_01484)
void エラー_9f4cb33ee6a8(CTRPluginFramework::MenuEntry *entry);

// Honduras (GROUP_01490)
void Honduras_9fd6c324cee1(CTRPluginFramework::MenuEntry *entry);

// 茶色い敷石 (GROUP_01492)
void 茶色い敷石_a01f679637ff(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧右奥2 魚 (GROUP_01493)
void 博物館1階_奧右奥2_魚_a0395834def0(CTRPluginFramework::MenuEntry *entry);

// 22222 (GROUP_01494)
void Cheat_22222_a03a88b60c76(CTRPluginFramework::MenuEntry *entry);

// 2037 (GROUP_01496)
void Cheat_2037_a0636d0598dd(CTRPluginFramework::MenuEntry *entry);

// 女22 (GROUP_01497)
void 女22_a0654e5b122d(CTRPluginFramework::MenuEntry *entry);

// 植える (GROUP_01498)
void 植える_a0e9b9f3d5db(CTRPluginFramework::MenuEntry *entry);

// メガホン1 (GROUP_01499)
void メガホン1_a114a71e94cc(CTRPluginFramework::MenuEntry *entry);

// 特殊配列1 (GROUP_01505)
void 特殊配列1_a1d66641c166(CTRPluginFramework::MenuEntry *entry);

// クラゲに刺されても即解除 (GROUP_01508)
void クラゲに刺されても即解除_a1ea03357610(CTRPluginFramework::MenuEntry *entry);

// クラゲ刺された後 (GROUP_01510)
void クラゲ刺された後_a228bc3859b1(CTRPluginFramework::MenuEntry *entry);

// 2027 (GROUP_01519)
void Cheat_2027_a30068a55a8d(CTRPluginFramework::MenuEntry *entry);

// わからん (GROUP_01520)
void わからん_a305c4849ace(CTRPluginFramework::MenuEntry *entry);

// 青いメルヘンな丸ドア (GROUP_01522)
void 青いメルヘンな丸ドア_a341b14106a3(CTRPluginFramework::MenuEntry *entry);

// 2021 (GROUP_01527)
void Cheat_2021_a3bb957f725e(CTRPluginFramework::MenuEntry *entry);

// 海入る (GROUP_01530)
void 海入る_a3fc04892c04(CTRPluginFramework::MenuEntry *entry);

// 日焼け7 (GROUP_01534)
void 日焼け7_a41f368f7712(CTRPluginFramework::MenuEntry *entry);

// 3D風 (GROUP_01535)
void Cheat_3D風_a44b5e684fd6(CTRPluginFramework::MenuEntry *entry);

// スペシャルバッチ-B (GROUP_01540)
void スペシャルバッチ_B_a48d4ff216d4(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作 埋める (GROUP_01543)
void 岩壊す動作_埋める_a53ff506111f(CTRPluginFramework::MenuEntry *entry);

// トタンの壁 (GROUP_01545)
void トタンの壁_a5b02fcc77b0(CTRPluginFramework::MenuEntry *entry);

// マイメロ (GROUP_01552)
void マイメロ_a655399b6161(CTRPluginFramework::MenuEntry *entry);

// 家 (GROUP_01555)
void 家_a6a590027898(CTRPluginFramework::MenuEntry *entry);

// 女21 (GROUP_01557)
void 女21_a6c06f902431(CTRPluginFramework::MenuEntry *entry);

// 丸いドア (GROUP_01558)
void 丸いドア_a6cb3988e5a9(CTRPluginFramework::MenuEntry *entry);

// 全部無し (GROUP_01560)
void 全部無し_a6e2f213aef7(CTRPluginFramework::MenuEntry *entry);

// 表示 (GROUP_01566)
void 表示_a79e2cf61ff5(CTRPluginFramework::MenuEntry *entry);

// サーモグラフィー (GROUP_01572)
void サーモグラフィー_a813a0f9306c(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(なんか起動する) (GROUP_01573)
void 音反映チート_なんか起動する_a82c29e0dbcf(CTRPluginFramework::MenuEntry *entry);

// 黒くちかちか (GROUP_01577)
void 黒くちかちか_a8b50c85fb11(CTRPluginFramework::MenuEntry *entry);

// 2038 (GROUP_01579)
void Cheat_2038_a8ce2acbad09(CTRPluginFramework::MenuEntry *entry);

// パネポン必殺技ゲージMAX (GROUP_01581)
void パネポン必殺技ゲージMAX_a8f91d9efff5(CTRPluginFramework::MenuEntry *entry);

// カフェに変更 (GROUP_01586)
void カフェに変更_a98af19e95b3(CTRPluginFramework::MenuEntry *entry);

// 住人2の引っ越し (GROUP_01592)
void 住人2の引っ越し_aa5785d19407(CTRPluginFramework::MenuEntry *entry);

// 2茶色 (GROUP_01597)
void Cheat_2茶色_aaba3def9d3e(CTRPluginFramework::MenuEntry *entry);

// 埋まって岩ドロップ (GROUP_01598)
void 埋まって岩ドロップ_aac7dfdc2404(CTRPluginFramework::MenuEntry *entry);

// オレンジの壁 (GROUP_01599)
void オレンジの壁_aad0e9f0aec8(CTRPluginFramework::MenuEntry *entry);

// スペシャルをミニサイズにする (GROUP_01601)
void スペシャルをミニサイズにする_aaf1ff9fff43(CTRPluginFramework::MenuEntry *entry);

// 謎 (GROUP_01602)
void 謎_aaf3668cb8a1(CTRPluginFramework::MenuEntry *entry);

// 9黒 (GROUP_01603)
void Cheat_9黒_aafa359f8bc4(CTRPluginFramework::MenuEntry *entry);

// 竹の柵 (GROUP_01605)
void 竹の柵_ab16f8f17e9e(CTRPluginFramework::MenuEntry *entry);

// 紫 (GROUP_01607)
void 紫_ab33b1cdca0b(CTRPluginFramework::MenuEntry *entry);

// 住人10 (GROUP_01613)
void 住人10_abf920159f2e(CTRPluginFramework::MenuEntry *entry);

// ようふうのおしろ (GROUP_01614)
void ようふうのおしろ_ac03463cd4ff(CTRPluginFramework::MenuEntry *entry);

// 着替え (GROUP_01624)
void 着替え_acf1f93b3e9c(CTRPluginFramework::MenuEntry *entry);

// 女23 (GROUP_01625)
void 女23_ad1e13d80615(CTRPluginFramework::MenuEntry *entry);

// 揺らして岩ドロップ (GROUP_01632)
void 揺らして岩ドロップ_ae2bd057c717(CTRPluginFramework::MenuEntry *entry);

// 四角い茶色のドア (GROUP_01635)
void 四角い茶色のドア_ae9c7e4409e2(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 手前右 美術品 (GROUP_01638)
void 博物館1階_手前右_美術品_aed74e1b353e(CTRPluginFramework::MenuEntry *entry);

// カタログコンプリート (GROUP_01639)
void カタログコンプリート_af051f62e5a6(CTRPluginFramework::MenuEntry *entry);

// 横にドン (GROUP_01640)
void 横にドン_af0fb40cd57b(CTRPluginFramework::MenuEntry *entry);

// どこでも掘れる (GROUP_01649)
void どこでも掘れる_b137d913f71b(CTRPluginFramework::MenuEntry *entry);

// 右の部屋 (GROUP_01656)
void 右の部屋_b1b85e229da2(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作 切り株 (GROUP_01657)
void 岩壊す動作_切り株_b1f542b42dac(CTRPluginFramework::MenuEntry *entry);

// 貼る (GROUP_01658)
void 貼る_b23bf548200e(CTRPluginFramework::MenuEntry *entry);

// 揺れる (GROUP_01660)
void 揺れる_b2e6c08c3154(CTRPluginFramework::MenuEntry *entry);

// 女34 (GROUP_01662)
void 女34_b337f41587c0(CTRPluginFramework::MenuEntry *entry);

// ペグとロープ (GROUP_01668)
void ペグとロープ_b3d9faefbd5a(CTRPluginFramework::MenuEntry *entry);

// やりつく (GROUP_01669)
void やりつく_b3f705c444cb(CTRPluginFramework::MenuEntry *entry);

// 黄色い屋根 (GROUP_01674)
void 黄色い屋根_b44d614e232f(CTRPluginFramework::MenuEntry *entry);

// 4水色 (GROUP_01675)
void Cheat_4水色_b46c3866cbd0(CTRPluginFramework::MenuEntry *entry);

// 6青 (GROUP_01677)
void Cheat_6青_b4963d6bbce8(CTRPluginFramework::MenuEntry *entry);

// 四角いピンクのドア (GROUP_01680)
void 四角いピンクのドア_b4c9df7f09a5(CTRPluginFramework::MenuEntry *entry);

// 直立時の呼吸 (GROUP_01683)
void 直立時の呼吸_b530388a8a15(CTRPluginFramework::MenuEntry *entry);

// 住人5の引っ越し (GROUP_01686)
void 住人5の引っ越し_b587f69d9c1e(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 EEEE (GROUP_01687)
void 夢番地中4桁_EEEE_b588572e9b84(CTRPluginFramework::MenuEntry *entry);

// 左の部屋 (GROUP_01690)
void 左の部屋_b5daa8ecd72d(CTRPluginFramework::MenuEntry *entry);

// ピンクのきわくの壁 (GROUP_01692)
void ピンクのきわくの壁_b63ae14b9f63(CTRPluginFramework::MenuEntry *entry);

// 博物館2階 右手前 (GROUP_01695)
void 博物館2階_右手前_b66e5ba570b6(CTRPluginFramework::MenuEntry *entry);

// 乗っ取りバグ防止 (GROUP_01697)
void 乗っ取りバグ防止_b6df80ecff34(CTRPluginFramework::MenuEntry *entry);

// 博物館2階 左手前 (GROUP_01698)
void 博物館2階_左手前_b6f8ed7736bd(CTRPluginFramework::MenuEntry *entry);

// CLUB444 営業前 (GROUP_01701)
void CLUB444_営業前_b7434334ccb7(CTRPluginFramework::MenuEntry *entry);

// 穴に落ちても即脱出 [R] (GROUP_01702)
void 穴に落ちても即脱出_R_b7449d8c3983(CTRPluginFramework::MenuEntry *entry);

// 四角いドア (GROUP_01706)
void 四角いドア_b76a7e7c48f0(CTRPluginFramework::MenuEntry *entry);

// お菓子の屋根 (GROUP_01707)
void お菓子の屋根_b78f9cb02210(CTRPluginFramework::MenuEntry *entry);

// Rパーカーズ (GROUP_01709)
void Rパーカーズ_b7e10f9e44d1(CTRPluginFramework::MenuEntry *entry);

// ステンレスなポスト (GROUP_01710)
void ステンレスなポスト_b81f0caf4d06(CTRPluginFramework::MenuEntry *entry);

// ウオマサテント屋根裏 (GROUP_01711)
void ウオマサテント屋根裏_b8516e67d2cb(CTRPluginFramework::MenuEntry *entry);

// 飲む (GROUP_01720)
void 飲む_b93ac9071e21(CTRPluginFramework::MenuEntry *entry);

// 7ピンク (GROUP_01722)
void Cheat_7ピンク_b9451b265e75(CTRPluginFramework::MenuEntry *entry);

// さきゅの服装セット (GROUP_01723)
void さきゅの服装セット_b98da791309c(CTRPluginFramework::MenuEntry *entry);

// 黄色い壁 (GROUP_01726)
void 黄色い壁_b9f1c5261a2e(CTRPluginFramework::MenuEntry *entry);

// テクスチャ変更2 (GROUP_01727)
void テクスチャ変更2_b9f27fed620e(CTRPluginFramework::MenuEntry *entry);

// 44444 (GROUP_01728)
void Cheat_44444_ba009f00dd8f(CTRPluginFramework::MenuEntry *entry);

// 四角い鉄のドア (GROUP_01736)
void 四角い鉄のドア_bab7b7ee1d90(CTRPluginFramework::MenuEntry *entry);

// 頭の上にエフェクト表示 (GROUP_01739)
void 頭の上にエフェクト表示_bb40dbb26149(CTRPluginFramework::MenuEntry *entry);

// 丸窓の丸ドア (GROUP_01740)
void 丸窓の丸ドア_bb479ac658ad(CTRPluginFramework::MenuEntry *entry);

// 四角いカラフルなドア (GROUP_01741)
void 四角いカラフルなドア_bb5b93c200b5(CTRPluginFramework::MenuEntry *entry);

// 11111 (GROUP_01744)
void Cheat_11111_bb790a94a8ef(CTRPluginFramework::MenuEntry *entry);

// ぐー (GROUP_01747)
void ぐー_bbbedc3feb52(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 7777 (GROUP_01755)
void 夢番地中4桁_7777_bc6d198918ae(CTRPluginFramework::MenuEntry *entry);

// カメヤマ表彰式 (GROUP_01758)
void カメヤマ表彰式_bcfbb9b598db(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 9999 (GROUP_01759)
void 夢番地上4桁_9999_bd385c6dcdcf(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 3333 (GROUP_01760)
void 夢番地下4桁_3333_bd96302d6814(CTRPluginFramework::MenuEntry *entry);

// 石の壁 (GROUP_01761)
void 石の壁_bdca473c71eb(CTRPluginFramework::MenuEntry *entry);

// 2017 (GROUP_01769)
void Cheat_2017_be92564a171d(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 DDDD (GROUP_01773)
void 夢番地中4桁_DDDD_bf3e80f242d5(CTRPluginFramework::MenuEntry *entry);

// 緑の屋根 (GROUP_01775)
void 緑の屋根_bf53440e0e4b(CTRPluginFramework::MenuEntry *entry);

// 大きさ変更 (GROUP_01777)
void 大きさ変更_bf83f5c82959(CTRPluginFramework::MenuEntry *entry);

// 2045 (GROUP_01782)
void Cheat_2045_c010bd1aff96(CTRPluginFramework::MenuEntry *entry);

// リメイク中 (GROUP_01787)
void リメイク中_c09996e81dd4(CTRPluginFramework::MenuEntry *entry);

// 和風のかこい (GROUP_01788)
void 和風のかこい_c0b23c3ffb2c(CTRPluginFramework::MenuEntry *entry);

// ドアの開閉 (GROUP_01789)
void ドアの開閉_c0bf0b4e763b(CTRPluginFramework::MenuEntry *entry);

// 16グレー (GROUP_01798)
void Cheat_16グレー_c1778d0b854b(CTRPluginFramework::MenuEntry *entry);

// マーメイドな屋根 (GROUP_01811)
void マーメイドな屋根_c2af146f6096(CTRPluginFramework::MenuEntry *entry);

// Panama (GROUP_01812)
void Panama_c2c21941821e(CTRPluginFramework::MenuEntry *entry);

// クイックモード [+/] (GROUP_01815)
void クイックモード_c2dd54a17bfd(CTRPluginFramework::MenuEntry *entry);

// 桜量15 (GROUP_01826)
void 桜量15_c44b9d0e7f23(CTRPluginFramework::MenuEntry *entry);

// 旗荒ぶる (GROUP_01835)
void 旗荒ぶる_c5a82109cd1e(CTRPluginFramework::MenuEntry *entry);

// 2025 (GROUP_01839)
void Cheat_2025_c5cfd42d50b2(CTRPluginFramework::MenuEntry *entry);

// 女27 (GROUP_01840)
void 女27_c5f8296de46f(CTRPluginFramework::MenuEntry *entry);

// コスタリカ (GROUP_01845)
void コスタリカ_c6a3c2b1fa5f(CTRPluginFramework::MenuEntry *entry);

// 特殊配列3 (GROUP_01846)
void 特殊配列3_c6fa9d05fb96(CTRPluginFramework::MenuEntry *entry);

// 自分と同じ動作をさせる (GROUP_01851)
void 自分と同じ動作をさせる_c75eb0221f07(CTRPluginFramework::MenuEntry *entry);

// こしふり (GROUP_01852)
void こしふり_c76a2a6dd2b0(CTRPluginFramework::MenuEntry *entry);

// 二階 (GROUP_01854)
void 二階_c784e7da3c60(CTRPluginFramework::MenuEntry *entry);

// デパート 1F (GROUP_01856)
void デパート_1F_c7b8a5d3dfeb(CTRPluginFramework::MenuEntry *entry);

// お菓子のポスト (GROUP_01860)
void お菓子のポスト_c85570a33f1a(CTRPluginFramework::MenuEntry *entry);

// スコップ判定解除オフコ (GROUP_01864)
void スコップ判定解除オフコ_c880c6ea7da6(CTRPluginFramework::MenuEntry *entry);

// 引っこ抜く (GROUP_01873)
void 引っこ抜く_c9aa3f276da9(CTRPluginFramework::MenuEntry *entry);

// 占いの館 未完成 (GROUP_01875)
void 占いの館_未完成_c9c82780d6a5(CTRPluginFramework::MenuEntry *entry);

// >< (GROUP_01876)
void Cheat_c9cc4f3fabfa(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 AAAA (GROUP_01878)
void 夢番地下4桁_AAAA_ca504348d640(CTRPluginFramework::MenuEntry *entry);

// スネーク音 (GROUP_01882)
void スネーク音_caad7c378e57(CTRPluginFramework::MenuEntry *entry);

// 謎動作 (GROUP_01893)
void 謎動作_cbc200e3d235(CTRPluginFramework::MenuEntry *entry);

// 女31 (GROUP_01895)
void 女31_cbedc9a0ea98(CTRPluginFramework::MenuEntry *entry);

// 食べる2 (GROUP_01901)
void 食べる2_cc845ef165b0(CTRPluginFramework::MenuEntry *entry);

// 紫の屋根 (GROUP_01903)
void 紫の屋根_cde800286720(CTRPluginFramework::MenuEntry *entry);

// キティ (GROUP_01910)
void キティ_cebc7f6ee194(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 2222 (GROUP_01911)
void 夢番地上4桁_2222_ceddc97244b6(CTRPluginFramework::MenuEntry *entry);

// ムーンジャンプ P4 (GROUP_01913)
void ムーンジャンプ_P4_cf29e2af565e(CTRPluginFramework::MenuEntry *entry);

// 靴屋 未完成 (GROUP_01919)
void 靴屋_未完成_cfcc92f281f2(CTRPluginFramework::MenuEntry *entry);

// 男6 (GROUP_01921)
void 男6_d039f706165a(CTRPluginFramework::MenuEntry *entry);

// 岩壊す動作 掘り出す (GROUP_01928)
void 岩壊す動作_掘り出す_d0df7586c0e4(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 8888 (GROUP_01929)
void 夢番地中4桁_8888_d0e5eb554e81(CTRPluginFramework::MenuEntry *entry);

// 園芸店ホームセンター (GROUP_01934)
void 園芸店ホームセンター_d131562cf0ca(CTRPluginFramework::MenuEntry *entry);

// リゾートな壁 (GROUP_01935)
void リゾートな壁_d15d3b0d27a7(CTRPluginFramework::MenuEntry *entry);

// 影 綺麗 (GROUP_01942)
void 影_綺麗_d235c1ea8830(CTRPluginFramework::MenuEntry *entry);

// 無し (GROUP_01946)
void 無し_d265a7c6add6(CTRPluginFramework::MenuEntry *entry);

// 重い丸ドア (GROUP_01947)
void 重い丸ドア_d27927755bc7(CTRPluginFramework::MenuEntry *entry);

// 全部銀 (GROUP_01949)
void 全部銀_d292241594c5(CTRPluginFramework::MenuEntry *entry);

// 和風な壁 (GROUP_01953)
void 和風な壁_d30e636ec5b7(CTRPluginFramework::MenuEntry *entry);

// バク転 (GROUP_01956)
void バク転_d3548f6d93e2(CTRPluginFramework::MenuEntry *entry);

// 寝る(?) (GROUP_01957)
void 寝る_d3611cbb117d(CTRPluginFramework::MenuEntry *entry);

// 白い柵 (GROUP_01958)
void 白い柵_d36a289cdc90(CTRPluginFramework::MenuEntry *entry);

// めっちゃ怖くなる (GROUP_01959)
void めっちゃ怖くなる_d374b95392ad(CTRPluginFramework::MenuEntry *entry);

// 黄金のドア (GROUP_01962)
void 黄金のドア_d3b7f5f77a2a(CTRPluginFramework::MenuEntry *entry);

// アラブな黄色丸ドア (GROUP_01966)
void アラブな黄色丸ドア_d443dd91aba9(CTRPluginFramework::MenuEntry *entry);

// 日焼け (GROUP_01969)
void 日焼け_d4bc30242b6d(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 FFFF (GROUP_01972)
void 夢番地中4桁_FFFF_d4f281485d89(CTRPluginFramework::MenuEntry *entry);

// リセット監視センターに変更 (GROUP_01977)
void リセット監視センターに変更_d575899ea10f(CTRPluginFramework::MenuEntry *entry);

// カーニバルダンス3 (GROUP_01985)
void カーニバルダンス3_d693edde0662(CTRPluginFramework::MenuEntry *entry);

// 住人4の引っ越し (GROUP_01986)
void 住人4の引っ越し_d6ae6439028f(CTRPluginFramework::MenuEntry *entry);

// 中華な丸ドア (GROUP_01988)
void 中華な丸ドア_d6dbae5e7624(CTRPluginFramework::MenuEntry *entry);

// 全かっぱの位置をもとに戻す (GROUP_01990)
void 全かっぱの位置をもとに戻す_d6f8d2e5bac5(CTRPluginFramework::MenuEntry *entry);

// スペシャルをカーニバル2にする (GROUP_01991)
void スペシャルをカーニバル2にする_d71f55ddddf4(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 7777 (GROUP_01995)
void 夢番地下4桁_7777_d7903b530764(CTRPluginFramework::MenuEntry *entry);

// コンビニまめつぶ (GROUP_01998)
void コンビニまめつぶ_d7c51c400955(CTRPluginFramework::MenuEntry *entry);

// ハニワ場所戻す (GROUP_02001)
void ハニワ場所戻す_d80fd9f4c822(CTRPluginFramework::MenuEntry *entry);

// 男15 (GROUP_02003)
void 男15_d84e9e02eadb(CTRPluginFramework::MenuEntry *entry);

// エクアドル (GROUP_02004)
void エクアドル_d86a3a581738(CTRPluginFramework::MenuEntry *entry);

// オノ4 (GROUP_02007)
void オノ4_d8bea9c3164d(CTRPluginFramework::MenuEntry *entry);

// 靴屋 完成 (GROUP_02008)
void 靴屋_完成_d90ee9cd85e4(CTRPluginFramework::MenuEntry *entry);

// 2030 (GROUP_02013)
void Cheat_2030_d97104c895f4(CTRPluginFramework::MenuEntry *entry);

// 川が堀れるようになる (GROUP_02015)
void 川が堀れるようになる_da0bcb3d7872(CTRPluginFramework::MenuEntry *entry);

// Aボタン押している間置く (GROUP_02021)
void Aボタン押している間置く_daac5dbf79c4(CTRPluginFramework::MenuEntry *entry);

// BIG! (GROUP_02022)
void BIG_dad290286228(CTRPluginFramework::MenuEntry *entry);

// 美容院 工事中 (GROUP_02025)
void 美容院_工事中_db15cda46803(CTRPluginFramework::MenuEntry *entry);

// レンガの敷石 (GROUP_02033)
void レンガの敷石_dbb9b0982923(CTRPluginFramework::MenuEntry *entry);

// 謎の寝方 (GROUP_02034)
void 謎の寝方_dbba06a01128(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(キラーン) (GROUP_02035)
void 音反映チート_キラーン_dbbba73286e9(CTRPluginFramework::MenuEntry *entry);

// 黄金のベンチに変更 (GROUP_02037)
void 黄金のベンチに変更_dbce3152d0b8(CTRPluginFramework::MenuEntry *entry);

// 横に回る2 (GROUP_02038)
void 横に回る2_dc0580fbb25d(CTRPluginFramework::MenuEntry *entry);

// 物置く (GROUP_02040)
void 物置く_dc1107aea49f(CTRPluginFramework::MenuEntry *entry);

// 四角い中華なドア (GROUP_02041)
void 四角い中華なドア_dc2a4f1c1579(CTRPluginFramework::MenuEntry *entry);

// ドミニカ共和国 (GROUP_02045)
void ドミニカ共和国_dc436c818c40(CTRPluginFramework::MenuEntry *entry);

// 四角いベージュのドア (GROUP_02046)
void 四角いベージュのドア_dc50d2e50323(CTRPluginFramework::MenuEntry *entry);

// 他人が自分を押せなくなる (GROUP_02049)
void 他人が自分を押せなくなる_dcaad6569fd3(CTRPluginFramework::MenuEntry *entry);

// 物を置く (GROUP_02050)
void 物を置く_dcc2e1d28201(CTRPluginFramework::MenuEntry *entry);

// 住人9 (GROUP_02052)
void 住人9_dcd2ed558ca1(CTRPluginFramework::MenuEntry *entry);

// 竹の丸ドア (GROUP_02058)
void 竹の丸ドア_dd1063889990(CTRPluginFramework::MenuEntry *entry);

// バラ (GROUP_02060)
void バラ_dd22b6bdb24b(CTRPluginFramework::MenuEntry *entry);

// 2036 (GROUP_02061)
void Cheat_2036_dd31205db5a2(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 CCCC (GROUP_02065)
void 夢番地中4桁_CCCC_ddf8b74b1559(CTRPluginFramework::MenuEntry *entry);

// 連続でオノを振る動作 (GROUP_02069)
void 連続でオノを振る動作_de69f95baa31(CTRPluginFramework::MenuEntry *entry);

// アラブな緑丸ドア (GROUP_02074)
void アラブな緑丸ドア_dec03bf96d74(CTRPluginFramework::MenuEntry *entry);

// 2047 (GROUP_02075)
void Cheat_2047_def1f78c69cd(CTRPluginFramework::MenuEntry *entry);

// 影が金色になる (GROUP_02079)
void 影が金色になる_df4631f8c857(CTRPluginFramework::MenuEntry *entry);

// お菓子の柵 (GROUP_02081)
void お菓子の柵_df7190b132b0(CTRPluginFramework::MenuEntry *entry);

// 四角い丸窓のドア (GROUP_02082)
void 四角い丸窓のドア_df962fd033f4(CTRPluginFramework::MenuEntry *entry);

// 掘れない (GROUP_02089)
void 掘れない_e0652c8659ec(CTRPluginFramework::MenuEntry *entry);

// 2026 (GROUP_02092)
void Cheat_2026_e0a1853cf2d7(CTRPluginFramework::MenuEntry *entry);

// 住人8の引っ越し (GROUP_02094)
void 住人8の引っ越し_e10ee0e3137b(CTRPluginFramework::MenuEntry *entry);

// 魚窓の丸ドア (GROUP_02096)
void 魚窓の丸ドア_e19682285496(CTRPluginFramework::MenuEntry *entry);

// おやしき (GROUP_02103)
void おやしき_e282ef088ea9(CTRPluginFramework::MenuEntry *entry);

// メガホン2 (GROUP_02105)
void メガホン2_e2bbc1cc2cbf(CTRPluginFramework::MenuEntry *entry);

// 高額買取品変更 (GROUP_02106)
void 高額買取品変更_e32ae9e69cc3(CTRPluginFramework::MenuEntry *entry);

// 日焼け10 (GROUP_02109)
void 日焼け10_e35e90f03b52(CTRPluginFramework::MenuEntry *entry);

// オノ3 (GROUP_02110)
void オノ3_e37eb85a88db(CTRPluginFramework::MenuEntry *entry);

// ハチに刺される2 (GROUP_02111)
void ハチに刺される2_e3cca988733c(CTRPluginFramework::MenuEntry *entry);

// オン・オフ "切り替え" (GROUP_02114)
void オン_オフ_切り替え_e3ff55f1ae26(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 BBBB (GROUP_02115)
void 夢番地下4桁_BBBB_e401265d024c(CTRPluginFramework::MenuEntry *entry);

// つねきちのテント (GROUP_02118)
void つねきちのテント_e43c5f51e902(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 DDDD (GROUP_02121)
void 夢番地下4桁_DDDD_e4832201740e(CTRPluginFramework::MenuEntry *entry);

// Martiniqua (GROUP_02123)
void Martiniqua_e4c1b7402916(CTRPluginFramework::MenuEntry *entry);

// よこいたの柵 (GROUP_02127)
void よこいたの柵_e51fdd3968af(CTRPluginFramework::MenuEntry *entry);

// 岩の壁 (GROUP_02130)
void 岩の壁_e53cfac1a185(CTRPluginFramework::MenuEntry *entry);

// 男12 (GROUP_02134)
void 男12_e59093191a26(CTRPluginFramework::MenuEntry *entry);

// OUTO (GROUP_02139)
void OUTO_e5b8deab5bc6(CTRPluginFramework::MenuEntry *entry);

// 空が緑色になる (GROUP_02146)
void 空が緑色になる_e6323462895b(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 DDDD (GROUP_02149)
void 夢番地上4桁_DDDD_e6568f13ecb4(CTRPluginFramework::MenuEntry *entry);

// ベージュの丸ドア (GROUP_02150)
void ベージュの丸ドア_e661f0afa731(CTRPluginFramework::MenuEntry *entry);

// Tポーズ (GROUP_02153)
void Tポーズ_e6943b3ac539(CTRPluginFramework::MenuEntry *entry);

// うく (GROUP_02154)
void うく_e6994766b5fe(CTRPluginFramework::MenuEntry *entry);

// 黒いでこぼこ屋根 (GROUP_02155)
void 黒いでこぼこ屋根_e6bbe334f024(CTRPluginFramework::MenuEntry *entry);

// 夢番地上4桁 3333 (GROUP_02156)
void 夢番地上4桁_3333_e6dabdb39230(CTRPluginFramework::MenuEntry *entry);

// 男10 (GROUP_02159)
void 男10_e71f6d5c5538(CTRPluginFramework::MenuEntry *entry);

// 女30 (GROUP_02162)
void 女30_e73d13851fac(CTRPluginFramework::MenuEntry *entry);

// 植える動作でドロップ (GROUP_02163)
void 植える動作でドロップ_e76b29cdff4c(CTRPluginFramework::MenuEntry *entry);

// 男16 (GROUP_02167)
void 男16_e812de0933da(CTRPluginFramework::MenuEntry *entry);

// ものしまう (GROUP_02168)
void ものしまう_e81ceed6b362(CTRPluginFramework::MenuEntry *entry);

// 2022 (GROUP_02174)
void Cheat_2022_e8cc53905f16(CTRPluginFramework::MenuEntry *entry);

// 強制エラーをする (GROUP_02175)
void 強制エラーをする_e8cfbffe8a87(CTRPluginFramework::MenuEntry *entry);

// ハート風船セット (GROUP_02176)
void ハート風船セット_e8d4431da088(CTRPluginFramework::MenuEntry *entry);

// くち (GROUP_02182)
void くち_e9a29a16f5d6(CTRPluginFramework::MenuEntry *entry);

// 四角いお菓子のドア (GROUP_02183)
void 四角いお菓子のドア_e9b798469ee2(CTRPluginFramework::MenuEntry *entry);

// 13黄色 (GROUP_02184)
void Cheat_13黄色_e9c86a4ff0b0(CTRPluginFramework::MenuEntry *entry);

// 9999999スコア (GROUP_02188)
void Cheat_9999999スコア_ea2d1988d6d6(CTRPluginFramework::MenuEntry *entry);

// 住人3の引っ越し (GROUP_02191)
void 住人3の引っ越し_eaa39092e439(CTRPluginFramework::MenuEntry *entry);

// 四角い近未来のドア (GROUP_02193)
void 四角い近未来のドア_eabc16d89cf9(CTRPluginFramework::MenuEntry *entry);

// 音反映チート(唸り声) (GROUP_02196)
void 音反映チート_唸り声_eb6ad3024c5d(CTRPluginFramework::MenuEntry *entry);

// オレンジのポスト (GROUP_02203)
void オレンジのポスト_ec0f2ae54ed4(CTRPluginFramework::MenuEntry *entry);

// 画面圧縮 (GROUP_02204)
void 画面圧縮_ec16a7b6d4b7(CTRPluginFramework::MenuEntry *entry);

// 砂浜が真っ白 (GROUP_02214)
void 砂浜が真っ白_ed7c656d16ba(CTRPluginFramework::MenuEntry *entry);

// 黄金の壁 (GROUP_02215)
void 黄金の壁_eda2112c60f9(CTRPluginFramework::MenuEntry *entry);

// 狸ハウジング (GROUP_02216)
void 狸ハウジング_eda2dc2dc956(CTRPluginFramework::MenuEntry *entry);

// 穴埋める (GROUP_02220)
void 穴埋める_ee3b3ce27987(CTRPluginFramework::MenuEntry *entry);

// デパート(商店街のみ) (GROUP_02226)
void デパート_商店街のみ_eec64a111dbd(CTRPluginFramework::MenuEntry *entry);

// 夢番地下4桁 5555 (GROUP_02227)
void 夢番地下4桁_5555_ef01732ba1df(CTRPluginFramework::MenuEntry *entry);

// ツアーのロボットムーンジャンプ (GROUP_02229)
void ツアーのロボットムーンジャンプ_ef10a595afe4(CTRPluginFramework::MenuEntry *entry);

// リゾートなポスト (GROUP_02231)
void リゾートなポスト_ef4a742495f2(CTRPluginFramework::MenuEntry *entry);

// サブ1 -> 自分 (GROUP_02232)
void サブ1_自分_ef9f65041a30(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 奧右奥1 魚 (GROUP_02238)
void 博物館1階_奧右奥1_魚_f03fe1eb29c4(CTRPluginFramework::MenuEntry *entry);

// 2035 (GROUP_02239)
void Cheat_2035_f0510901c283(CTRPluginFramework::MenuEntry *entry);

// 岩砕く動作でドロップ (GROUP_02241)
void 岩砕く動作でドロップ_f07098f05638(CTRPluginFramework::MenuEntry *entry);

// 4濃い緑 (GROUP_02242)
void Cheat_4濃い緑_f0726ccd2153(CTRPluginFramework::MenuEntry *entry);

// 音程 (GROUP_02244)
void 音程_f07d1e2bfbf0(CTRPluginFramework::MenuEntry *entry);

// 白いブロック塀 (GROUP_02251)
void 白いブロック塀_f153a68397a8(CTRPluginFramework::MenuEntry *entry);

// 緑のモダンな屋根 (GROUP_02258)
void 緑のモダンな屋根_f216892009db(CTRPluginFramework::MenuEntry *entry);

// 連続で扉を開ける動作 (GROUP_02259)
void 連続で扉を開ける動作_f2359127fb69(CTRPluginFramework::MenuEntry *entry);

// 男8 (GROUP_02265)
void 男8_f2964c056e80(CTRPluginFramework::MenuEntry *entry);

// 11赤色 (GROUP_02266)
void Cheat_11赤色_f29b547e28f1(CTRPluginFramework::MenuEntry *entry);

// 豪華なフェンス (GROUP_02271)
void 豪華なフェンス_f344c3629b60(CTRPluginFramework::MenuEntry *entry);

// 桜量250 (GROUP_02272)
void 桜量250_f3741b04bfed(CTRPluginFramework::MenuEntry *entry);

// 穴を埋める動作変更(切り株) (GROUP_02273)
void 穴を埋める動作変更_切り株_f380cdb33bbc(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 4444 (GROUP_02277)
void 夢番地中4桁_4444_f431a78a7fcb(CTRPluginFramework::MenuEntry *entry);

// Test (GROUP_02278)
void Test_f458c7ac3809(CTRPluginFramework::MenuEntry *entry);

// 飛び込めない (GROUP_02280)
void 飛び込めない_f46e9def0544(CTRPluginFramework::MenuEntry *entry);

// 2015 (GROUP_02283)
void Cheat_2015_f48907bdd17d(CTRPluginFramework::MenuEntry *entry);

// 壁貫通 (GROUP_02284)
void 壁貫通_f4b81acc5da8(CTRPluginFramework::MenuEntry *entry);

// しまえない (GROUP_02285)
void しまえない_f4babcec797b(CTRPluginFramework::MenuEntry *entry);

// 夢番地中4桁 5555 (GROUP_02289)
void 夢番地中4桁_5555_f4fc78c0f594(CTRPluginFramework::MenuEntry *entry);

// 住人10の引っ越し (GROUP_02290)
void 住人10の引っ越し_f5092f03b69f(CTRPluginFramework::MenuEntry *entry);

// 住人3の引っ越し解除 (GROUP_02294)
void 住人3の引っ越し解除_f584701a1dc5(CTRPluginFramework::MenuEntry *entry);

// 銅バッジ (GROUP_02297)
void 銅バッジ_f5e1deb50253(CTRPluginFramework::MenuEntry *entry);

// 博物館1階 手前左 化石2 (GROUP_02300)
void 博物館1階_手前左_化石2_f62def65e05f(CTRPluginFramework::MenuEntry *entry);

// 女24 (GROUP_02301)
void 女24_f6435dd17d24(CTRPluginFramework::MenuEntry *entry);

// 2043 (GROUP_02302)
void Cheat_2043_f6580f9fdec2(CTRPluginFramework::MenuEntry *entry);

// ウオマサ表彰式 (GROUP_02303)
void ウオマサ表彰式_f683a5ef5985(CTRPluginFramework::MenuEntry *entry);

// 黒くなって出てくる (GROUP_02305)
void 黒くなって出てくる_f6925eb05645(CTRPluginFramework::MenuEntry *entry);

// ぽむぽむ (GROUP_02306)
void ぽむぽむ_f6b0def3e4de(CTRPluginFramework::MenuEntry *entry);

// 早着替え [R] (GROUP_02307)
void 早着替え_R_f6dbff17f7cf(CTRPluginFramework::MenuEntry *entry);

// 捨てる (GROUP_02312)
void 捨てる_f7470c3f7c29(CTRPluginFramework::MenuEntry *entry);

// 日焼け5 (GROUP_02314)
void 日焼け5_f761e0e5eb34(CTRPluginFramework::MenuEntry *entry);

// 赤いポスト (GROUP_02321)
void 赤いポスト_f8293c7dfadf(CTRPluginFramework::MenuEntry *entry);

// 影 海ピンク (GROUP_02323)
void 影_海ピンク_f82daa214875(CTRPluginFramework::MenuEntry *entry);

// 指定した色に光る (GROUP_02324)
void 指定した色に光る_f8479ff6a0fb(CTRPluginFramework::MenuEntry *entry);

// チート:常時オン推奨/コマンド (GROUP_02328)
void チート_常時オン推奨_コマンド_f8a2af1048d3(CTRPluginFramework::MenuEntry *entry);

// ログハウスの丸ドア (GROUP_02333)
void ログハウスの丸ドア_f8ec9b6b7e79(CTRPluginFramework::MenuEntry *entry);

// 四角い重いドア (GROUP_02334)
void 四角い重いドア_f935eab72154(CTRPluginFramework::MenuEntry *entry);

// 飛び込み (GROUP_02335)
void 飛び込み_f94a3d3a6807(CTRPluginFramework::MenuEntry *entry);

// わ! (GROUP_02338)
void わ_f9aa0d4945ba(CTRPluginFramework::MenuEntry *entry);

// セーブメニュー無効 (GROUP_02340)
void セーブメニュー無効_f9e11443853f(CTRPluginFramework::MenuEntry *entry);

// 美容院 完成 (GROUP_02344)
void 美容院_完成_fa72e53243d2(CTRPluginFramework::MenuEntry *entry);

// 蚊にさされなくなる (GROUP_02347)
void 蚊にさされなくなる_fad5d8a8af18(CTRPluginFramework::MenuEntry *entry);

// 住人1 (GROUP_02351)
void 住人1_fb5fad71b0ce(CTRPluginFramework::MenuEntry *entry);

// 風船セット (GROUP_02353)
void 風船セット_fb7020ae98f1(CTRPluginFramework::MenuEntry *entry);

// スペシャルバッチ-D (GROUP_02355)
void スペシャルバッチ_D_fb9501a76386(CTRPluginFramework::MenuEntry *entry);

// 髪型変更するときオンにすること (GROUP_02356)
void 髪型変更するときオンにすること_fbda775be988(CTRPluginFramework::MenuEntry *entry);

// ドロップスパム (GROUP_02362)
void ドロップスパム_fc272ad8455d(CTRPluginFramework::MenuEntry *entry);

// 55555 (GROUP_02368)
void Cheat_55555_fc9b179c8257(CTRPluginFramework::MenuEntry *entry);

// カラフルな屋根 (GROUP_02370)
void カラフルな屋根_fcb61061daf4(CTRPluginFramework::MenuEntry *entry);

// 博物館F2 完成 (GROUP_02373)
void 博物館F2_完成_fd17ac8c34f6(CTRPluginFramework::MenuEntry *entry);

// 65535 (GROUP_02374)
void Cheat_65535_fd2f61617a18(CTRPluginFramework::MenuEntry *entry);

// 博物館2階 右奥 (GROUP_02379)
void 博物館2階_右奥_fe4de75de291(CTRPluginFramework::MenuEntry *entry);

// 2明るい茶色 (GROUP_02381)
void Cheat_2明るい茶色_fe51f8e1305a(CTRPluginFramework::MenuEntry *entry);

// 和風なポスト (GROUP_02382)
void 和風なポスト_fe557210f7e4(CTRPluginFramework::MenuEntry *entry);

// 住人8の引っ越し解除 (GROUP_02384)
void 住人8の引っ越し解除_fe6307be7ab2(CTRPluginFramework::MenuEntry *entry);

// NPC動作乗っ取り (GROUP_02389)
void NPC動作乗っ取り_fef365f652aa(CTRPluginFramework::MenuEntry *entry);

// 白い屋根 (GROUP_02393)
void 白い屋根_ff6b4a396d4f(CTRPluginFramework::MenuEntry *entry);

// 1919 (GROUP_02398)
void Cheat_1919_ffdfcfbc82b2(CTRPluginFramework::MenuEntry *entry);

} }
