// Generated by tools/cheat_collection; IDA-gpt-6.1-sol-F018 / gpt-6.1-sol.
// AR semantics derived from CTRPluginFramework; retain LICENSE.CTRPluginFramework.txt.
#pragma once
#include <CTRPluginFramework.hpp>

namespace ReferenceCheats { namespace WorldTown {

// ホームセンタ (GROUP_00004)
void ホームセンタ_00545e3471b8(CTRPluginFramework::MenuEntry *entry);

// 建物から出る (GROUP_00017)
void 建物から出る_01e16c5d5779(CTRPluginFramework::MenuEntry *entry);

// ハニワ 黄金ベンチ (GROUP_00033)
void ハニワ_黄金ベンチ_038b31295dd5(CTRPluginFramework::MenuEntry *entry);

// 快晴 (GROUP_00039)
void 快晴_03e58fa9634e(CTRPluginFramework::MenuEntry *entry);

// kuku 2 (GROUP_00046)
void kuku_2_049e51f65c8c(CTRPluginFramework::MenuEntry *entry);

// 大雪 (GROUP_00062)
void 大雪_05fd9f003c69(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(24番)に行く (GROUP_00072)
void 待ち合わせのチーターの島_24番_に行く_06e350b3226e(CTRPluginFramework::MenuEntry *entry);

// 花を置く2P (GROUP_00073)
void 花を置く2P_06ec54f68f66(CTRPluginFramework::MenuEntry *entry);

// 喫茶店(バイト中) (GROUP_00083)
void 喫茶店_バイト中_08102a505ef9(CTRPluginFramework::MenuEntry *entry);

// 謎3 (GROUP_00085)
void 謎3_085a06595167(CTRPluginFramework::MenuEntry *entry);

// 崖(坂あり) (GROUP_00089)
void 崖_坂あり_08c23e4af8ac(CTRPluginFramework::MenuEntry *entry);

// 朝方の条例 (GROUP_00093)
void 朝方の条例_0907d3b94e75(CTRPluginFramework::MenuEntry *entry);

// クク 4 (GROUP_00096)
void クク_4_0952a65471dc(CTRPluginFramework::MenuEntry *entry);

// 3-5の地形変更 (GROUP_00110)
void Cheat_3_5の地形変更_0b1888f4dc60(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(39番)に行く (GROUP_00147)
void 待ち合わせのチーターの島_39番_に行く_10964f80f58b(CTRPluginFramework::MenuEntry *entry);

// ハニワ 駅 (GROUP_00148)
void ハニワ_駅_10b40fa20d1e(CTRPluginFramework::MenuEntry *entry);

// ユリセット (GROUP_00154)
void ユリセット_11b47baef9bc(CTRPluginFramework::MenuEntry *entry);

// 晴れ (GROUP_00160)
void 晴れ_122f84fcca00(CTRPluginFramework::MenuEntry *entry);

// クク 3 自分の場所 (GROUP_00171)
void クク_3_自分の場所_13868ee45348(CTRPluginFramework::MenuEntry *entry);

// ばばあ 4 自分の場所 (GROUP_00191)
void ばばあ_4_自分の場所_15385714f6df(CTRPluginFramework::MenuEntry *entry);

// ライチ (GROUP_00196)
void ライチ_15c1f3819fd1(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(5番)に行く (GROUP_00197)
void 待ち合わせのチーターの島_5番_に行く_15c9f33d4833(CTRPluginFramework::MenuEntry *entry);

// 島のお土産 (GROUP_00206)
void 島のお土産_16c1ca86eb3d(CTRPluginFramework::MenuEntry *entry);

// ノルウェー (GROUP_00221)
void ノルウェー_183612c0a3b3(CTRPluginFramework::MenuEntry *entry);

// 花柄の壁 (GROUP_00226)
void 花柄の壁_18fd567952a3(CTRPluginFramework::MenuEntry *entry);

// レモン (GROUP_00238)
void レモン_1a78cb927f05(CTRPluginFramework::MenuEntry *entry);

// マンゴー (GROUP_00240)
void マンゴー_1aafd0fd1a50(CTRPluginFramework::MenuEntry *entry);

// オートキャンプ左 (GROUP_00248)
void オートキャンプ左_1b547eb028a7(CTRPluginFramework::MenuEntry *entry);

// 木をドラッグで置けるようにする (GROUP_00265)
void 木をドラッグで置けるようにする_1e5549707483(CTRPluginFramework::MenuEntry *entry);

// 花を置く1P (GROUP_00305)
void 花を置く1P_22529f5306bf(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(35番)に行く (GROUP_00325)
void 待ち合わせのチーターの島_35番_に行く_24caeb507296(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(38番)に行く (GROUP_00339)
void 待ち合わせのチーターの島_38番_に行く_25e1ebc41fde(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(37番)に行く (GROUP_00343)
void 待ち合わせのチーターの島_37番_に行く_266429f70e57(CTRPluginFramework::MenuEntry *entry);

// イタリア (GROUP_00348)
void イタリア_26bac3b27f29(CTRPluginFramework::MenuEntry *entry);

// 広場の木に変更 (GROUP_00373)
void 広場の木に変更_28eb7ac9024c(CTRPluginFramework::MenuEntry *entry);

// g 3 (GROUP_00381)
void g_3_297badb14e0b(CTRPluginFramework::MenuEntry *entry);

// クーコ 3 自分の場所 (GROUP_00382)
void クーコ_3_自分の場所_29c70cb4071e(CTRPluginFramework::MenuEntry *entry);

// 広場の木 (GROUP_00385)
void 広場の木_29f7f669cc09(CTRPluginFramework::MenuEntry *entry);

// その他の花セット (GROUP_00399)
void その他の花セット_2bf410dfebbd(CTRPluginFramework::MenuEntry *entry);

// キノえもん島 (GROUP_00401)
void キノえもん島_2c3c47cffbae(CTRPluginFramework::MenuEntry *entry);

// Turks/Caicos Islands (GROUP_00418)
void Turks_Caicos_Islands_2ded60701cda(CTRPluginFramework::MenuEntry *entry);

// オン島でフレンド申請(解除) (GROUP_00436)
void オン島でフレンド申請_解除_2f9bf3f6d621(CTRPluginFramework::MenuEntry *entry);

// ナシ (GROUP_00439)
void ナシ_301ec3dde3e3(CTRPluginFramework::MenuEntry *entry);

// 改造島3 (GROUP_00460)
void 改造島3_3291a1bbaed6(CTRPluginFramework::MenuEntry *entry);

// クーコ 2 (GROUP_00465)
void クーコ_2_33191f892652(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(42番)に行く (GROUP_00476)
void 待ち合わせのチーターの島_42番_に行く_34c2c3e52b6a(CTRPluginFramework::MenuEntry *entry);

// 島(中) (GROUP_00477)
void 島_中_34de57de6b7f(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(22番)に行く (GROUP_00484)
void 待ち合わせのチーターの島_22番_に行く_3571e1730251(CTRPluginFramework::MenuEntry *entry);

// 島メダル (GROUP_00494)
void 島メダル_36541a7811b8(CTRPluginFramework::MenuEntry *entry);

// o (GROUP_00511)
void o_381eeebd5c19(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(28番)に行く (GROUP_00518)
void 待ち合わせのチーターの島_28番_に行く_386717f4a064(CTRPluginFramework::MenuEntry *entry);

// 島のメダル (GROUP_00519)
void 島のメダル_387258f31b7f(CTRPluginFramework::MenuEntry *entry);

// ポルトガル (GROUP_00524)
void ポルトガル_38c3efc25ccc(CTRPluginFramework::MenuEntry *entry);

// 薔薇セット (GROUP_00525)
void 薔薇セット_38cdb587883d(CTRPluginFramework::MenuEntry *entry);

// 草の屋根 (GROUP_00533)
void 草の屋根_3a12f009af9b(CTRPluginFramework::MenuEntry *entry);

// 村のコンシェルジュ (GROUP_00543)
void 村のコンシェルジュ_3b3d73d8ae27(CTRPluginFramework::MenuEntry *entry);

// NPC クラッカー (GROUP_00546)
void NPC_クラッカー_3b89e1091e6d(CTRPluginFramework::MenuEntry *entry);

// ポーランド (GROUP_00549)
void ポーランド_3bb17d6d134f(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(8番)に行く (GROUP_00588)
void 待ち合わせのチーターの島_8番_に行く_3fbe91ea7e4d(CTRPluginFramework::MenuEntry *entry);

// モモ (GROUP_00612)
void モモ_4290d3483c5e(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(48番)に行く (GROUP_00615)
void 待ち合わせのチーターの島_48番_に行く_42f0d52eb1e2(CTRPluginFramework::MenuEntry *entry);

// カーネーションセット (GROUP_00620)
void カーネーションセット_4332d07c03eb(CTRPluginFramework::MenuEntry *entry);

// 木を持つ (GROUP_00639)
void 木を持つ_44b9e8752830(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(12番)に行く (GROUP_00641)
void 待ち合わせのチーターの島_12番_に行く_44d143ae0efb(CTRPluginFramework::MenuEntry *entry);

// ASM乗っ取りP2 (GROUP_00642)
void ASM乗っ取りP2_44fa3174fa0a(CTRPluginFramework::MenuEntry *entry);

// バナナ (GROUP_00655)
void バナナ_46b70e33850b(CTRPluginFramework::MenuEntry *entry);

// 全部川 (GROUP_00695)
void 全部川_4aa1d32d59aa(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(7番)に行く (GROUP_00707)
void 待ち合わせのチーターの島_7番_に行く_4bcf37d9e387(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(31番)に行く (GROUP_00718)
void 待ち合わせのチーターの島_31番_に行く_4c86ef418cc3(CTRPluginFramework::MenuEntry *entry);

// 植木 (GROUP_00741)
void 植木_4e75d254259e(CTRPluginFramework::MenuEntry *entry);

// メルヘンな時計に変更 (GROUP_00743)
void メルヘンな時計に変更_4e92098e998e(CTRPluginFramework::MenuEntry *entry);

// 木枠の壁 (GROUP_00751)
void 木枠の壁_4fbfa0491206(CTRPluginFramework::MenuEntry *entry);

// 雪 (GROUP_00752)
void 雪_4fd9f1735df2(CTRPluginFramework::MenuEntry *entry);

// 空から降るもの消す (GROUP_00755)
void 空から降るもの消す_507670a403ff(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(11番)に行く (GROUP_00765)
void 待ち合わせのチーターの島_11番_に行く_515ab89b2212(CTRPluginFramework::MenuEntry *entry);

// 靴 (GROUP_00778)
void 靴_51f4e308ddd4(CTRPluginFramework::MenuEntry *entry);

// 島(外) (GROUP_00787)
void 島_外_5357d59cffc7(CTRPluginFramework::MenuEntry *entry);

// ボタン式エラーB (GROUP_00795)
void ボタン式エラーB_53f22392c8b1(CTRPluginFramework::MenuEntry *entry);

// クーコ 4 自分の場所 (GROUP_00798)
void クーコ_4_自分の場所_544f768847be(CTRPluginFramework::MenuEntry *entry);

// 揺する動作変更 (GROUP_00801)
void 揺する動作変更_54c6fe56eecf(CTRPluginFramework::MenuEntry *entry);

// 4-5の地形変更 (GROUP_00805)
void Cheat_4_5の地形変更_55107f3fd677(CTRPluginFramework::MenuEntry *entry);

// コスモスセット (GROUP_00812)
void コスモスセット_55a280d66a4b(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(6番)に行く (GROUP_00834)
void 待ち合わせのチーターの島_6番_に行く_58a64794737d(CTRPluginFramework::MenuEntry *entry);

// ズボン (GROUP_00847)
void ズボン_59b576da5505(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(17番)に行く (GROUP_00849)
void 待ち合わせのチーターの島_17番_に行く_59e496510c50(CTRPluginFramework::MenuEntry *entry);

// ルーマニア (GROUP_00855)
void ルーマニア_5a4b6f60ff4e(CTRPluginFramework::MenuEntry *entry);

// お引き取りBOX機能変更(島) (GROUP_00869)
void お引き取りBOX機能変更_島_5c5c1839ee38(CTRPluginFramework::MenuEntry *entry);

// ばばあ 2 自分の場所 (GROUP_00882)
void ばばあ_2_自分の場所_5db8a1216f20(CTRPluginFramework::MenuEntry *entry);

// 海 (GROUP_00892)
void 海_5e6cd83f6df9(CTRPluginFramework::MenuEntry *entry);

// 島品変更3 (GROUP_00922)
void 島品変更3_61748ffd1ec7(CTRPluginFramework::MenuEntry *entry);

// 島の建物を中心に (GROUP_00942)
void 島の建物を中心に_63c97b753db5(CTRPluginFramework::MenuEntry *entry);

// 没サーバー (GROUP_00945)
void 没サーバー_644b920d6ed8(CTRPluginFramework::MenuEntry *entry);

// オーストラリア1 (GROUP_00952)
void オーストラリア1_659687f7710f(CTRPluginFramework::MenuEntry *entry);

// 花を置く3P (GROUP_00975)
void 花を置く3P_67a76dc61584(CTRPluginFramework::MenuEntry *entry);

// g 6 (GROUP_00982)
void g_6_686af6ac1b14(CTRPluginFramework::MenuEntry *entry);

// オートキャンプ右 (GROUP_00985)
void オートキャンプ右_689de91e38a8(CTRPluginFramework::MenuEntry *entry);

// チューリップセット (GROUP_00991)
void チューリップセット_6943c3cba35c(CTRPluginFramework::MenuEntry *entry);

// チーター島(けんじい) (GROUP_00992)
void チーター島_けんじい_6959b14e9c63(CTRPluginFramework::MenuEntry *entry);

// 服/ワンピース (GROUP_01010)
void 服_ワンピース_6b3a2d9adb95(CTRPluginFramework::MenuEntry *entry);

// 美しい条例 (GROUP_01016)
void 美しい条例_6c88094128fc(CTRPluginFramework::MenuEntry *entry);

// オーキャンの入り口 (GROUP_01065)
void オーキャンの入り口_71a77b17e75f(CTRPluginFramework::MenuEntry *entry);

// 木を揺らす (GROUP_01071)
void 木を揺らす_727c2060ae69(CTRPluginFramework::MenuEntry *entry);

// ドリアン (GROUP_01072)
void ドリアン_7288f6903ec9(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(32番)に行く (GROUP_01086)
void 待ち合わせのチーターの島_32番_に行く_738e5b7e5af5(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(36番)に行く (GROUP_01116)
void 待ち合わせのチーターの島_36番_に行く_77042a65aa92(CTRPluginFramework::MenuEntry *entry);

// ツアー強制終了 (GROUP_01135)
void ツアー強制終了_79bc14f505dc(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(10番)に行く (GROUP_01144)
void 待ち合わせのチーターの島_10番_に行く_7b240eb57b0b(CTRPluginFramework::MenuEntry *entry);

// 通常営業 (GROUP_01181)
void 通常営業_7e8a48823249(CTRPluginFramework::MenuEntry *entry);

// アクセサリー (GROUP_01183)
void アクセサリー_7ebda1f2c225(CTRPluginFramework::MenuEntry *entry);

// クーコ 2 自分の場所 (GROUP_01193)
void クーコ_2_自分の場所_7f64ef417496(CTRPluginFramework::MenuEntry *entry);

// 雨 (GROUP_01230)
void 雨_83ac62b5555a(CTRPluginFramework::MenuEntry *entry);

// palntino (GROUP_01286)
void palntino_89c6a333c6d5(CTRPluginFramework::MenuEntry *entry);

// ヤシの実 (GROUP_01334)
void ヤシの実_8e4f25646ab6(CTRPluginFramework::MenuEntry *entry);

// おき花火の燃えカスが出ない (GROUP_01339)
void おき花火の燃えカスが出ない_8ea1e96227b9(CTRPluginFramework::MenuEntry *entry);

// 崖(坂ない) (GROUP_01342)
void 崖_坂ない_8f3c8168565f(CTRPluginFramework::MenuEntry *entry);

// ハニワ Rパカーズ (GROUP_01346)
void ハニワ_Rパカーズ_8fb2e0c5d821(CTRPluginFramework::MenuEntry *entry);

// kappei (GROUP_01350)
void kappei_902bf7d855b5(CTRPluginFramework::MenuEntry *entry);

// ばばあ 2 (GROUP_01351)
void ばばあ_2_903ed21409d0(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(45番)に行く (GROUP_01363)
void 待ち合わせのチーターの島_45番_に行く_917639ddf3c9(CTRPluginFramework::MenuEntry *entry);

// yで鉱石 (GROUP_01369)
void yで鉱石_9215767a9468(CTRPluginFramework::MenuEntry *entry);

// 全ての条例の効果 (GROUP_01370)
void 全ての条例の効果_921921ad2660(CTRPluginFramework::MenuEntry *entry);

// たけのこ (GROUP_01375)
void たけのこ_92c75d64d795(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(23番)に行く (GROUP_01379)
void 待ち合わせのチーターの島_23番_に行く_9389788651e6(CTRPluginFramework::MenuEntry *entry);

// イギリス (GROUP_01407)
void イギリス_97705ecca0ca(CTRPluginFramework::MenuEntry *entry);

// キャンプ場 (GROUP_01414)
void キャンプ場_97f37464f7bc(CTRPluginFramework::MenuEntry *entry);

// 靴下 (GROUP_01432)
void 靴下_99b9352e75f3(CTRPluginFramework::MenuEntry *entry);

// ドイツ (GROUP_01456)
void ドイツ_9be544a576e8(CTRPluginFramework::MenuEntry *entry);

// ASM乗っ取りP4 (GROUP_01466)
void ASM乗っ取りP4_9d43d8e6dab1(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(43番)に行く (GROUP_01476)
void 待ち合わせのチーターの島_43番_に行く_9e79d49c8bc4(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(14番)に行く (GROUP_01486)
void 待ち合わせのチーターの島_14番_に行く_9f6189a3d8b6(CTRPluginFramework::MenuEntry *entry);

// 柿 (GROUP_01502)
void 柿_a17daf58652c(CTRPluginFramework::MenuEntry *entry);

// 帽子/仮面 (GROUP_01506)
void 帽子_仮面_a1e67002ead7(CTRPluginFramework::MenuEntry *entry);

// 改造島2 (GROUP_01507)
void 改造島2_a1e8664f5659(CTRPluginFramework::MenuEntry *entry);

// bellina (GROUP_01518)
void bellina_a2ed3d7adaa5(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(9番)に行く (GROUP_01529)
void 待ち合わせのチーターの島_9番_に行く_a3f3accf01b0(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(27番)に行く (GROUP_01532)
void 待ち合わせのチーターの島_27番_に行く_a4159de4d9e4(CTRPluginFramework::MenuEntry *entry);

// オーストラリア2 (GROUP_01547)
void オーストラリア2_a6135c78aff9(CTRPluginFramework::MenuEntry *entry);

// クク 2 自分の場所 (GROUP_01606)
void クク_2_自分の場所_ab2c60dc19e9(CTRPluginFramework::MenuEntry *entry);

// オン島で数字3文字以上送信できる (GROUP_01623)
void オン島で数字3文字以上送信できる_acd3e1d80640(CTRPluginFramework::MenuEntry *entry);

// 曇り (GROUP_01626)
void 曇り_ad2f98dcede2(CTRPluginFramework::MenuEntry *entry);

// 1-5の地形変更 (GROUP_01628)
void Cheat_1_5の地形変更_ad742d34ca79(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(3番)に行く (GROUP_01629)
void 待ち合わせのチーターの島_3番_に行く_adcb61715ec0(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(29番)に行く (GROUP_01648)
void 待ち合わせのチーターの島_29番_に行く_b11e69bd0e91(CTRPluginFramework::MenuEntry *entry);

// リンゴ (GROUP_01685)
void リンゴ_b56126743850(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(4番)に行く (GROUP_01688)
void 待ち合わせのチーターの島_4番_に行く_b59bff8b8eeb(CTRPluginFramework::MenuEntry *entry);

// 木のポスト (GROUP_01689)
void 木のポスト_b5b1d2045997(CTRPluginFramework::MenuEntry *entry);

// 木を揺するだけで切れる (GROUP_01729)
void 木を揺するだけで切れる_ba12d03609b7(CTRPluginFramework::MenuEntry *entry);

// 木をドラッグで置く解除 (GROUP_01737)
void 木をドラッグで置く解除_baddc054799c(CTRPluginFramework::MenuEntry *entry);

// 謎1 (GROUP_01743)
void 謎1_bb772398cd20(CTRPluginFramework::MenuEntry *entry);

// サクランボ (GROUP_01748)
void サクランボ_bbc5befa2782(CTRPluginFramework::MenuEntry *entry);

// 全部海 (GROUP_01762)
void 全部海_bdf92d5a2e9e(CTRPluginFramework::MenuEntry *entry);

// 謎2 (GROUP_01765)
void 謎2_be3c00355669(CTRPluginFramework::MenuEntry *entry);

// クク 4 自分の場所 (GROUP_01781)
void クク_4_自分の場所_bffbf0f994d6(CTRPluginFramework::MenuEntry *entry);

// ASM乗っ取りP1 (GROUP_01791)
void ASM乗っ取りP1_c0e3fbe9bdd7(CTRPluginFramework::MenuEntry *entry);

// 帰らせる (GROUP_01792)
void 帰らせる_c100ac65c0f3(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(46番)に行く (GROUP_01797)
void 待ち合わせのチーターの島_46番_に行く_c1657dffe3c9(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(33番)に行く (GROUP_01829)
void 待ち合わせのチーターの島_33番_に行く_c4c132d3f066(CTRPluginFramework::MenuEntry *entry);

// すみれセット (GROUP_01830)
void すみれセット_c4e5881d360d(CTRPluginFramework::MenuEntry *entry);

// ばばあ 3 自分の場所 (GROUP_01843)
void ばばあ_3_自分の場所_c6939db17ef0(CTRPluginFramework::MenuEntry *entry);

// ハニワ 広場の木 (GROUP_01865)
void ハニワ_広場の木_c882aaa44b21(CTRPluginFramework::MenuEntry *entry);

// チーター島(Lukas) (GROUP_01880)
void チーター島_Lukas_caa8be6f9228(CTRPluginFramework::MenuEntry *entry);

// 木を切る度に切り倒すエフェクト出現 (GROUP_01905)
void 木を切る度に切り倒すエフェクト出現_ce23c0e997da(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(21番)に行く (GROUP_01906)
void 待ち合わせのチーターの島_21番_に行く_ce25fda5bd20(CTRPluginFramework::MenuEntry *entry);

// パンジーセット (GROUP_01933)
void パンジーセット_d122a853ed0f(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(47番)に行く (GROUP_01943)
void 待ち合わせのチーターの島_47番_に行く_d2397a37d488(CTRPluginFramework::MenuEntry *entry);

// スペイン (GROUP_01973)
void スペイン_d52099d16adb(CTRPluginFramework::MenuEntry *entry);

// オンラインアニメーション (GROUP_01993)
void オンラインアニメーション_d73bf3b0c647(CTRPluginFramework::MenuEntry *entry);

// 世界島 (GROUP_02000)
void 世界島_d8031310131d(CTRPluginFramework::MenuEntry *entry);

// US Virgin Islands (GROUP_02006)
void US_Virgin_Islands_d8856ef0e680(CTRPluginFramework::MenuEntry *entry);

// 全て穴判定 (GROUP_02026)
void 全て穴判定_db3029020673(CTRPluginFramework::MenuEntry *entry);

// 大雨 (GROUP_02031)
void 大雨_db527fe1a0f9(CTRPluginFramework::MenuEntry *entry);

// 全部駅 (GROUP_02043)
void 全部駅_dc3213eae171(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(20番)に行く (GROUP_02057)
void 待ち合わせのチーターの島_20番_に行く_dcfc40d0886f(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(40番)に行く (GROUP_02098)
void 待ち合わせのチーターの島_40番_に行く_e1e74f0cc38c(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(19番)に行く (GROUP_02152)
void 待ち合わせのチーターの島_19番_に行く_e669ebc8a7de(CTRPluginFramework::MenuEntry *entry);

// kuku' 2 (GROUP_02161)
void kuku_2_e73b6ab94d95(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(15番)に行く (GROUP_02165)
void 待ち合わせのチーターの島_15番_に行く_e795a3239fe1(CTRPluginFramework::MenuEntry *entry);

// ずっと営業 (GROUP_02169)
void ずっと営業_e822158bdab1(CTRPluginFramework::MenuEntry *entry);

// 2-5の地形変更 (GROUP_02171)
void Cheat_2_5の地形変更_e878a9ce1766(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(41番)に行く (GROUP_02205)
void 待ち合わせのチーターの島_41番_に行く_ec1a5db11188(CTRPluginFramework::MenuEntry *entry);

// 改造島1 (GROUP_02207)
void 改造島1_ec5226e98aa2(CTRPluginFramework::MenuEntry *entry);

// イギリス領ヴァージン諸島 (GROUP_02221)
void イギリス領ヴァージン諸島_ee457310d2c3(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(25番)に行く (GROUP_02247)
void 待ち合わせのチーターの島_25番_に行く_f0d6ed8252d4(CTRPluginFramework::MenuEntry *entry);

// 村長 -> 自分 (GROUP_02254)
void 村長_自分_f18a2e89ab3d(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(30番)に行く (GROUP_02255)
void 待ち合わせのチーターの島_30番_に行く_f1e67c7ab462(CTRPluginFramework::MenuEntry *entry);

// 花を置く4P (GROUP_02263)
void 花を置く4P_f25ab224f153(CTRPluginFramework::MenuEntry *entry);

// 時計非表示 (GROUP_02267)
void 時計非表示_f300db1657af(CTRPluginFramework::MenuEntry *entry);

// 喫茶店 (GROUP_02270)
void 喫茶店_f3323c0ecd30(CTRPluginFramework::MenuEntry *entry);

// ASM乗っ取りP3 (GROUP_02281)
void ASM乗っ取りP3_f484e1fc8321(CTRPluginFramework::MenuEntry *entry);

// ケイマン諸島 (GROUP_02298)
void ケイマン諸島_f5e7c350baa1(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(34番)に行く (GROUP_02315)
void 待ち合わせのチーターの島_34番_に行く_f765e3b15f6f(CTRPluginFramework::MenuEntry *entry);

// 商品変更4 (GROUP_02319)
void 商品変更4_f7cd190d8ac6(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(26番)に行く (GROUP_02320)
void 待ち合わせのチーターの島_26番_に行く_f810199a5576(CTRPluginFramework::MenuEntry *entry);

// 交番 (GROUP_02332)
void 交番_f8e8fc012857(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(44番)に行く (GROUP_02375)
void 待ち合わせのチーターの島_44番_に行く_fd7255dd818c(CTRPluginFramework::MenuEntry *entry);

// 待ち合わせのチーターの島(13番)に行く (GROUP_02376)
void 待ち合わせのチーターの島_13番_に行く_fdb7ea0780ae(CTRPluginFramework::MenuEntry *entry);

} }
