// Generated by CTRPF-GUI-Simulator/tools/extract_pixel_mplus_10_numeric_8.py.
// Source: PixelMplus10 M+ 10 px BDF; unchanged pixels in an 8 px cell.
#include "PixelMplus10Numeric8.hpp"

#include <CTRPluginFramework.hpp>

namespace CTRPluginFramework
{
    namespace PixelMplus10Numeric8
    {
        namespace
        {
            struct Glyph
            {
                u32 codepoint;
                u8  width;
                u8  height;
                s8  offsetX;
                s8  offsetY;
                u8  advance;
                u16 rows[8];
            };

            static const Glyph kGlyphs[] =
            {
                {0x0030, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x000D, 0x000B, 0x0009, 0x0009, 0x0006, 0x0000}}, // 0
                {0x0031, 5, 8, 0, 0, 5, {0x0004, 0x0006, 0x0005, 0x0004, 0x0004, 0x0004, 0x0004, 0x0000}}, // 1
                {0x0032, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x0008, 0x0004, 0x0002, 0x0001, 0x000F, 0x0000}}, // 2
                {0x0033, 5, 8, 0, 0, 5, {0x000F, 0x0008, 0x0004, 0x0006, 0x0008, 0x0009, 0x0006, 0x0000}}, // 3
                {0x0034, 5, 8, 0, 0, 5, {0x0004, 0x0006, 0x0005, 0x0005, 0x000F, 0x0004, 0x0004, 0x0000}}, // 4
                {0x0035, 5, 8, 0, 0, 5, {0x000F, 0x0001, 0x0007, 0x0008, 0x0008, 0x0009, 0x0006, 0x0000}}, // 5
                {0x0036, 5, 8, 0, 0, 5, {0x0006, 0x0001, 0x0007, 0x0009, 0x0009, 0x0009, 0x0006, 0x0000}}, // 6
                {0x0037, 5, 8, 0, 0, 5, {0x000F, 0x0008, 0x0004, 0x0004, 0x0002, 0x0002, 0x0002, 0x0000}}, // 7
                {0x0038, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x0009, 0x0006, 0x0009, 0x0009, 0x0006, 0x0000}}, // 8
                {0x0039, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x0009, 0x0009, 0x000E, 0x0008, 0x0006, 0x0000}}, // 9
                {0x0041, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x0009, 0x000F, 0x0009, 0x0009, 0x0009, 0x0000}}, // A
                {0x0042, 5, 8, 0, 0, 5, {0x0007, 0x0009, 0x0009, 0x0007, 0x0009, 0x0009, 0x0007, 0x0000}}, // B
                {0x0043, 5, 8, 0, 0, 5, {0x0006, 0x0009, 0x0001, 0x0001, 0x0001, 0x0001, 0x000E, 0x0000}}, // C
                {0x0044, 5, 8, 0, 0, 5, {0x0007, 0x0009, 0x0009, 0x0009, 0x0009, 0x0009, 0x0007, 0x0000}}, // D
                {0x0045, 5, 8, 0, 0, 5, {0x000F, 0x0001, 0x0001, 0x0007, 0x0001, 0x0001, 0x000F, 0x0000}}, // E
                {0x0046, 5, 8, 0, 0, 5, {0x000F, 0x0001, 0x0001, 0x0007, 0x0001, 0x0001, 0x0001, 0x0000}}, // F
                {0x0061, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0006, 0x0008, 0x000E, 0x0009, 0x000E, 0x0000}}, // a
                {0x0062, 5, 8, 0, 0, 5, {0x0001, 0x0001, 0x0007, 0x0009, 0x0009, 0x0009, 0x0007, 0x0000}}, // b
                {0x0063, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0006, 0x0009, 0x0001, 0x0001, 0x000E, 0x0000}}, // c
                {0x0064, 5, 8, 0, 0, 5, {0x0008, 0x0008, 0x000E, 0x0009, 0x0009, 0x0009, 0x000E, 0x0000}}, // d
                {0x0065, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0006, 0x0009, 0x000F, 0x0001, 0x000E, 0x0000}}, // e
                {0x0066, 5, 8, 0, 0, 5, {0x000C, 0x0002, 0x0002, 0x000F, 0x0002, 0x0002, 0x0002, 0x0000}}, // f
                {0x0078, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0009, 0x0009, 0x0006, 0x0009, 0x0009, 0x0000}}, // x
                {0x0058, 5, 8, 0, 0, 5, {0x0009, 0x0009, 0x0009, 0x0006, 0x0009, 0x0009, 0x0009, 0x0000}}, // X
                {0x002E, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000}}, // .
                {0x002B, 5, 8, 0, 0, 5, {0x0000, 0x0004, 0x0004, 0x000F, 0x0004, 0x0004, 0x0000, 0x0000}}, // +
                {0x002D, 5, 8, 0, 0, 5, {0x0000, 0x0000, 0x0000, 0x000F, 0x0000, 0x0000, 0x0000, 0x0000}}, // -
            };

            static const Glyph *FindGlyph(u32 codepoint)
            {
                const u32 count = sizeof(kGlyphs) / sizeof(kGlyphs[0]);
                for (u32 index = 0; index < count; ++index)
                    if (kGlyphs[index].codepoint == codepoint)
                        return &kGlyphs[index];
                return nullptr;
            }
        }

        int LineHeight(void) { return 8; }

        int Measure(const std::string &text)
        {
            int width = 0;
            for (u32 index = 0; index < text.size(); ++index)
            {
                const Glyph *glyph = FindGlyph(static_cast<u8>(text[index]));
                width += glyph ? glyph->advance : 4;
            }
            return width;
        }

        void Draw(const Screen &screen, const std::string &text, int x, int y, const Color &color)
        {
            int cursor = x;
            for (u32 index = 0; index < text.size(); ++index)
            {
                const Glyph *glyph = FindGlyph(static_cast<u8>(text[index]));
                if (glyph == nullptr)
                {
                    cursor += 4;
                    continue;
                }
                for (u32 row = 0; row < glyph->height; ++row)
                {
                    const u16 bits = glyph->rows[row];
                    for (u32 column = 0; column < glyph->width; ++column)
                        if (bits & (1U << column))
                        {
                            const int pixelX = cursor + glyph->offsetX + column;
                            const int pixelY = y + glyph->offsetY + row;
                            const int screenWidth = screen.IsTop ? 400 : 320;
                            if (pixelX >= 0 && pixelX < screenWidth && pixelY >= 0 && pixelY < 240)
                                screen.DrawPixel(pixelX, pixelY, color);
                        }
                }
                cursor += glyph->advance;
            }
        }
    }
}
