// Generated by tools/gridcursor/build_frame_stub.py. Do not edit.
//
// The only hand-written code in this plugin. It saves the game's registers,
// flags, FPSCR and d0-d15, calls whatever address is in its last word, and
// restores. Patch that word with the C++ callback before installing the hook,
// and write zero into it to make the stub a no-op without unhooking.
#pragma once
#include <3ds/types.h>

namespace GridCursor {
namespace Stub {

static const u32 kAddress        = 0x00838700u;  // where the stub is written
static const u32 kHookAddress    = 0x001B721Cu;  // the NOP it replaces
static const u32 kHookOriginal   = 0xE320F000u;  // put this back on uninstall
static const u32 kHookWord       = 0xEA1A0537u;  // branch to the stub
static const u32 kCallbackOffset = 0x038u;   // word to patch with the callback
static const u32 kSize           = 60u;

static const u8 kBytes[60] = {
    0xFF, 0x5F, 0x2D, 0xE9, 0x00, 0x00, 0x0F, 0xE1, 0x10, 0x1A, 0xF1, 0xEE,
    0x03, 0x00, 0x2D, 0xE9, 0x20, 0x0B, 0x2D, 0xED, 0x1C, 0xC0, 0x9F, 0xE5,
    0x00, 0x00, 0x5C, 0xE3, 0x3C, 0xFF, 0x2F, 0x11, 0x20, 0x0B, 0xBD, 0xEC,
    0x03, 0x00, 0xBD, 0xE8, 0x10, 0x1A, 0xE1, 0xEE, 0x00, 0xF0, 0x2C, 0xE1,
    0xFF, 0x5F, 0xBD, 0xE8, 0xB9, 0xFA, 0xE5, 0xEA, 0x00, 0x00, 0x00, 0x00,
};

}  // namespace Stub
}  // namespace GridCursor
