// Generated by tools/hhd/generate_room_camera_curve.py. Do not edit.
// IDA-gpt-6.1-sol-F014: HHD v1.1 JPN param [3,4,5,37], original ARM 0x5F942C.
#pragma once

namespace HhdRoomCameraControl {
struct CurvePoint { float y, distance; int pitch; };
static const CurvePoint kCurve[4][4] = {
    {
        {-10.0f, 220.0f, 5097},
        {0.0f, 330.0f, 6371},
        {0.0f, 500.0f, 10922},
        {5.0f, 500.0f, 1820},
    },
    {
        {13.0f, 82.6666641f, -509},
        {4.0f, 164.666672f, 4842},
        {1.0f, 98.6666641f, -1384},
        {0.0f, 0.0f, 0},
    },
    {
        {0.0f, 0.0f, 0},
        {-9.0f, 82.0f, 5351},
        {6.0f, -148.0f, -11577},
        {0.0f, 0.0f, 0},
    },
    {
        {-3.0f, 27.333334f, 1783},
        {5.0f, -76.6666641f, -5642},
        {-2.0f, 49.3333321f, 3859},
        {0.0f, 0.0f, 0},
    },
};
static const float kSegmentSteps[3] = {0.0700000003f, 0.0599999987f, 0.0799999982f};
static const float kAngleUnits = 182.044449f;
}  // namespace HhdRoomCameraControl
