#pragma once

// Generated by tools/strc/map_icon_pools.py (IDA-opus-5.5-F006). Do not edit.
// Map icon pool each building id takes on the lower-screen village map, obtained by
// running MapBase_AllocBuildingIcon 0x222434 for every id under Unicorn:
// 'A' pool +0x2B1C (10, count +0xB3B0), 'B' pool +0x49E4 (8, count +0xB3AC),
// 'F' fixed slot, '-' no icon (includes the ids MapBase_PlaceBuildingIcons skips).

namespace PublicWorks
{
    static const char kMapIconPool[0xFC + 1] =
    "FFFF----FFFFFFFFFF--------------"
    "--------------------------------"
    "--FFFFFFFFFFAAA-AAAAAAAAAAB-B-AA"
    "A--------A----------------------"
    "-----AA--A--A---BBBBBBBBBBBBBBBB"
    "BBBBBBBB------------------------"
    "------A-------------------------"
    "----------------------------";
}
